### ISSUE TITLE
For RAMSES runs, luminosity.py has bug on line 53: need "metal" vs "metals"

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#231]
I had to change 

    metals = simstars['metals']
to
    metals = simstars['metal']

I noticed that other routines copy s.s['metals'] = s.s['metal'] so that either work. However, I don't think this happens when working with a RAMSES snap.

I've made the change and can upload after you verify this is the case... Or, since its so simple, I'm sure you can make the change.

Aloha!

Rick S
ASU

**Comment by apontzen** [comment]
Actually I think the error is on line 134 of default_config.ini which names it 'metal'. For every other snapshot type it's called 'metals' so it ought to be for ramses too. Trouble is, by fixing this now we could break some people's code... Hmmm.... tricky

**Comment by rokroskar** [comment]
I think it was done this way to keep in line with the naming convention from RAMSES... so I'm not sure we should change anything in this case
