### ISSUE TITLE
Plotting my own arrays

### ISSUE THREAD

**Issue by nikTheCosmoGuy** [pynbody/pynbody#243]
First disclaimer i'm new to python so this maybe a dumb newbie question.

I'm trying to plot my own arrays. I followed the examples here

http://pynbody.github.io/pynbody/tutorials/pictures.html

I can recreate the density slice image but when I try to plot my own quantities, say rho squared

I type

s.gas['rhosq'] = s.gas['rho']**2    

I repeat the above command for s.star and s.dm

and finally

sph.image(h[1].g, qty='rhosq', units='g^2 cm^-6' width =100, cmap='Blues')

*Edit I forgot to say that trying to plot the density squared this way fails for me.

**Comment by apontzen** [comment]
Sorry, I don't understand what the question is! Could you expand?

**Comment by nikTheCosmoGuy** [comment]
Woops sorry I left out my question yesterday!

I want to be able to plot things like in the tutorial linked above. In that case It shows me how I can use pynbody to plot  a density slice using the test data, however I want to similarly make a plot of different values (in this case the square of the density). I thought it could do with the extra steps above but It ends up giving me a 'ValueError'.

So my question is why that way failed or if there is a better way to this?

**Comment by apontzen** [comment]
Sorry, I can't work out from your description what has gone wrong. Could you post your entire python session including the traceback of the error?

**Comment by nikTheCosmoGuy** [comment]
Hello, apologies for the delayed response. Here is my session-

----------------------------------------------------------------------------------------------------
IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib as mpl

In [2]: mpl.use('Agg')

In [3]: import pynbody

In [4]: import pynbody.plot.sph as sph

In [5]: import matplotlib.pylab as plt

In [6]: s = pynbody.load('g15784.lr.01024.gz')

In [7]: s.physical_units()

In [8]: h = s.halos()
pynbody.analysis.angmom.faceon(h[1])

In [9]: pynbody.analysis.angmom.faceon(h[1])
Out[9]: <pynbody.transformation.GenericRotation at 0x114685a50>

In [10]: sph.image(h[1].g,qty="rho",units="g cm^-3",width=100,cmap="Greys")
Out[10]: 
SimArray([[  6.68506269e-28,   6.71722090e-28,   6.74938008e-28, ...,
          7.46708991e-28,   7.43091613e-28,   7.39474284e-28],
       [  6.69959383e-28,   6.73187916e-28,   6.76416352e-28, ...,
          7.46053164e-28,   7.42610564e-28,   7.39167820e-28],
       [  6.71412497e-28,   6.74653597e-28,   6.77894792e-28, ...,
          7.45397481e-28,   7.42129467e-28,   7.38861405e-28],
       ..., 
       [  6.35471370e-28,   6.45441910e-28,   6.55412353e-28, ...,
          6.36954914e-28,   6.36451909e-28,   6.35948905e-28],
       [  6.29408976e-28,   6.39194674e-28,   6.48980324e-28, ...,
          6.33623537e-28,   6.33281732e-28,   6.32940024e-28],
       [  6.23346582e-28,   6.32947343e-28,   6.42548152e-28, ...,
          6.30292111e-28,   6.30111555e-28,   6.29931048e-28]], dtype=float32, 'g cm**-3')

In [11]:  plt.savefig('gas')

In [12]: s.gas['rhosq'] = s.gas['rho']**2     // here I attempt to define the density squared

In [13]: sph.image(h[1].g,qty="rhosq",units="g^2 cm^-6",width=100,cmap="Greys") // and here it attempt to plot it
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-7687a4f6569c> in <module>()
----> 1 sph.image(h[1].g,qty="rhosq",units="g^2 cm^-6",width=100,cmap="Greys")

/usr/local/lib/python2.7/site-packages/pynbody/plot/sph.pyc in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, center, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    404                 im[np.where(im == 0)] = abs(im[np.where(abs(im != 0))]).min()
    405             except ValueError:
--> 406                 raise ValueError, "Failed to make a sensible logarithmic image. This probably means there are no particles in the view."
    407 
    408             # check if there are negative values -- if so, use the symmetric

ValueError: Failed to make a sensible logarithmic image. This probably means there are no particles in the view.

-------------------------------------------------------------------------------------------------------------------------
I don't understand why the particles are not in view for the case of the density squared, When it works for the case of density.

**Comment by apontzen** [comment]
Interesting case - I have tracked down the problem to the unit conversion. If I use `units="m_p^2 cm^-6"`, for example, it works fine. Delving a little deeper, it seems like the g^2 cm^-6 units are just a little too extreme for the floating point accuracy available:

```
In [40]: pynbody.units.Unit("g^2 cm^-6").in_units("Msol^2 kpc^-6")
Out[40]: 2.1820811365531364e+62
```

so it ends up multiplying the image by around 10^-62 which, to floating point accuracy, gives just zero.

Anyway, the best workaround I can offer is to use different units.

**Comment by nikTheCosmoGuy** [comment]
Ok that works. Thanks for the help!
