### ISSUE TITLE
problem with ramses star particle birth times

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#244]
The code in analysis/ramses_util.py seems to mangle the path names. When it run ramses 'part2birth' the files end up in the 'output_xxxxx' directories, while it creates the 'birth' dir at a higher level. 

I've fixed this in my code... Let me know if you'd like to merge it. See line after comment # part2birth.

    for i in range(ncpu):
        try:
            f = open('%s/birth/birth_%s.out%05d' %
                     (parent_dir, top._timestep_id, i + 1))
        except IOError:
            import os

            # birth/ doesn't exist, create it with ramses part2birth util
            os.system("cd %s; mkdir birth;" % (parent_dir))
            with open(os.devnull, 'w') as fnull:
                exit_code = subprocess.call([part2birth_path, '-inp', 'output_%s' % top._timestep_id],
                                            stdout=fnull, stderr=fnull)
               # part2birth put the files in output_<top._timestep_id> ... move to ../birth
                os.system("cd %s; mv output_%s/birth* %sbirth/;" % (parent_dir,top._timestep_id,parent_dir)) 
             f = open('%s/birth/birth_%s.out%05d' % 
                    (parent_dir, top._timestep_id, i + 1)) 

        n = fromfile(f, 'i', 1)

**Comment by apontzen** [comment]
Please do submit a pull request for this. Thanks!

**Comment by earnric** [comment]
fixed in my fork: earnric/pynbody.

**Comment by apontzen** [comment]
Great. Could you open a pull request? See here for more info: https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request

**Comment by earnric** [comment]
Done… 
Cheers!

Rick Sarmento
SESE Astronomy/Astrophysics Grad Student
rsarment@asu.edu
