### ISSUE TITLE
Pip install looks for version 0.2 then fails

### ISSUE THREAD

**Issue by ajclarke90** [pynbody/pynbody#251]
If i install using:

```pip install pynbody```

  ```bash
Could not find a version that satisfies the requirement pynbody (from versions: pynbody-0.2)
Some externally hosted files were ignored as access to them may be unreliable (use --allow-external pynbody to allow).
No matching distribution found for pynbody
```
Adding the ```--allow-external``` flag then allows it to find pynbody-0.2 though I thought the new version is 0.3. 

I then get an issue installing which looks like its error about unbuffered text I/O.

**Comment by apontzen** [comment]
The version on pip is hugely out of date. We are waiting for PR #248 to merge (@rokroskar?) then we should get all this sorted.

As for the need for --allow-external, sadly I don't see this on any of my systems. What python flavour/version are you using?

**Comment by ajclarke90** [comment]
I'm using python 2.7.9 and the Anaconda distribution on Mac osx Yosemite.

**Comment by apontzen** [comment]
Version 0.3 now added to PyPI and seems to install OK on a variety of systems, although it still needs --allow-external for reasons which don't seem soluble. Still, pip spits out a fairly meaningful message and with the correction it then installs fine.
