### ISSUE TITLE
Write Gadget Snapshot

### ISSUE THREAD

**Issue by DCunnama** [pynbody/pynbody#252]
Hi there,

I would like to write out a gadget snapshot in format 2 and am encountering the following error. The original snapshot is in snap format 1 which has no blocknames.

I'd appreciate any advice or assistance?

Kind Regards,
Daniel

```
In [1]: import pynbody 
pynbody : Verbose mode is on

In [2]: snap=pynbody.load('/data/dcunnama/L200_N128/snapshot_050')
pynbody : Loading using backend <class 'pynbody.snapshot.gadget.GadgetSnap'>

In [3]: snap.write(filename='snapshot_050.g2')
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-a0a2c1df65ba> in <module>()
----> 1 snap.write(filename='snapshot_050.g2')

/home/dcunnama/anaconda/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in write(self, fmt, filename, **kwargs)
    943                     'Cannot infer a file format; please provide one (e.g. use obj.write(filename="filename", fmt=pynbody.tipsy.TipsySnap)')
    944 
--> 945             self._write(self, filename, **kwargs)
    946         else:
    947             fmt._write(self, filename, **kwargs)

/home/dcunnama/anaconda/lib/python2.7/site-packages/pynbody/snapshot/gadget.pyc in _write(self, filename)
   1068                         self._files[i].write_header(self.header, ffile)
   1069                 else:
-> 1070                     self._files[0].write_header(self.header, filename)
   1071             else:
   1072                 # Call write_header for every file.

/home/dcunnama/anaconda/lib/python2.7/site-packages/pynbody/snapshot/gadget.pyc in write_header(self, head_in, filename)
    619         head = copy.deepcopy(head_in)
    620         head.npart = np.array(self.header.npart)
--> 621         data = self.write_block_header(b"HEAD", 256)
    622         data += head.serialize()
    623         if filename == None:

/home/dcunnama/anaconda/lib/python2.7/site-packages/pynbody/snapshot/gadget.pyc in write_block_header(self, name, blocksize)
    606                 self.endian + 'I4sII', blkheadsize, name, nextblock, blkheadsize)
    607         # Also write the record size, which we want for all files*/
--> 608         head += self.write_block_footer(name, blocksize)
    609         return head
    610 

UnboundLocalError: local variable 'head' referenced before assignment
```

**Comment by apontzen** [comment]
Thanks for the bug report. I just pushed a possible fix to branch `fix-252` - could you check if it works for you?

You'll need to `git pull; git checkout fix-252; python setup.py install`

**Comment by DCunnama** [comment]
Hi Andrew,

Thanks for getting back to me. That successfully writes a file but if I'm
reading your fix correctly you are not writing block names when writing out
the file so the output is not a functional gadget2 snapshot.

I've converted the gadget1 snapshot to gadget2 and pynbody can read and
write that correctly.

I'm not sure whether you want to go so far as to support gadget1 files? As
I understand it the only way to do so would be to guess the block order and
impose that when writing out.

Kind Regards,
Daniel

**Comment by apontzen** [comment]
Hi Daniel,

I never work with gadget 1 files so I'm not sure but I thought if we just don't write a block name, we'll end up with a functioning gadget 1 file? This would seem to be the right behaviour, rather than to convert to gadget 2 in place? But maybe I misunderstood...

Cheers, Andrew

**Comment by DCunnama** [comment]
Hi Andrew,

I try not to if possible. There is a difference in how the header is
written too, in Gadget 2 there is a header block as you're aware. In
Gadget-1 this does not exist and the header is held in the first block
"HEAD"

Cheers,
Daniel

**Comment by apontzen** [comment]
Hmmn. Well I suppose it is possible to convert to Gadget-2 format by using our default-gadget-1 blocks in the configuration file but I don't have sample files to work on. Have you got a suggested patch?

**Comment by DCunnama** [comment]
Hi Andrew,

I could provide sample files if you really want to do this but I'm not sure
it is really a necessary feature these days.

I had a look your code in attempt to suggest a patch but the current
behaviour appears to be correct, unless the footer is not the same size as
the header?

Cheers,
Daniel

Pynbody:

if self.format2:
            # This is the block header record, which we want for format two
            # files only
            blkheadsize = 4 + 4 * 1
            # 1 int and 4 chars
            nextblock = blocksize + 2 * 4
            # Relative location of next block; the extra 2 uints are for
storing the headers.
            # Write format 2 header header
            head = struct.pack(
                self.endian + 'I4sII', blkheadsize, name, nextblock,
blkheadsize)
        else:
            head = ""
        # Also write the record size, which we want for all files*/
        head += self.write_block_footer(name, blocksize)
        return head

Gadget2:

if(All.SnapFormat == 2)
            {
              blksize = sizeof(int) + 4 * sizeof(char);
              SKIP;
              my_fwrite("HEAD", sizeof(char), 4, fd);
              nextblock = sizeof(header) + 2 * sizeof(int);
              my_fwrite(&nextblock, sizeof(int), 1, fd);
              SKIP;
            }

          blksize = sizeof(header);
          SKIP;
          my_fwrite(&header, sizeof(header), 1, fd);
          SKIP;

**Comment by apontzen** [comment]
I'm actually unclear now what we should be doing! Could you advise what your preferred solution is? If (as I think you are saying in your previous comment?) that this does not need to be fixed, then I will close the issue.

**Comment by DCunnama** [comment]
Hi Andrew,

Yes, I think close the issue.

Kind Regards,
Daniel
