### ISSUE TITLE
Trouble compiling on Mac OS 10.10.3 Yosemite

### ISSUE THREAD

**Issue by stinsong4100** [pynbody/pynbody#253]
I’m trying to install a latest pull of pynbody on my MacBook.  The Mac has 10.10.3 Yosemite.  I updated homebrew and then reinstalled gcc-5.1.  However, it is having troubles with C compiling.  It spits out this type of error for every line (17000 of them) in the ccV50tZi.s file:

/var/folders/rg/zss6mykj26v_x393c80c9nt80000gn/T//ccV5OtZi.s:17144:`__ZStL8__ioinit(%rip)' is not a valid base/index expression

and then says

error: Command "/usr/local/bin/gcc-5 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -UDEBUG -I/Users/stinson/python/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pynbody/sph/smooth.cpp -o build/temp.macosx-10.6-x86_64-2.7/pynbody/sph/smooth.o -ftree-vectorize -fno-omit-frame-pointer -funroll-loops -fprefetch-loop-arrays -fstrict-aliasing -g -DKDT_THREADING" failed with exit status 1

I feel like I should try to delete that file to clean up some register, but when I go look after the install, the file is gone, so it is getting cleaned by itself.

**Comment by apontzen** [comment]
Wow. That seems like a seriously messed up compiler, Greg. Are you sure this applies only to pynbody?

**Comment by apontzen** [comment]
Hi Greg, I am closing this issue as it doesn't seem like a pynbody thing, but let me know if you think otherwise.
