### ISSUE TITLE
Unexpected units behavior

### ISSUE THREAD

**Issue by ibackus** [pynbody/pynbody#255]
Squaring (or raising to a higher, integer exponent) does not give the same result as multiplication:
```python
r = SimArray(0.5, 'au')

r**2
Out[33]: 0.25

r*r
Out[34]: SimArray(0.25, 'au**2')
```

This seems a little counter-intuitive and causes issues.  Doing this:
```python
r = SimArray([1.0], 'au')

r**2
Out[36]: SimArray([ 1.], 'au**2')
```
gives the expected result.

**Comment by apontzen** [comment]
I've attemped a fix and pushed to branch fix-255

Could you confirm if this works for you?

**Comment by ibackus** [comment]
The fix appears to work for me.  I get all the expected behavior:

```python

r = SimArray(0.5, 'au')

r**2
Out[2]: SimArray(0.25, 'au**2')

r*r
Out[3]: SimArray(0.25, 'au**2')

r = SimArray([0.5], 'au')

r**2
Out[5]: SimArray([ 0.25], 'au**2')

```

**Comment by apontzen** [comment]
Thanks - fixed and merged
