### ISSUE TITLE
snapshot/gadgethdf.py loadable_keys

### ISSUE THREAD

**Issue by HongpingDeng** [pynbody/pynbody#256]
Hi, the loadable_keys() function in this file should be changed to it's equivalent in gadget.py. Otherwise it will not do _family_has_loadable_key() check and return all the available keys of all families.

Regards,

**Comment by apontzen** [comment]
Thanks for the report. Could you pull the latest version, which has just had a major update to the HDF handling merged in, and confirm whether the issue you are seeing persists?

If it does persist, please provide a working example of the wrong behaviour as I don't quite understand your description.

**Comment by HongpingDeng** [comment]
Hi,

I have attached tow screen shot about the loadable_key function in pynobody/snapshot/gadget.py and pynobody/snapshot/gadgethdf.py. I thinks the gadgethdf.py should use the same function as the gadget.py file, which checks whether certain keys apply to one family before return them.

Regards,
Hongping

**Comment by rokroskar** [comment]
can you please look at PR #259 -- I think the output is correct now
