### ISSUE TITLE
ramses.py

### ISSUE THREAD

**Issue by perretv** [pynbody/pynbody#263]
Since the modification of ```ramses.py``` (3c9270a635cde4947b6bc52ff7d068c9e6cd14c2), the family ```star``` has no particle when I load one of my ramses simulation. The stars actually end up in the ```dm``` family.
It is due to the fact that I have a special ramses output format with tracer particles with mass=0 and age=0.
These tracer particles are mixed with dm and star particles, i.e. for each particle with a mass, the next particle in the same datablock is a tracer particle with no mass. If I ```git checkout``` the ```ramses.py``` of the previous commit (b836618a8f9caae5bf00df8d3f1ca07defee5348) and recompile pynbody, this problem disappear.

**Comment by apontzen** [comment]
Could you provide a sample file so that I can develop a fix?

**Comment by apontzen** [comment]
I'll probably close this issue shortly as I don't think we can develop a fix without a sample.
