### ISSUE TITLE
Midplane gravity gives inaccurate results in galaxy center

### ISSUE THREAD

**Issue by jakobherpich** [pynbody/pynbody#270]
In the following plot I overplotted the potential (`phi` array) of all particles with |z|<0.1 kpc as a function of radius (black points), a spherically averaged profile of the `phi` array (`prof['phi']`) from the simulation (red line) and the potential from midplane gravity (`prof['pot']`). There is a discrepancy between the midplane gravity method with the spherical mean and the actual data in the plane inside ~ 1 kpc. The gravitational softening is 227 pc.

Why is the midplane gravity calculation not able to reproduce the potential in the inner region? Even a spherically averaged profile is more accurate. Since the gravity calculation uses the softening from the simulation I would assume that it returns the same potential as the simulation software.

![prof_phi_test](https://cloud.githubusercontent.com/assets/5030846/9224525/512f1b02-4103-11e5-88c7-173c51ca4e2a.png)

Here is the code:
```
In [2]: sim = pynbody.load('halo.000818')

In [3]: trans = pynbody.analysis.angmom.faceon(sim.s, vcen=0)

In [4]: plt.figure(figsize=(5, 3.6))
Out[4]: <matplotlib.figure.Figure at 0x44e1e90>

In [5]: prof = pynbody.analysis.profile.Profile(sim, nbins=1000, type='log', ndim=3)

In [6]: plane = sim[np.where(np.abs(sim['z'])<.1)]

In [7]: plt.plot(plane['rxy'], plane['phi'].in_units(prof['pot'].units), 'k.')
pynbody.analysis.profile : Profile pot -- this routine assumes the disk is in the x-y plane
Out[7]: [<matplotlib.lines.Line2D at 0x45f1990>]

In [8]: plt.semilogx(prof['rbins'], prof['phi'], 'r-')
/home/herpich/python/pynbody/analysis/profile.py:418: RuntimeWarning: invalid value encountered in double_scalars
  result[i] = (name_array * mass_array).sum() / self['mass'][i]
Out[8]: [<matplotlib.lines.Line2D at 0x4608150>]

In [9]: plt.semilogx(prof['rbins'], prof['pot'], 'g-')
Out[9]: [<matplotlib.lines.Line2D at 0x461ae50>]
```

**Comment by apontzen** [comment]
Could this be because the softening kernel is wrong? Can you get a better result by rescaling epsilon?

**Comment by trquinn** [comment]
Or perhaps the form of the kernel is mismatched.  It looks like pynbody is using the Dehnen K1 kernel; what's the simulation software using?

**Comment by jakobherpich** [comment]
@apontzen: when I reduce the softening by a factor of 2 the red and green lines become practically identical.

@trquinn: I ran the simulations with ChaNGa. I don't know which kernel it uses but I'm sure you do.

**Comment by apontzen** [comment]
OK, sounds very much like it is just a kernel mismatch then (the functional form, like @trquinn says). In principle it would be nice to be able to select kernels, but if you don't have time to implement that then at least you have a workaround :-)

Perhaps @trquinn can advise further just to be sure this is indeed the underlying problem.

**Comment by trquinn** [comment]
I checked the code again: it looks like pynbody uses analysis/gravity.py to calculate the potential, which uses a Plummer potential.  For the same "eps" this produces a force law that is about a factor of two softer than a spline kernel (which indeed is what ChaNGa uses.)  Hence @jakobherpich results are expected.

**Comment by apontzen** [comment]
OK, @jakobherpich do you plan to implement the alternative kernel or are you just going to live with the workaround? If the latter, I'll close this as 'wontfix' as I am not going to get to it in the near future.
