### ISSUE TITLE
snapshot/gadget.py line 201 bug

### ISSUE THREAD

**Issue by HongpingDeng** [pynbody/pynbody#271]
if (npart < 2 ** 31).all(): this line doesn't work in python 2.7.6. Should be if(all(npart)<2**31): ??

**Comment by apontzen** [comment]
Hmmm, I can't see why the code as implemented wouldn't work. Can you paste an actual failure case?

Your proposed fix seems actively wrong, though all(npart<2**31) would work (less efficiently). Your parenthesis placement would lead to incorrect behaviour.

**Comment by HongpingDeng** [comment]
It says "bool object has no attribute all". I found it is similar to http://stackoverflow.com/questions/21744821/error-bool-object-has-no-attribute-any

I don't know what happened, but if(all(npart)<2**31): works on my PC, Ubuntu 14.04 python 2.7.6

**Comment by apontzen** [comment]
Weird - this doesn't make sense! Could you `print type(npart)` just above that line? It should be np.ndarray, which does not behave in this way.

**Comment by HongpingDeng** [comment]
sorry I didn't initial npart as np.array but as list. :(

**Comment by apontzen** [comment]
OK, that would be the problem then! I'm closing this issue now.
