### ISSUE TITLE
Notebook information

### ISSUE THREAD

**Issue by ajclarke90** [pynbody/pynbody#272]
Hey guys,

A really nice little change (if it's possible) would be being able to suppress the pynbody information that is relayed back to you in notebooks. 

For example when you load a snapshot in a notebook you get the following put back to you:

    INFO:pynbody.snapshot.tipsy:Loading run670DiffHflT.01550
    INFO:pynbody:Loading using backend <class 'pynbody.snapshot.tipsy.TipsySnap'>
    INFO:pynbody.snapshot.tipsy:Loading run670DiffHflT.01550
    INFO:pynbody.analysis.angmom:Finding halo center...

Now with other notebook things, you can usually suppress this feedback by putting a `;` at the end of the command, but this doesn't appear to work for the pynbody routines.

Cheers.

**Comment by rokroskar** [comment]
do you have verbose = True set in your config file?

**Comment by ajclarke90** [comment]
verbose is set as false

**Comment by apontzen** [comment]
I think this is actually a bug. Could you check whether branch `issue-272` fixes it for you?

**Comment by ajclarke90** [comment]
Yeah, those branch changes fix it! Thanks.

**Comment by apontzen** [comment]
Thanks for the report!
