### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by matthew86** [pynbody/pynbody#277]
I'm trying to install pynbody locally, so I used the --prefix flag during the installation and everything seems to run smoothly.
However, when trying to call pynbody I get the following error message

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pynbody/__init__.py", line 21, in <module>
    from . import util, filt, array, family, snapshot
  File "pynbody/util.py", line 27, in <module>
    from ._util import *
ImportError: No module named _util

Do you think you can help me understand what's going wrong?

**Comment by apontzen** [comment]
Are you by any chance launching Python from within the pynbody folder? If so, python may have picked up the wrong copy of the module. Try switching to another folder.

**Comment by matthew86** [comment]
I'm not launching python from there, but this is what I have for my PYTHONPATH

export PYTHONPATH=/home/mtomas/pynbody

Do you think this may be the issue?

**Comment by apontzen** [comment]
Yes, definitely! Get rid of that and try again.

**Comment by matthew86** [comment]
Mmmm, I did that but the problem still persist.
What should I have for my PYTHONPATH?

On Mon, Sep 14, 2015 at 10:59 PM, Andrew Pontzen <notifications@github.com>
wrote:

> Yes, definitely! Get rid of that and try again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pynbody/pynbody/issues/277#issuecomment-140289150>.
>



-- 
Matteo

**Comment by apontzen** [comment]
PYTHONPATH can be empty on a normal installation of python. 

More information here https://docs.python.org/2/install/

**Comment by matthew86** [comment]
I see, but that's what I have now and I still get the same error.

On Tue, Sep 15, 2015 at 10:53 AM, Andrew Pontzen <notifications@github.com>
wrote:

> PYTHONPATH can be empty on a normal installation of python.
>
> More information here https://docs.python.org/2/install/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pynbody/pynbody/issues/277#issuecomment-140481163>.
>



-- 
Matteo

**Comment by apontzen** [comment]
Baffling. Can you post the output from python setup.py install?

**Comment by matthew86** [comment]
I know, right?

So after I do this

python setup.py install --prefix=/home/mtomas/pynbody

I get this

/pfs/sw/python/Python-2.7.8/lib/python2.7/distutils/dist.py:267:
UserWarning: Unknown distribution option: 'install_requires'

  warnings.warn(msg)

running install

running build

running build_py

running build_ext

skipping 'pynbody/gravity/_gravity.c' Cython extension (up-to-date)

skipping 'pynbody/chunk/scan.c' Cython extension (up-to-date)

skipping 'pynbody/sph/_render.c' Cython extension (up-to-date)

skipping 'pynbody/analysis/_com.c' Cython extension (up-to-date)

skipping 'pynbody/bridge/_bridge.c' Cython extension (up-to-date)

skipping 'pynbody/_util.c' Cython extension (up-to-date)

skipping 'pynbody/analysis/_interpolate3d.c' Cython extension (up-to-date)

skipping 'pynbody/openmp/openmp_real.c' Cython extension (up-to-date)

running install_lib

running install_egg_info

Removing
/home/mtomas/pynbody/lib/python2.7/site-packages/pynbody-0.30-py2.7.egg-info

Writing
/home/mtomas/pynbody/lib/python2.7/site-packages/pynbody-0.30-py2.7.egg-info


On Tue, Sep 15, 2015 at 10:58 AM, Andrew Pontzen <notifications@github.com>
wrote:

> Baffling. Can you post the output from python setup.py install?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pynbody/pynbody/issues/277#issuecomment-140482892>.
>



-- 
Matteo

**Comment by matthew86** [comment]
I guess this means that somehow I skipped the installation of a few Cython
extensions. How can this be avoided?

On Tue, Sep 15, 2015 at 11:00 AM, Matteo Tomassetti <m.tomassetti@gmail.com>
wrote:

> I know, right?
>
> So after I do this
>
> python setup.py install --prefix=/home/mtomas/pynbody
>
> I get this
>
> /pfs/sw/python/Python-2.7.8/lib/python2.7/distutils/dist.py:267:
> UserWarning: Unknown distribution option: 'install_requires'
>
>   warnings.warn(msg)
>
> running install
>
> running build
>
> running build_py
>
> running build_ext
>
> skipping 'pynbody/gravity/_gravity.c' Cython extension (up-to-date)
>
> skipping 'pynbody/chunk/scan.c' Cython extension (up-to-date)
>
> skipping 'pynbody/sph/_render.c' Cython extension (up-to-date)
>
> skipping 'pynbody/analysis/_com.c' Cython extension (up-to-date)
>
> skipping 'pynbody/bridge/_bridge.c' Cython extension (up-to-date)
>
> skipping 'pynbody/_util.c' Cython extension (up-to-date)
>
> skipping 'pynbody/analysis/_interpolate3d.c' Cython extension (up-to-date)
>
> skipping 'pynbody/openmp/openmp_real.c' Cython extension (up-to-date)
>
> running install_lib
>
> running install_egg_info
>
> Removing
> /home/mtomas/pynbody/lib/python2.7/site-packages/pynbody-0.30-py2.7.egg-info
>
> Writing
> /home/mtomas/pynbody/lib/python2.7/site-packages/pynbody-0.30-py2.7.egg-info
>
>
> On Tue, Sep 15, 2015 at 10:58 AM, Andrew Pontzen <notifications@github.com
> > wrote:
>
>> Baffling. Can you post the output from python setup.py install?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pynbody/pynbody/issues/277#issuecomment-140482892>.
>>
>
>
>
> --
> Matteo
>



-- 
Matteo

**Comment by apontzen** [comment]
No the cython comments are normal, and not the issue.

The problem seems to be this:

/home/mtomas/pynbody/lib/python2.7/site-packages/pynbody-0.30-py2.7.egg-info

which should be

/lib/python2.7/site-packages/pynbody-0.30-py2.7.egg-info

This seems to be some sort of problem with your python setup, as the path is provided by distutils...

**Comment by rokroskar** [comment]
well he is installing it locally with `--prefix`, hence the different directory structure. 

@matthew86: if you want to keep pynbody in a custom directory, can you try setting your `PYTHONPATH` to `/home/mtomas/pynbody/lib/python2.7/site-packages/`

Also, check that `_util.so` is actually included in the installed pynbody directory in `/home/mtomas/pynbody/lib/python2.7/site-packages/pynbody` -- mine looks like this, for example: 

```
rokstar3:~ rokstar$ cd test/lib/python2.7/site-packages/pynbody
rokstar3:pynbody rokstar$ ls
__init__.py		bridge			filt.py			grafic.pyc		ramses.pyc		transformation.py
__init__.pyc		bridge.py		filt.pyc		gravity			simdict.py		transformation.pyc
_util.so		bridge.pyc		gadget.py		halo.py			simdict.pyc		units.py
analysis		chunk			gadget.pyc		halo.pyc		snapshot		units.pyc
array.py		default_config.ini	gadgethdf.py		nchilada.py		snapshot.py		util.py
array.pyc		derived.py		gadgethdf.pyc		nchilada.pyc		snapshot.pyc		util.pyc
backcompat.py		derived.pyc		genic.py		openmp.so		sph
backcompat.pyc		family.py		genic.pyc		plot			tipsy.py
bc_modules		family.pyc		grafic.py		ramses.py		tipsy.pyc
```

since it seems to compile OK it should be there -- if it isn't, this may be a bug

**Comment by apontzen** [comment]
Hi @matthew86 - did you resolve this issue?
