### ISSUE TITLE
Virial radius definition is wrong

### ISSUE THREAD

**Issue by bwkeller** [pynbody/pynbody#278]
The docstring for pynbody.analysis.halo.virial_radius states that the virial radius is defined as

 "This is here defined by the sphere centerd on cen which contains a mean density of overden * rho_c_0 * (1+z)^3."

The actual code uses not the critical density, rho_c_0, but the mean density, omega_M0*rho_c_0.  Neither is the one true way of calculating the virial radius, but the documentation should match what the code is doing.  We should either remove the sim.properties['omegaM0'] term from the target_rho, or update the docstring to state that we use the mean density rather than critical density.

**Comment by apontzen** [comment]
Whoops. Let's update the docstring so that we don't break people's existing code.

**Comment by apontzen** [comment]
p.s. are you able to do this for us and submit a PR?

**Comment by bwkeller** [comment]
Yep. Will do right now.

**Comment by bwkeller** [comment]
It looks like the docstring is actually correct, but the website documentation is wrong.  You fixed this with the commit 0c1c46f6 last year!

**Comment by apontzen** [comment]
I rebuilt the documentation (actually I thought @rokroskar had an automated script somewhere doing this once a week or something).

Please check it matches your expectations now...
