### ISSUE TITLE
Axes convention?

### ISSUE THREAD

**Issue by skendrew** [pynbody/pynbody#281]
Slightly dumb question: what is the convention for the axes when plotting images? Does it follow the right-hand rule? If the z axis is my line of sight, am I (the observer) at positive or negative z? I can't find the info in the documentation anywhere.

**Comment by apontzen** [comment]
How does it make a difference? Isn't it always symmetric under z -> -z?

**Comment by skendrew** [comment]
Yes I know it's not hugely important but I'd like to interpret where two galaxies are with respect to each other in a high-resolution sim, based on the coordinates.

**Comment by apontzen** [comment]
But I mean it's not just that it's unimportant - as far as I can tell there is actually no answer... you would get the same image either way.
