### ISSUE TITLE
No stars returned for RAMSES

### ISSUE THREAD

**Issue by biernackip** [pynbody/pynbody#282]
I have a problem when trying to access stars from RAMSES. I think the problem lies in checking the age of particles when assigning them to categories. If tform is zero, then it's DM. In other cases it's stars.

I am using the dev version.

**Comment by apontzen** [comment]
That's the expected behaviour isn't it? Could you describe where it's going wrong?

**Comment by biernackip** [comment]
Sorry, I think I wasn't very clear. If I load the simulation output like this:
```python
ds = pynbody.load("/path_tomy_data_set/output_00022")
print len(ds.stars)
```
then I get 0 and I am sure I have stars in that simulation. And the same call to length of ds.dm gives me over a million and in the ICs I have only a million of DM particles.

I hope it's more clear now.

**Comment by apontzen** [comment]
But is there some reason why the `tform` is zero for your stars? Ramses format unfortunately does not specify what are stars and what is DM, so pynbody guesses just by looking at `tform`. You can change the field it looks at in the `config.ini` if that helps?

**Comment by biernackip** [comment]
So `tform` for stars should be greater than zero and for DM it should be 0. How can/should I update the config.ini?

**Comment by apontzen** [comment]
Ok, that should work out of the box then. Could you provide a sample file so that I can debug this?

**Comment by biernackip** [comment]
My working snapshots are rather big (about 2GB), but I will try to produce something smaller (unless you could suggest some hosting service)

**Comment by apontzen** [comment]
One CPU only would be fine (so long as you are sure there are star particles on that CPU!)

Or use wetransfer?

**Comment by biernackip** [comment]
OK, I compressed the output and it's here:
www.ics.uzh.ch/~biernack/output_00022.tar.gz
It has 650 MB, but it's a fully working snapshot.

**Comment by apontzen** [comment]
OK - I tried a patch in branch `issue-282` - could you give it a go and let me know.

FYI I think the problem is that the array is called 'tform' in this ramses output whereas pynbody was expecting it to be called 'age'. I'm not sure which is strictly 'correct'... I've tried making it more robust and just emit a warning if it's not 100% sure what's going on.

**Comment by biernackip** [comment]
I can confirm that it works. I've tested it also on another non-cosmo setup. Thanks a lot!

Well, I guess it should be:
'age' = snapshot_time - 'tform'

**Comment by apontzen** [comment]
Great. Is it OK if I take one CPU out of this file and distribute it with the test suite so I can include a regression test? It would have only 20,000 particles or so out of your simulation.

**Comment by biernackip** [comment]
Of course, no problem. I'm a bit cut out from the Internet at the moment. I would like to get in touch about some other things in pynbody

Sent from my Sony Xperia™ smartphone

---- Andrew Pontzen wrote ----
