### ISSUE TITLE
half-light radius funciton returns units of kpc^2

### ISSUE THREAD

**Issue by adicintio** [pynbody/pynbody#286]
In [62]: pynbody.analysis.luminosity.half_light_r(sim.s)
Out[62]: SimArray(3.7397091027335896, 'kpc**2')

**Comment by apontzen** [comment]
Looks like the error's on line 155 which should probably just be `return test_r` rather than `return test_r * sim.star['r'].units` - @stinsong4100 ?

**Comment by adicintio** [comment]
That's what i think.the actual numerical value seems ok.

**Comment by stinsong4100** [comment]
I fixed the units problem in branch issue-286 (`git checkout issue-286`), but I also reworked the algorithm.  It gives reasonable answers to me.  Can you double check it is giving you the same answers you are getting with your other algorithm, Arianna?

**Comment by adicintio** [comment]
HI Greg, im doing it right now. meantime, do you think it is possible to add other meaninful bands to the calculation of mag/lum?for example, L band (peak at 3.6micron) would be super useful for all those people using Spitzer (like me)

**Comment by stinsong4100** [comment]
I don’t know where that data is, but it would be very helpful if you wanted to add bands to the table.  Just make a pull request when you’re done.

Greg

**Comment by adicintio** [comment]
no idea how to do this, Greg. but i see in http://stev.oapd.inaf.it/cgi-bin/cmd that there is the option to chose different bands..

Choose among the available photometric systems:  2MASS + SPITZER (IRAC+MIPS) + WISE

**Comment by adicintio** [comment]
@stinsong4100  your previous half_light_r algorithm gives very similar results as your new one, so it seems ok. and it also gives similar results to my algorithm computing the half_mass radius in a 2d profile when compared to your half_light radius in k band . so it seems all good.

**Comment by adicintio** [comment]
hi @stinsong4100  the units of half light radius are still wrong
