### ISSUE TITLE
possible error in halo_lum luminosity calculation.

### ISSUE THREAD

**Issue by adicintio** [pynbody/pynbody#287]
when calculating the halo_lum, what is the value 5.8?
shouldn't it be the sun magnitude in some specific band, ergo changing according to the band we select?
in any case 5.8 does not seem to be the sun magnitude in any band..
(i double check the halo_mag function seems to be ok)
thanks!

return np.sum(10.0 ** ((5.8 - sim.star[band + '_mag']) / 2.5))

**Comment by rokroskar** [comment]
Seems like a good time to enforce references for all free floating numbers in the code...

**Comment by apontzen** [comment]
Was written by @stinsong4100 in 2011... hopefully he can remember where it came from. But I agree, it doesn't look quite right.

**Comment by adicintio** [comment]
which means that also the half-light radius function may be wrong, given that is based on halo_lum calculations..

**Comment by apontzen** [comment]
Yes, I agree. Perhaps @stinsong4100 will turn up and explain his thinking...

**Comment by stinsong4100** [comment]
Sorry for the slow response.  I was sick all last week and finally getting over it.  I've been trying to remember if I put in an extra 1 for some reason.  I see now there is no reason to.  I will create a branch to fix this bug that will take Arianna's suggestion of an array of magnitudes from http://www.ucolick.org/~cnaw/sun.html .

**Comment by adicintio** [comment]
great. i think the 5.8 should be the sun magnitude in the selected band, so changing according to the desired Lum band. also, can you double check the half-light radius function?seems similar but not equal to what im computing, so it may contain an error as well.cheers

**Comment by stinsong4100** [comment]
I think this is fixed in branch issue-287.  Do you want to merge in the pull request @apontzen ?

**Comment by apontzen** [comment]
Sure, happy to merge as soon as @adicintio confirms the fix works!  Thanks both.

**Comment by adicintio** [comment]
hi everyone. the fix works. now the luminosity should be correct. can you please confirm that the halo_mag function was already ok since the sun contribution canceled out?

**Comment by stinsong4100** [comment]
halo_mag didn't rely on the solar magnitude at all, so it is OK.
