### ISSUE TITLE
Units on colorbar ... 

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#293]
Since the default unit labels on cbars are "log_10" I'd like to make the values on the color bars something like [1,2,3] as opposed to what they default to: [10^1, 10^2, 10^3] ... Its not that big a deal, but I'm always having to change the label on the cbar (removing "log") since the default values on the cbar scale aren't log.
![index](https://cloud.githubusercontent.com/assets/8357712/11389369/20d70ee6-92fd-11e5-86fa-5ac2a6a8336a.png)

**Comment by apontzen** [comment]
You're right, I'd support that change, please open a pull request
