### ISSUE TITLE
Adding the Ramses RT hydro variables

### ISSUE THREAD

**Issue by biernackip** [pynbody/pynbody#297]
Hi!

Would it be possible to add a possibility to read in the RT hydro variables, i.e. photon fluxes, to pynbody?

**Comment by apontzen** [comment]
You should be able to do this just by editing the configuration files. Take a look at line 155 of `default_config.ini`

If for some reason this doesn't work let me know

**Comment by biernackip** [comment]
I looked at that and it will work for ionisation fractions, but the RT variables are stored in a separate file, i.e. rt_XXXXX.outYYYYY

**Comment by apontzen** [comment]
Oh I see. Is the format documented somewhere?

**Comment by biernackip** [comment]
It is most likely the same as hydro. The header might be a bit different, but that should be easy to check in the code.

**Comment by apontzen** [comment]
Ok, if you can post a sample output I'll give it a shot.

**Comment by biernackip** [comment]
I have made a simple run and the output is at http://www.ics.uzh.ch/~biernack/output_00002.tar <http://www.ics.uzh.ch/~biernack/output_00002.tar> (it’s about 550 MB; sorry, they are kinda big)

**Comment by apontzen** [comment]
Thanks. Having never used ramses-RT can I check I'm interpreting correctly that there are nGroups wavebands, for which it is storing a total energy density as well as momentum fluxes in three directions, so that nRTvar = nGroups * 4. Is that correct?

**Comment by biernackip** [comment]
So from what I see in the source code the quantities stored are: photon density in flux units and photon flux for 3 dimensions and this is done for all groups, thus you are correct (I think).

**Comment by apontzen** [comment]
Right - I made a patch in the `ramses-RT` branch. Have a play and let me know how you get on. 

The variables are called `rad_X_rho` and `rad_X_flux` where `X` is the group number.

**Comment by biernackip** [comment]
Awesome! How can I access the blocks? I tried:
In [28]: data.g.loadable_keys()
Out[28]:
['x',
 'y',
 'z',
 'smooth',
 'rho',
 'vx',
 'vy',
 'vz',
 'p',
 'metal',
 'var7',
 'var8’]

I have rt-blocks in my ~/.pynbodyrc

**Comment by apontzen** [comment]
Just try accessing them, I didn't put them in `loadable_keys` yet but it should work nonetheless.

**Comment by apontzen** [comment]
I pushed a change adding them to `loadable_keys` to remove this confusion

**Comment by biernackip** [comment]
Thanks. That’s easier, I think, if they are accesible through gas keys.
I’m getting:
In [10]: data.g.loadable_keys()
Out[10]:
['x',
 'y',
 'z',
 'smooth',
 'rho',
 'vx',
 'vy',
 'vz',
 'p',
 'metal',
 'var7',
 'var8',
 'rad_%d_rho',
 'rad_%d_flux_x',
 'rad_%d_flux_y',
 'rad_%d_flux_z',
 'rad_%d_rho',
 'rad_%d_flux_x',
 'rad_%d_flux_y',
 'rad_%d_flux_z',
 'rad_%d_rho',
 'rad_%d_flux_x',
 'rad_%d_flux_y',
 'rad_%d_flux_z',
 'rad_%d_rho',
 'rad_%d_flux_x',
 'rad_%d_flux_y',
 'rad_%d_flux_z',
 'rad_%d_rho',
 'rad_%d_flux_x',
 'rad_%d_flux_y',
 'rad_%d_flux_z’]

But if I try to use them e.g. pynbody.plot.sph.image(data.g,qty="rad_%d_rho",width='20 kpc',cmap="Reds_r”)
returns "list index out of range”, same if I subsitute %d by integer.

**Comment by apontzen** [comment]
You are one version out-of-date and are seeing a bug... pull it again!

**Comment by biernackip** [comment]
Oops, sorry! Works fine now! Thanks a lot for all the effort!

**Comment by apontzen** [comment]
No problem. Could I ask a favour in return - could you generate a (much) smaller test file than the one you have supplied, so that I can incorporate it in the test suite?

Either by making a grid that is not much refined, or just by spreading the same run across many CPUs so that we can pick out one CPU only.

This would let me merge it into the master branch confidently.

**Comment by biernackip** [comment]
Sure, no problem. I have spread it over more CPUs (64) and put the file at the same location as previously: www.ics.uzh.ch/~biernack/output_00002.tar <http://www.ics.uzh.ch/~biernack/output_00002.tar> (765 MB)

Thanks a lot again!

**Comment by apontzen** [comment]
OK - last request. Could you pull the latest version on that branch and check that the units of the arrays are as you expect? Otherwise I think it is ready to merge.

**Comment by biernackip** [comment]
For the RT runs it looks fine, but now I am getting this for the non-RT runs: (I made sure that my .pynbodyrc is updated for the hydro-blocks and rt-blocks)
  File "./compute_outflows2.py", line 39, in <module>
    shell = data1.g[pynbody.filt.BandPass('r', r_inner, r_outer)]
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 271, in __getitem__
    return IndexedSubSnap(self, i)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1814, in __init__
    index_array = index_array.where(base)[0]
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/filt.py", line 27, in where
    return np.where(self(sim))
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/filt.py", line 254, in __call__
    min_.in_units(sim[prop].units, **sim.conversion_context()))
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 263, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 354, in _get_array_with_lazy_actions
    self.__load_if_required(name)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 365, in __load_if_required
    self.__load_array_and_perform_postprocessing(name)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 886, in __load_array_and_perform_postprocessing
    self._load_array(array_name, fam)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1932, in _load_array
    self.base._load_array(array_name, self._unifamily)
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/ramses.py", line 732, in _load_array
    elif array_name in self._rt_blocks_3d:
  File "/home/ics/biernack/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 444, in __getattr__
    type(self).__name__, name))
AttributeError: 'RamsesSnap' object has no attribute ‘_rt_blocks_3d'

The code was working before the last update.

**Comment by apontzen** [comment]
Ah, thanks! Strange the unit tests didn't catch that, I'll track it down.
