### ISSUE TITLE
warning when loading gadget file 

### ISSUE THREAD

**Issue by dumasj** [pynbody/pynbody#300]
I get this warning when loading a P-Gadget3 snapshot.

/usr/local/lib/python2.7/site-packages/pynbody/snapshot/gadget.py:363: RuntimeWarning: Encountered a gadget block 'NHE ' which could not be interpreted - is it a strange length or data type (length=200)?
  (name, block.length), RuntimeWarning)

**Comment by apontzen** [comment]
What does this block mean and what would you expect pynbody to do with it?

**Comment by dumasj** [comment]
I was trying to generate a density plot, which I am still able to do despite this warning. I am not sure what the block 'NHE ' is.
