### ISSUE TITLE
Proposal to stop importing plot submodule automatically

### ISSUE THREAD

**Issue by apontzen** [pynbody/pynbody#302]
I'd like to stop the main `pynbody` package from importing the `plot` module. 

This would mean that before plotting, you'd have to explicitly `import pynbody.plot`.

The rationale is that `import pynbody` currently takes a long time importing `pyplot`. Furthermore, depending on matplotlib backend, this can cause a system exit if there is no X display available - which prevents command-line utilities from running.

Not importing submodules is standard practice e.g. in `scipy` and `astropy` to save time and reduce the chance of dependency failure. 

However, I'd be interested to hear if anyone has any objections because obviously this could necessitate changes to existing code (an extra import line). One possibility would be to introduce this in stages; first as a configurable option, making it the default later.

**Comment by stinsong4100** [comment]
Sounds like a fine idea to me.

**Comment by trquinn** [comment]
I also concur.

**Comment by bwkeller** [comment]
Me too!

**Comment by jakobherpich** [comment]
That would be great.
