### ISSUE TITLE
Problem with derived unit, sound speed, with python 3

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#315]
I’m running pynbody under python 3 … loading a RAMSES simsnap as I’ve always done, but now I’m getting a unsupported operand type while trying to acceess the derived type 'cs':

```
s.g['cs’]
/Users/earnric/anaconda/lib/python3.4/site-packages/pynbody/derived.py in cs(self)
    216 def cs(self):
    217     """Sound speed"""
--> 218     return np.sqrt(5.0 * units.k * self['temp'] / self['mu'] / units.m_p)
    219 
    220 

TypeError: unsupported operand type(s) for /: 'float' and 'NamedUnit'
    216 def cs(self):
    217     """Sound speed"""
--> 218     return np.sqrt(5.0 * units.k * self['temp'] / self['mu'] / units.m_p)
    219 
    220 

TypeError: unsupported operand type(s) for /: 'float' and 'NamedUnit'
    219 
    220 

TypeError: unsupported operand type(s) for /: 'float' and 'NamedUnit'

```
This is a confirmed python 3 issue. I have no problem with the derived quantity with python 2.7.

**Comment by apontzen** [comment]
Thanks! There is a fix in branch `issue-315`; could you confirm whether this works for you?

**Comment by earnric** [comment]
Thx. I can test later this afternoon.

**Comment by earnric** [comment]
It checks out-- cs is working under py3.

I think it's ready for merging to master.
