### ISSUE TITLE
Problem with vel image plot

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#318]
I'm trying to do the following -- which is the way I generate metallicity and density plots in my own matplotlib figure:

```
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.xaxis.set_visible(True)
    ax.yaxis.set_visible(True)
    fileOut="img_log_ax_vel-z=%.1lf-%i.pdf"% (z,i)
    titleStr = "v - z = %.1lf" % z
    print (titleStr)
    sph.image(impData.g,qty="vel",width=smallbox,cmap="RdYlBu_r", denoise=True ,av_z=False, 
                      log=True, approximate_fast=False, subplot=ax, qtytitle=r"${\rm log}\, v\, {\rm km/s}$"
                      ); #vmin=0.006, vmax=1.0,
    plt.savefig(fileOut,dpi=fig.dpi,bbox_inches='tight') 
    plt.close(fig)

```

However, I get this error (in each of my threads):

> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/Users/earnric/anaconda/envs/py27/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/Users/earnric/anaconda/envs/py27/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/Users/earnric/anaconda/envs/py27/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 407, in bridge
>     X = fn(*args[1:], **kwargs)
>   File "/Users/earnric/anaconda/envs/py27/lib/python2.7/site-packages/pynbody/sph/__init__.py", line 612, in _render_image
>     smooth_lo, smooth_hi, kernel)
>   File "pynbody/sph/_render.pyx", line 125, in pynbody.sph._render.__pyx_fused_cpdef (pynbody/sph/_render.c:34578)
> TypeError: Function call with ambiguous argument types
>

**Comment by apontzen** [comment]
I can't reproduce this. Can you please post a sample file and exact code?

**Comment by earnric** [comment]
```
import gc
from matplotlib.pylab import *
import matplotlib.pyplot as plt 
import pynbody
import pynbody.plot.sph as sph

pynbody.ramses.multiprocess_num = 12
pynbody.config['number_of_threads'] = 24

rcParams['figure.figsize'] = (12,9)
rcParams['font.size'] = 36

s = pynbody.load('output_00121')  # z=8
print ("Loading {}".format('file...'))
s['pos']
s['pos'] -= 0.5
s.physical_units();

z = 1/s.properties['a']-1
print ("Redshift = {:.0f}".format(z))
boxsizestring = "%.2f" % s.properties['boxsize'].in_units('kpc')
boxsizestring += " kpc"
print (boxsizestring)

gc.collect()

s.g['zsolar']  = s.g['metal'] * 50.0         # Solar units
s.g['pzsolar'] = s.g['pzf'] * 50.0           # Solar units
s.g['zsolarOrig']=s.g['zsolar']

s.g['zsolar'][s.g['zsolar']< 1e-5] = 1e-6
s.g['pzsolar'][s.g['pzsolar']< 1e-5] = 0.0   # Since we are looking at ratio
rx,ry,rz = -121.77, -104.01, -203.10
tic = 0.8
i=0  # 00121, 0

print(rx,ry,rz)

sbox = 40.0 / (1.0 + z) * 0.71 # 40 kpc comoving box
smallbox = str(sbox) + " kpc"
print(smallbox)

impData = s[pynbody.filt.Cuboid(str((rx-sbox/2.0)) + " kpc", str((ry-sbox/2.0)) + " kpc",str((rz-sbox/4.0)) + " kpc",
                                str((rx+sbox/2.0)) + " kpc", str((ry+sbox/2.0)) + " kpc",str((rz+sbox/4.0)) + " kpc")]

rect = [0.15,0.15,0.85,0.9]
coords= [-rx,-ry,-rz] # Translation requires negative of the coord
with pynbody.transformation.translate(impData,coords):
    
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.xaxis.set_visible(True)
    ax.yaxis.set_visible(True)
    fileOut="img_log_ax_vel-z=%.1lf-%i.pdf"% (z,i)
    titleStr = "v - z = %.1lf" % z
    print (titleStr)
    sph.image(impData.g,qty="vel",width=smallbox,cmap="RdYlBu_r", denoise=True ,av_z=False, # units="km s^-1",
                      log=True, approximate_fast=False, subplot=ax, qtytitle=r"${\rm log}\, v\, {\rm km/s}$"
                      ); #vmin=0.006, vmax=1.0,
    plt.savefig(fileOut,dpi=fig.dpi,bbox_inches='tight') 
    plt.close(fig)
```

The dataset is pretty big (59GB), not sure where I could post it.

**Comment by earnric** [comment]
My ramses generates the exta scalar 'pzf' that you see in the code above... I have a .pynbodyrc that accounts for it...

**Comment by earnric** [comment]
FYI -- only happens with 'vel' ... plotting rho, temp, zsolar, etc. all seem to work just fine.

**Comment by apontzen** [comment]
vel is a 3D quantity so cannot be plotted. What happens if you plot `v_x`, `v_y` or `v_z`?

**Comment by earnric** [comment]
oh geez.Apologies Andrew. I thought it would plot mag(vel) for the image plot... The x,y,z work fine. 

I just need to take the mag myself and plot.

**Comment by apontzen** [comment]
Yep! Ok, glad it is sorted. :-)
