### ISSUE TITLE
bug in gadget.py

### ISSUE THREAD

**Issue by reangulo** [pynbody/pynbody#321]
Hi, 

I think there is a bug in gadget.py when the mass block is not present and the simulation
was run in single precision.

around line 375 
            # In the header, mass is a double
            block.partlen = 8
            block.data_type = np.float64
            self.blocks[b'MASS'] = block

The mass block should not always be 64 bits, but it should match the type of ,e.g. 'pos'. Otherwise,
there is problems when constructing the kdTree.

Raul

**Comment by apontzen** [comment]
Thanks Raul, are you able to submit a pull request with a fix for this? I don't have a file to test on.

**Comment by jrs65** [comment]
I was having this same issue trying to look at snapshots with `L-PICOLA`. I've submitted a PR #334 with minimal changes that seem to get it working again.

**Comment by apontzen** [comment]
Ideally if there is a small file we can use to generate a regression test, please let me know @jrs65 or @reangulo

**Comment by jrs65** [comment]
I can probably put together something this afternoon. How small is small? A few MB?

**Comment by jrs65** [comment]
I've put a test file [here](http://www.cita.utoronto.ca/~jrs65/pynbody_test.tar.bz2). It's ~700 KB.

**Comment by apontzen** [comment]
Thanks Richard. I've created a regression test and will pull it into master shortly all being well.
