### ISSUE TITLE
unicode_literals

### ISSUE THREAD

**Issue by reangulo** [pynbody/pynbody#326]
I'm not sure this falls within the bug category, but nevertheless I wanted to report that the numpy array view fails when unicode_literals is imported. e.g.

```
from __future__ import (unicode_literals)
import pynbody
snapshot = pynbody.load("sim_00"')
pos = snapshot.d['pos'].view(np.ndarray)
```

results into

```
pos = snapshot.d['pos'].view(np.ndarray)
  File "/home/CEFCA/rangulo/.local/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 255, in __getitem__
    raise TypeError
TypeError
```

**Comment by apontzen** [comment]
I think this is expected behaviour. Pynbody only expects unicode strings if it's running on python 3. Is there a reason why you need it to behave differently?

**Comment by reangulo** [comment]
No reason. But took me a while to realise what was causing the error. So, I thought to report it here for other people potentially finding the same issue in the future.
