### ISSUE TITLE
UCS2/UCS4 Problem on clean install

### ISSUE THREAD

**Issue by ajclarke90** [pynbody/pynbody#330]
Fresh install of pynbody and anaconda python distro, gives the following error when importing pynbody:

Python 2.7.11, ipython 4.1.2

```
In [1]: import pynbody
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-815e57a3be73> in <module>()
----> 1 import pynbody

/applications/anaconda/lib/python2.7/site-packages/pynbody/__init__.py in <module>()
     19 from .configuration import config, config_parser, logger
     20 
---> 21 from . import util, filt, array, family, snapshot
     22 from .snapshot import tipsy, gadget, gadgethdf, ramses, grafic, nchilada, ascii
     23 from . import analysis, halo, derived, bridge, gravity, sph, transformation

/applications/anaconda/lib/python2.7/site-packages/pynbody/util.py in <module>()
     25 
     26 logger = logging.getLogger('pynbody.util')
---> 27 from ._util import *
     28 
     29 

ImportError: /applications/anaconda/lib/python2.7/site-packages/pynbody/_util.so: undefined symbol: PyUnicodeUCS2_Format
```

**Comment by apontzen** [comment]
Are you sure that's a clean install? Such an error suggests the build was done on a different Python to the one importing the module.

I would double check everything, clone a fresh copy of the repository, make sure there isn't some old Python on your path etc.

See here: http://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm

**Comment by ajclarke90** [comment]
Yeah it should be. I'm running on CentOS 6, so there is the python2 from the OS, but I've appended the anaconda distro to the beginning of the path to test and it's still causing the same bug. I'll keep investigating.

**Comment by rokroskar** [comment]
just to be sure check if PYTHONPATH is defined and if it is, do

$> unset PYTHONPATH

**Comment by ajclarke90** [comment]
Thanks Rok. Thats solved it, I was being dense (as normal!). 

I'd been installing it on an shared filesystem across the network as root, but then I had a local version on my personal account that I was using to test. 

Thanks for the hints.
