### ISSUE TITLE
AHF not automatically invoked

### ISSUE THREAD

**Issue by TobiBu** [pynbody/pynbody#332]
I updated pynbody to the latest version and now I get the following error when trying to load the halo catalogue:

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-c6b82ef9666e> in <module>()
----> 1 h=s.halos()

python2.7/site-packages/pynbody/snapshot/__init__.pyc in halos(self, *args, **kwargs)
    826                 pass
    827
--> 828         raise RuntimeError("No halo catalogue found for %r" % str(self))
    829
    830     ############################################

RuntimeError: No halo catalogue found for '<SimSnap "7.55e11.00616" len=61016846>'

Did I do something wrong when updating or is this a bug?

**Comment by apontzen** [comment]
What do you get if you type `pynbody.halo.AHFCatalogue._run_ahf(s)`? What about for `pynbody.halo.AHFCatalogue._can_run(s)`?

**Comment by TobiBu** [comment]
Hi,

sorry for the delay...

If I type `pynbody.halo.AHFCatalogue._run_ahf(s)` I get the following error message:

`<ipython-input-3-cad132a3812d> in <module>()
----> 1 pb.halo.AHFCatalogue._run_ahf(s)

TypeError: unbound method _run_ahf() must be called with AHFCatalogue instance as first argument (got TipsySnap instance instead)`

If I type: `pynbody.halo.AHFCatalogue._can_run(s)`
I get True

**Comment by apontzen** [comment]
Sorry, that should have been `pynbody.halo.AHFCatalogue(s)._run_ahf()`

**Comment by apontzen** [comment]
Did you get a chance to try the idea above? Would be interesting to see what happens.

**Comment by TobiBu** [comment]
Sorry for the delay...
If I type the above line I get the following:

Traceback (most recent call last):
  File "/home/ad176/bin/doahf.py", line 9, in <module>
    pynbody.halo.AHFCatalogue(s)._run_ahf()
  File "/home/ad176/.local/lib/python2.7/site-packages/pynbody/halo.py", line 826, in __init__
    self._run_ahf(sim)
  File "/home/ad176/.local/lib/python2.7/site-packages/pynbody/halo.py", line 1285, in _run_ahf
    'gridmax': lgmax
TypeError: get() got an unexpected keyword argument 'vars'

**Comment by bwkeller** [comment]
I've figured out the reason for this.  Commit 678bf0c279ca07cd changed config_parser from a ConfigParser instance to a RawConfigParser instance, which does not support vars in the argument to get.

**Comment by apontzen** [comment]
Thanks @bwkeller! Can I twist your arm into finding a workaround...?

**Comment by bwkeller** [comment]
Sure!  I'm going for a bike ride this afternoon, but I'll have a shot at it when I get home.

**Comment by apontzen** [comment]
Ping @bwkeller :-)

**Comment by bwkeller** [comment]
All fixed.  Pull request is in.  Should work with py2 and py3 now.

**Comment by apontzen** [comment]
This is now merged in. Could you confirm this works @TobiBu, before I close this issue?

**Comment by TobiBu** [comment]
Hi,

yes now it works. Thank you!
