### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by rahrah997** [pynbody/pynbody#333]
I would really like to use pynbody but when I download the repository and run the installation process I get an error: AttributeError : 'NoneType' object has no attribute 'split'

It says the error is at line 86 in setup.py.

Any help would be great!

**Comment by apontzen** [comment]
Seems like a problem with your distutils. Perhaps try setting the `CC` environment variable with a path to your C compiler before running `setup.py`?

**Comment by rahrah997** [comment]
I added this to path C:\TDM-GCC-64\bin;, but this did not work

**Comment by apontzen** [comment]
Ah are you installing on Windows? I don't think any of the decelopers use windows so it will be hard to provide any further info. However, it is clear that somehow the CC variable is coming back blank so the setup.py cannot find a C compiler...

**Comment by bwkeller** [comment]
I think to solve this, you will need to install a C compiler like mingw, and possibly modify setup.py.  I don't have any windows machines, so I can't really help much either. :/

**Comment by apontzen** [comment]
I'm afraid I'm going to close this as unfixable in practice. If there are any developers who work with Windows, we can reopen it in future :-)
