### ISSUE TITLE
RAMSES runs are missing cells

### ISSUE THREAD

**Issue by biernackip** [pynbody/pynbody#336]
Hi,

I have been playing with some RAMSES unigrid simulations and found that gas cells are missing. Say for the box with levelmin and levelmax both 7, I should have len(ds.g) to be 2097152 (and I am getting that when loading data with pymses), but pynbody returns instead 1835008.

If I looped through all the possible (x[ii], y[jj]) pairs, where x = np.unique(f.g[‘x’])  and y = np.unique(f.g[‘y’]), and look at the number of cells with these (x, y) coordinates, then this is what I get:

ii even, jj odd : 128
ii even, jj even : 64
ii odd, jj odd : 128
ii odd, jj even : 128

Seems like a bug in the reader to me.

**Comment by apontzen** [comment]
OK, please submit a pull request with the fix! (And provide a sample if possible.)

**Comment by biernackip** [comment]
I wish I knew how to fix it...

**Comment by perretv** [comment]
It seems that the problem concerns all of the ramses outputs.
1/8 of the cells at levelmax are always missing.

**Comment by apontzen** [comment]
I can't reproduce this problem on my outputs. Please post a test file, the unigrid one would be fine.

**Comment by apontzen** [comment]
(Update - no need, seems like @perretv has got a fix)
