### ISSUE TITLE
Updated pynbody to 0.41, positions loaded incorrectly?

### ISSUE THREAD

**Issue by nikTheCosmoGuy** [pynbody/pynbody#339]
Hi, I've updated pynbody from 0.3(?I think) to 0.41. Running the same script before, produced images like so, 
![dm_snapshot_001](https://cloud.githubusercontent.com/assets/9639229/16572912/4f9661aa-42b1-11e6-8986-84589f2bf7fd.png)
![gas_snapshot_001](https://cloud.githubusercontent.com/assets/9639229/16572913/51ff0370-42b1-11e6-873d-b7b818b6ed42.png)

Right after the update it produces images like 

![dm_snapshot_000](https://cloud.githubusercontent.com/assets/9639229/16572929/9edbda60-42b1-11e6-854a-8224aa6e7374.png)
![gas_snapshot_000](https://cloud.githubusercontent.com/assets/9639229/16572930/a0c11520-42b1-11e6-8110-cad35e52af91.png)

The only thing I changed was to update my pynbody using 

`pip install -I --no-deps git+git://github.com/pynbody/pynbody@master `

The script I use to produce these images is

```
import matplotlib as mpl
import pynbody
import pynbody.plot.sph as sph
import matplotlib.pylab as plt
import numpy as np

#Tell us the path 
path = '/media/nik/Disk_drive/Storage/MW5_B0/'
outpath = path #change if you want output elsewhere
basename = 'snapshot_'
#snapshot numbers
firstsnap= 0 #Which snap do you want to begin with?
lastsnap = 0 #if snap shot has numbers, 002, 004, 011 just write 2, 4, 11
#%%
plt.ion()

gas_max = 'None'
gas_min = 'None'
DM_max = 'None'
DM_min = 'None'
u_max = 'None'
u_min = 'None'
box_size =  300
profile_max = 'None'
profile_min = 'None'



print ('Processing snapshots - ' + basename + str(firstsnap) + ' to ' + str(lastsnap))

for snapnumber in range(firstsnap, lastsnap+1):
    plt.clf()    
    num= str(snapnumber).zfill(3)
    print ('Loading snapshot - ' + basename+num)
    s = pynbody.load(path + basename + num)
    print ('Loaded! Making images.')
    #s = pynbody.load('/home/nik/Desktop/depot2/nfw_10_041')
    mass = np.asanyarray(s['mass'], dtype=s['pos'].dtype)
    del s['mass']
    s['mass']=mass
    s.physical_units()

    #Move to the COM frame
    s['pos'] = s['pos'] - pynbody.analysis.halo.center_of_mass(s)    
    
    #Get Redshift as string
    a = s.properties['a']
    z='%.2f' % (1/a -1)
    #extra details to title
    extra = ''
    
    #make figure of gas distribution slice if there is gas present 
    if len(s.g) > 0:
        plt.figure(1)
        #sph.image(s.g,qty="rho",units='Msol kpc^-2', width=box_size,title='Gas Density', vmin=gas_min, vmax=gas_max ,cmap="Greys")
        sph.image(s.g,qty="rho",title='Gas Density',cmap="Greys")
        plt.savefig(outpath+'gas_'+basename+num)
    
    #make figure of dm distribution slice
    plt.figure(2)
    #sph.image(s.dm,qty="rho", units='Msol kpc^-2', width=box_size,title='Dark Matter', vmin=DM_min, vmax=DM_max, cmap="Greys")
    sph.image(s.dm,qty="rho", units='Msol kpc^-2', width=box_size,title='Dark Matter', cmap="Greys")
    plt.savefig(outpath+'dm_'+basename+num)
    
    if len(s.g) > 0:
        #make figure of internal energy per unit mass
        plt.figure(3)
        #sph.image(s.g,qty="u",units='km^2 s^-2', width=box_size,title='Internal Energy', vmin=u_min, vmax=u_max, cmap="YlOrRd")
        sph.image(s.g,qty="u",units='km^2 s^-2', width=box_size,title='Internal Energy', cmap="YlOrRd")
        plt.savefig(outpath+'u_'+basename+num)
        
        
        #GAS
        density_range = np.array([1.0, 10000000.0])
        temp_range = np.array([1.0*10**0, 1.0*10**8])   
        density_range=None
        temp_range= None
        
        plt.figure(4)            
        #pynbody.plot.gas.rho_T(s.g, rho_units=None, rho_range=density_range, t_range=temp_range, colorbar=True, logscale=True)
        pynbody.plot.gas.rho_T(s.g, rho_units=None, colorbar=True, logscale=True)
        plt.savefig(outpath+'rhovsT'+basename+num)
         
    
    plt.figure(5)
    s.dm['rhosq'] = s.dm['rho']*s.dm['rho']/gev_cc_to_solmass_cpc/gev_cc_to_solmass_cpc
    s.dm['A'] = s.dm['rhosq'] * sigmav/(mdm**2)/2
    sph.image(s.dm,qty="A", width=box_size,title='Annihilation', vmin=None, vmax=None ,cmap="YlOrRd")
    plt.savefig(outpath+'anni_'+basename+num)
    #plt.clf()
    
    
    #Create profile
    #ps = pynbody.analysis.profile.Profile(s.dm, type = 'lin', min=profile_min, max=profile_max, ndim=3)
    ps = pynbody.analysis.profile.Profile(s.dm, type = 'lin', ndim=3)
    plt.figure(6)
    plt.clf()
    plt.plot(ps['rbins'], ps['density']);
    ##plt.ylim(10**7, 10**10)
    plt.rc('font', family='serif')
    plt.semilogx();
    plt.semilogy();
    plt.xlabel('$R$ [kpc]');
    plt.ylabel('$\Sigma$ [M$_\odot$/kpc$^3$]');
    
    
    #plt.title('Gas Matter Profile')
    #plt.savefig(outpath+'Gas_Profile_'+basename+num)
    if len(s.g) > 0:
        #ps = pynbody.analysis.profile.Profile(s.g, type = 'lin', min=profile_min, max=profile_max, ndim=3)    
        ps = pynbody.analysis.profile.Profile(s.g, type = 'lin', ndim=3)    
        plt.plot(ps['rbins'], ps['density']);
    ##plt.ylim(10**7, 10**10)
    plt.semilogx();
    plt.semilogy();
    plt.xlabel('$R$ [kpc]');
    plt.ylabel('$\Sigma$ [M$_\odot$/kpc$^3$]');
    plt.title('Matter Profile')
    plt.savefig(outpath+'Profile_'+basename+num)

    
print ('Images saved to '+ outpath)
```
Where the file being loaded is Gadget2 files with comoving integration off. The gadget file is [here](https://www.dropbox.com/sh/d7dkx0edki97byp/AABuHH0kY_NKqTyybWbZhjO7a?dl=0) in dropbox if needed.

The issue seems to be the positions are loaded incorrectly Out[6]: 
```
SimArray([[ -717836.5       , -1680943.625     , -2297263.75      ],
       [ -376015.25      , -1061287.5       , -2797365.        ],
       [-1195774.625     , -1003204.5       , -1843018.5       ],
       ..., 
       [ -127856.9453125 ,   121013.1796875 ,   -35558.09765625],
       [ -144453.703125  ,   150689.5625    ,   -41340.13671875],
       [ -118174.5859375 ,   115669.453125  ,  -102738.1875    ]], dtype=float32, 'kpc')
```
You can see that these numbers a quite large, but the halo should have a scale radius 20 kpc. 

Commenting out s.physical_units(), seems to fix the dark matter image but not the gas image.

I'm not sure if I've missed some changes in the update but if there isn't a quick fix or error on my part, is it possible to temporally revert to an earlier version of pynbody?

**Comment by apontzen** [comment]
I think this is because at some point the default gadget units have been changed. This is probably undesirable and should be reverted, but to test first whether this is in fact the problem underlying your case can you create a `.pynbodyrc` in your home folder with the lines

```
[gadget-units]
pos: kpc a h^-1
mass: 1e10 Msol h^-1
```

and see if this resolves your issue?

**Comment by nikTheCosmoGuy** [comment]
Great, the dark matter image looks right but the gas one is still a bit funky.
![dm_snapshot_000](https://cloud.githubusercontent.com/assets/9639229/16578541/795421f8-42de-11e6-913c-4d6cbb092d9b.png)

![gas_snapshot_000](https://cloud.githubusercontent.com/assets/9639229/16578545/7df3fa26-42de-11e6-8115-5902386b9b6d.png)

By the colour bar, it looks like the gas density is at least in the right ball park

And s['pos'] gives sensible results.

`s['pos']
SimArray([[ -717.83642578, -1680.94360352, -2297.26367188],
       [ -376.01522827, -1061.28747559, -2797.36499023],
       [-1195.77453613, -1003.20440674, -1843.01867676],
       ..., 
       [ -127.85692596,   121.013237  ,   -35.55812073],
       [ -144.45370483,   150.68960571,   -41.34016037],
       [ -118.17456055,   115.66950226,  -102.73820496]], dtype=float32, 'kpc')`

**Comment by apontzen** [comment]
The previous example of gas density was projected (m_p cm^-2) but this one is a slice (m_p cm^-3)... Could this account for the difference?

**Comment by nikTheCosmoGuy** [comment]
Ahh great, the width size was also not the same. Forcing it with 

`sph.image(s.g,qty="rho", units='Msol kpc^-2', width=box_size, title='Gas Density',cmap="Greys")`

Reproduces the same image. 

Cheers Andrew!
