### ISSUE TITLE
ramses-rt hydro blocks

### ISSUE THREAD

**Issue by lnieblar** [pynbody/pynbody#343]
I read over issue #297 and it seems like to get ionization fractions you do something like this in ~/.pynbodyrc

`hydro-blocks=rho,vx,vy,vz,p,metal,xHII,xHeII,xHeIII`

I chose this ordering because I have NVAR=9 and as the [ramses wiki ](https://bitbucket.org/rteyssie/ramses/wiki/RHD) states that means (rho, u, v, w, P, Z, xHII, xHeII, xHeIII) But making plots of these variables for a stromgren sphere run (one radiating source at 100% Hydrogen) gives me counterintuitive results

![metal](https://cloud.githubusercontent.com/assets/14945544/17763620/a642a47a-64ce-11e6-8b7f-cb437cb4b66d.png)

This is a plot of the 'metal' variable, but corresponds to what we would expect for the neutral fraction of Hydrogen. Here is the plot of xHII

![xhii](https://cloud.githubusercontent.com/assets/14945544/17763624/ad72d4fe-64ce-11e6-8842-e1ef45ae592b.png)

Where everything is set to 1e-6, which is the minimum ionization fraction, which is what I think we expect for xHeII or xHeIII. Plotting xHeIII gives a blank plot, so I'm thinking I just remove the 'metal' variable, but is there any way to verify how these things are being translated? Do you know if I am writing the hydro-blocks correctly?

Thanks for any help.

**Comment by biernackip** [comment]
Hi Luis,

I think you are on a right track, but my question would be: do you have metals in your RAMSES run? `metal=.true.` in the namelist. My guess is that you don't, so you should have:
`hydro-blocks=rho,vx,vy,vz,p,xHII,xHeII,xHeIII` (and in fact NVAR=8 is enough for you then)

**Comment by lnieblar** [comment]
You are correct and I apologize for this oversight. Thank you for the help!!
