### ISSUE TITLE
Rotation curve not computed

### ISSUE THREAD

**Issue by mreinacampos** [pynbody/pynbody#358]
Hi all!

I am using PyNbody in Python 2.7 on my Mac and I am having problems to compute the rotation curve of some AREPO snapshots in .hdf5. It seems there is a format mismatch for the variable rs, but that is an internal variable.
My code:
```
import pynbody
import matplotlib.pyplot as plt
%matplotlib inline

path = "./AREPO-test01/output/snapshot_007.hdf5"
data = pynbody.load(path)
data.set_units_system(velocity='km s^-1', mass = '1e10 Msol', distance = '1 kpc')
data.physical_units() # only mass units change

data['eps'] = pynbody.array.SimArray([1], 'pc')

p = pynbody.analysis.profile.Profile(data,min=.01,max=10,type = 'log',ndim = 3)
pm = pynbody.analysis.profile.Profile(data.dm,min=.01,max=10,type = 'log',ndim = 3)
pg = pynbody.analysis.profile.Profile(data.gas,min=.01,max=10,type = 'log',ndim = 3)

plt.figure()
for prof, name in zip([p,pm,pg],['total','dm', 'gas']):
    plt.semilogy(prof['rbins'],prof['v_circ'],label = name)
plt.xlabel(r'$R$ [kpc]')
plt.ylabel('$V_{\rm c}$ [km s$^{-1}$]')
plt.legend()
plt.show()
```

and the output from terminal:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-39-1a830155f863> in <module>()
>      17 plt.figure()
>      18 for prof, name in zip([p,pm,pg],['total','dm', 'gas']):
> ---> 19     plt.semilogy(prof['rbins'],prof['v_circ'],label = name)
>      20 plt.xlabel(r'$R$ [kpc]')
>      21 plt.ylabel('$V_{\rm c}$ [km s$^{-1}$]')
> 
> /Users/mreina/anaconda2/lib/python2.7/site-packages/pynbody/analysis/profile.pyc in __getitem__(self, name)
>     432             return self._properties[name]
>     433         else:
> --> 434             return self._get_profile(name)
>     435 
>     436     def __setitem__(self, name, item):
> 
> /Users/mreina/anaconda2/lib/python2.7/site-packages/pynbody/analysis/profile.pyc in _get_profile(self, name)
>     344         elif x[0] in Profile._profile_registry:
>     345             args = x[1:]
> --> 346             self._profiles[name] = Profile._profile_registry[x[0]](self, *args)
>     347 
>     348             try:
> 
> /Users/mreina/anaconda2/lib/python2.7/site-packages/pynbody/analysis/profile.pyc in v_circ(p, grav_sim)
>     722     start = time.time()
>     723     rc = gravity.midplane_rot_curve(
> --> 724         grav_sim, p['rbins']).in_units(p.sim['vel'].units)
>     725     end = time.time()
>     726     logger.info("Rotation curve calculated in %5.3g s" % (end - start))
> 
> /Users/mreina/anaconda2/lib/python2.7/site-packages/pynbody/gravity/calc.pyc in midplane_rot_curve(f, rxy_points, eps, mode)
>     105         fn = mode
>     106 
> --> 107     pot, accel = fn(f, np.array(rs), eps=np.min(eps))
>     108 
>     109     u_out = (accel.units * f['pos'].units) ** (1, 2)
> 
> pynbody/gravity/_gravity.pyx in pynbody.gravity._gravity.direct (pynbody/gravity/_gravity.c:1989)()
> 
> ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'float'
> > 

Any help will be appreciated! Thanks!

**Comment by apontzen** [comment]
Interesting... the way you are setting the eps values might be the problem?
Try setting f['eps'] to 1.0 perhaps?

At the moment you are probably generating an integer array which could
potentially be the source of the problem.

If this doesn't help could you report what f['pos'].dtype is?

**Comment by mreinacampos** [comment]
Thanks for replying!

I set data['eps'] because it is not in the properties of the snapshot, so I thought I had to manually type it in. If I set data['eps'] = 1.0, I get the same error. So I've checked the type of data['pos'] and it is float32, so it seems to be that what is causing the problem. How can I cast them into the DTYPE_t format?

Thanks again!

**Comment by apontzen** [comment]
OK, I see the problem. The gravity module is assuming that your simulation has double (aka float64 aka DTYPE_t) type. 

I have tried creating a fix in branch `issue-358`. Can you try this out and see if it helps your case?

**Comment by apontzen** [comment]
By the way you will need to make sure your manually-created 'eps' array is also float32, like the rest of your file. This might require you to have something like `data['eps'] = np.ones(len(data),dtype=np.float32)`

**Comment by mreinacampos** [comment]
I have done as you said: used the branch issue-358 and made data['eps'] to be dfloat33, but it is still not working. The given error has changed:

`Buffer dtype mismatch, expected 'float64_t' but got 'float'
`
but it is still appearing at the same place. Ideas?

**Comment by apontzen** [comment]
Does it give you a line number in the .pyx file?

**Comment by mreinacampos** [comment]
This is the output:

```
pynbody/gravity/_gravity.pyx in pynbody.gravity._gravity.direct (pynbody/gravity/_gravity.c:4747)()

ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'
```

**Comment by apontzen** [comment]
Hmm, unfortunately that doesn't give a line number in the .pyx.

Perhaps it would be simplest if you could point to a sample file that reproduces this problem?

**Comment by mreinacampos** [comment]
I have put a sample file here: https://www.dropbox.com/s/n0tme120ac2o43p/sample-data?dl=0
Hope we can manage to find why this happens!

**Comment by apontzen** [comment]
Found the problem and can now generate rotation curves with this file. Please try pulling the `issue-358` branch again and see if it works.

Here is an example session showing the code working:

```python


In [1]: import pynbody

In [2]: f = pynbody.load("/Users/app/Downloads/sample-data")

In [3]: f.set_units_system(velocity='km s^-1', mass = '1e10 Msol', distance = '1 kpc')

In [4]: f.physical_units()

In [6]: import numpy as np

In [7]: f['eps'] = pynbody.array.SimArray([1.0],'pc',dtype=np.float32)

In [9]: p = pynbody.analysis.profile.Profile(f,min=.01,max=10,type = 'log',ndim = 3)

In [10]: p['rbins']
Out[10]: 
SimArray([ 0.0103576 ,  0.01109836,  0.01189211,  0.01274263,  0.01365397,
        0.01463049,  0.01567686,  0.01679805,  0.01799944,  0.01928675,
        0.02066612,  0.02214415,  0.02372788,  0.02542488,  0.02724325,
        0.02919167,  0.03127944,  0.03351653,  0.0359136 ,  0.03848212,
        0.04123433,  0.04418339,  0.04734335,  0.05072931,  0.05435744,
        0.05824505,  0.06241069,  0.06687426,  0.07165706,  0.07678192,
        0.08227331,  0.08815744,  0.0944624 ,  0.10121829,  0.10845735,
        0.11621414,  0.1245257 ,  0.13343169,  0.14297463,  0.15320008,
        0.16415684,  0.17589723,  0.18847727,  0.20195704,  0.21640086,
        0.2318777 ,  0.24846144,  0.26623122,  0.2852719 ,  0.30567434,
        0.32753596,  0.35096111,  0.3760616 ,  0.40295726,  0.43177649,
        0.46265684,  0.49574574,  0.53120113,  0.56919226,  0.6099005 ,
        0.65352016,  0.70025947,  0.75034154,  0.80400544,  0.86150735,
        0.92312176,  0.98914279,  1.05988559,  1.13568788,  1.21691148,
        1.30394415,  1.39720133,  1.49712819,  1.60420176,  1.71893316,
        1.84187006,  1.97359933,  2.11474978,  2.26599522,  2.42805762,
        2.60171062,  2.78778315,  2.98716347,  3.20080332,  3.42972255,
        3.67501393,  3.93784837,  4.21948055,  4.52125487,  4.84461187,
        5.19109515,  5.56235867,  5.9601747 ,  6.38644225,  6.84319616,
        7.3326168 ,  7.85704046,  8.41897053,  9.02108945,  9.6662715 ], 'kpc')


In [14]: p['v_circ']
pynbody.analysis.profile : Profile v_circ -- this routine assumes the disk is in the x-y plane
Out[14]: 
SimArray([  0.04189801,   0.04495077,   0.04804053,   0.05139807,
         0.05502109,   0.05907203,   0.06341501,   0.06801768,
         0.07276557,   0.07819316,   0.08381346,   0.08974831,
         0.0962645 ,   0.10322031,   0.1105962 ,   0.11867671,
         0.12713768,   0.13627036,   0.14590809,   0.15625396,
         0.16744944,   0.17941741,   0.19194683,   0.20544326,
         0.22043233,   0.23617855,   0.25300187,   0.27110598,
         0.29061468,   0.31103526,   0.33319396,   0.35689347,
         0.38238611,   0.40984333,   0.43873107,   0.47002465,
         0.50362904,   0.53937555,   0.5779501 ,   0.61902767,
         0.66286844,   0.70969061,   0.75966439,   0.81301696,
         0.87083519,   0.93220001,   0.99725383,   1.06713971,
         1.14148223,   1.22126579,   1.30526346,   1.39485206,
         1.49128953,   1.59315655,   1.70209316,   1.81771568,
         1.94018368,   2.07057765,   2.20760053,   2.35341343,
         2.50757043,   2.67050151,   2.84344253,   3.02449936,
         3.21475688,   3.41252646,   3.61860277,   3.83095646,
         4.04857932,   4.26895594,   4.49231549,   4.71764191,
         4.9461447 ,   5.17788113,   5.41838024,   5.66863985,
         5.9376111 ,   6.23298049,   6.56157047,   6.93402258,
         7.36360057,   7.86870477,   8.47026294,   9.19055166,
        10.03673069,  10.96706923,  11.9052936 ,  12.80603633,
        13.68668473,  14.58092763,  15.51652935,  16.54612554,
        17.74728705,  19.11616882,  20.63256814,  22.23498763,
        23.45487164,  24.35354416,  25.65412313,  27.44273039], 'km s**-1')
```

**Comment by mreinacampos** [comment]
Perfect, it works now! Thanks!
Maybe I should post this as a different issue, but I can't make images of the snapshots. With the same sample data, if I type:

>     data = pynbody.load("sample-data")
>     data.set_units_system(velocity='km s^-1', mass = '1e10 Msol', distance = '1 kpc')
>     data.physical_units()
>     data['eps'] = pynbody.array.SimArray([1.0],'pc',dtype=numpy.float32)
>     pynbody.analysis.angmom.faceon(data)
>     sph.image(data.gas,qty="rho",units="g cm^-3",width='100 kpc',cmap="Greys")

I get the following error: 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-bdf28d3eb6a6> in <module>()
      6 
      7 pynbody.analysis.angmom.faceon(data)
----> 8 sph.image(data.gas,qty="rho",units="g cm^-3",width='100 kpc',cmap="Greys")

/Users/mreina/anaconda2/lib/python2.7/site-packages/pynbody/plot/sph.pyc in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    422                 im[np.where(im == 0)] = abs(im[np.where(abs(im != 0))]).min()
    423             except ValueError:
--> 424                 raise ValueError, "Failed to make a sensible logarithmic image. This probably means there are no particles in the view."
    425 
    426             # check if there are negative values -- if so, use the symmetric

ValueError: Failed to make a sensible logarithmic image. This probably means there are no particles in the view.
```

But there are enough particles, as I am doing density profiles and I can see it. Any ideas?

**Comment by apontzen** [comment]
I think the smoothing lengths in the file look a bit suspect. Does overriding them using `f.gas['smooth'] = pynbody.sph.smooth(f.gas)` before calculating your image help?

**Comment by mreinacampos** [comment]
Yes, it does! Thanks for the help!

**Comment by apontzen** [comment]
Merged into master
