### ISSUE TITLE
Problem with sfh subplots

### ISSUE THREAD

**Issue by anchwr** [pynbody/pynbody#362]
I'm having a little bit of trouble producing subplots containing star formation histories made with pynbody.plot.stars.sfh. 

I tried a barebones version of the subplot creation:
>>> import pynbody
>>> import matplotlib.pyplot as plt
>>> s = pynbody.load('h986.cosmo50cmb.3072g14HBWK.00512')
>>> h = s.halos()
>>> s.physical_units()
>>> f,axs = plt.subplots(2,2)
>>> pynbody.plot.stars.sfh(h[15],subplot=axs[0,0],bins=100,linestyle='solid',color='k')

which produces the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python2.7/site-packages/pynbody/plot/stars.py", line 291, in sfh
    old_axis = plt.gca()
AttributeError: 'AxesSubplot' object has no attribute 'gca'

A similar error is produced using an alternative method, although 'gca' is replaced by 'clf':
>>> sfhplot = plt.subplot(221)
>>>pynbody.plot.stars.sfh(h[15],subplot=sfhplot,bins=100,linestyle='solid',color='k')

File "/opt/anaconda/lib/python2.7/site-packages/pynbody/plot/stars.py", line 270, in sfh
    plt.clf()
AttributeError: 'AxesSubplot' object has no attribute 'clf'

I know at least the latter method worked as recently as 9 months ago, so perhaps this is due to a recent change? Thanks!

**Comment by apontzen** [comment]
Thanks, I've pushed a fix to branch issue_362; could you confirm this works for you?

**Comment by anchwr** [comment]
It works! I can now make sfh subplots with both methods. Thank you very much!

**Comment by apontzen** [comment]
Merged into master
