### ISSUE TITLE
Calculate density at an arbitrary point?

### ISSUE THREAD

**Issue by nikTheCosmoGuy** [pynbody/pynbody#369]
I have some Gadget2 snapshots and I want to know about the 'dark matter environment' around each of the gas particles.

So I want to use an sph kernal to estimate the dark matter density at the positions of gas particles.

Can Pynbody currently do this? If not I think I should be able to copy and modify the following code- 

@snapshot.SimSnap.stable_derived_quantity`
def rho(self):
    build_tree_or_trees(self)

    logger.info('Calculating SPH density')
    rho = array.SimArray(
        np.empty(len(self['pos'])), self['mass'].units / self['pos'].units ** 3,
        dtype=self['pos'].dtype)

    start = time.time()

    self.kdtree.set_array_ref('smooth',self['smooth'])
    self.kdtree.set_array_ref('mass',self['mass'])
    self.kdtree.set_array_ref('rho',rho)

    self.kdtree.populate('rho', config['sph']['smooth-particles'])

    end = time.time()
    logger.info('Density calculation done in %5.3g s' % (end - start))

    return rho

so that I create a new quantity-
Simsnap.gas['rho_DM']

which gives an estimate of the dark matter density at the gas particle, and likewise a quantity-

Simsnap.gas['smooth_DM']

which is the smoothing length that contains the default number of dark matter nearest neighbors.

Would this be a easy way to get what I want? 

Nik

**Comment by rokroskar** [comment]
I think the easiest might be to temporarily set the mass of the gas particles to zero and run the density calculation on the full snapshot, e.g. `s['rho']`. Just save the mass array somewhere if you need it again later. Alternatively you could append zero-mass DM particles at the positions of the gas particles and calculate the density using `s.d['rho']` but that seems messier.

**Comment by nikTheCosmoGuy** [comment]
Thanks for rokroskar!

So running 

`s['mass']`
`s.g['mass']=0*s.g['mass']`
`s['rho']`

Where now I assume 
`s.g['rho']`
will be populated with dark matter densities measured at Gas particles? And 
`s.dm['rho']` 

is the usual dark matter density.

I'm not sure if I understood this method exactly, but wouldn't this way underestimate the dark matter density since now when it neighbor searches some of it's N neighbors are pseudo-particles with zero mass?

Nik

**Comment by rokroskar** [comment]
yes, you're correct -- however, if I remember correctly, particles with zero mass are ignored, i.e. are treated as test particles, though I can't seem to find this in the code at the moment.

**Comment by elehcim** [comment]
Hello, I'd like to do a similar thing. I'd like to compute the gas density at certain positions. I thought of following the suggestion of appending to the gas family some particles with zero mass but as positions (`'pos'`) the locations of which I'd like to get the density (btw, is it still a viable and the easiest option?).

However the `rho` array for the gas family is stored into the gadget file I'm using and pynbody is reading it.
Is there a way to ignore it and let pynbody recompute it using its kdtree?
I tried with `del snap.g['rho']`, but `snap.g['rho']` is still there after it.
Cheers and thank you,
Michele

**Comment by elehcim** [comment]
For future reference, I managed to do like this:

note: `snap.s['pos']` contains the positions in which I'd like to compute the density.

```
snap = pynbody.load('my.snap')
n_gas = len(snap.g)
n_star = len(snap.s)
new_snap = pynbody.snapshot.new(gas=n_gas+n_star)
new_snap.g['pos'][:n_gas] = snap.g['pos']
new_snap.g['pos'][n_gas:] = snap.s['pos']
new_snap.g['mass'][:n_gas] = snap.g['mass']

desired_rho = new_snap.g['rho'][:n_gas]
```

Let me know if you see any issues.
