### ISSUE TITLE
Wrong bin range in Fourier analysis of disk profiles

### ISSUE THREAD

**Issue by jakobherpich** [pynbody/pynbody#375]
In the `pynbody.analysis.profile.Profile` the fourier modes are calculated using binned values for particles azimuth angles. These are calculated with the `np.arctan2` function which maps to the interval [-pi, pi] but the range for the bins used in the code is [0, 2*pi] so half of the disk is not considered for the analysis. I actually do not understand at all, why this gives any reasonable result at all. The lines of code in question are from the file `pynbody/analysis/profile.py`:

```
 620             phi = np.arctan2(
 621                 self.sim['y'][self.binind[i]], self.sim['x'][self.binind[i]])
 622             mass = self.sim['mass'][self.binind[i]]
 623 
 624             x1 = self.sim['x'][self.binind[i]] + self.sim['vx'][self.binind[i]] * delta_t
 625             y1 = self.sim['y'][self.binind[i]] + self.sim['vy'][self.binind[i]] * delta_t
 626             phi1 = np.arctan2(y1,x1) 
 627 
 628             hist, _ = np.histogram(phi, weights=mass, bins=phi_bins, range=(0, 2.*math.pi))
 629             hist1, _ = np.histogram(phi1, weights=mass, bins=phi_bins, range=(0, 2.*math.pi))
 630             binphi = np.linspace(0, 2*math.pi, phi_bins)
 631             for m in range(7):
 632                 f['c'][m, i] = np.sum(hist * np.exp(-1j * m * binphi))
 633                 f['c_delta'][m, i] = np.sum(hist1 * np.exp(-1j * m * binphi))
```

There are two ways to fix this:

1. Adjust the binning range of the histograms to be [-pi, pi].

2. Do the calculation without binning. I chose this option and will create a pull request right now.

**Comment by apontzen** [comment]
@rokroskar could you comment on this and the associated PR? I never used this code so want to double check you agree before I merge the PR :-)

**Comment by jakobherpich** [comment]
The calculation of `binphi` in line 630 is also wrong. These are not the bin centers.

I will implement this option in a new PR as discussed in PR  #376 

> 1. Adjust the binning range of the histograms to be [-pi, pi].

along with a fix to the calculation of `binphi`.
