### ISSUE TITLE
Misaligned flow lines?

### ISSUE THREAD

**Issue by ibackus** [pynbody/pynbody#380]
I'm rendering a velocity image, and it appears the flow lines may be misaligned with the image.  I say this because the there is a gap between the flow lines and the right edge of the image (see the plot below) and because they don't appear to be centered on the disk.

I'm using a fairly recent pull of pynbody and matplotlib 2.0.

### Image
This is a side-on slice of a protoplanetary disk with 10^8 particles.
![flowlines](https://user-images.githubusercontent.com/6054037/26956331-aa6b92ba-4c71-11e7-8b87-579dd828f80d.png)

**Comment by apontzen** [comment]
Many thanks - could you try the fix in branch `issue-380` and confirm whether this fixes the issue for you?

**Comment by ibackus** [comment]
`issue-380` fixes the issue for me.  Here are two plots that confirm this:

### `master` branch
![vel-image-master](https://user-images.githubusercontent.com/6054037/27239261-07faeb38-5285-11e7-95bb-8362fb929510.png)

### fix branch
![vel-image-issue-380](https://user-images.githubusercontent.com/6054037/27239262-07fcd3da-5285-11e7-9051-92b8b49d2ec0.png)

**Comment by apontzen** [comment]
Thanks for the report and confirmation. Fix merged into master.
