### ISSUE TITLE
question regarding subfind/fof format

### ISSUE THREAD

**Issue by lbignone** [pynbody/pynbody#391]
I seem to have subfind/fof output that does not match the expected format assumed by pynbody. ¿Is there a way to add a custom subfind/fof reader in a plugin-like approach? Perhaps subclassing.
Thanks

**Comment by apontzen** [comment]
Yep, you can subclass `pynbody.halo.HaloCatalogue` to achieve this! For an example, fairly minimal implementation see the `GrpCatalogue`, line 1466 onwards of `halo.py`.
