### ISSUE TITLE
Potential issue with pynbody.plot.image

### ISSUE THREAD

**Issue by Morkney** [pynbody/pynbody#441]
Hello,

I am trying to plot some pynbody images for a DM-only Ramses run. I am using the pynbody.plot.image() function on a centred halo, and have encountered the following error:

`ValueError: The particles span a region larger than the specified boxsize`

In Python's traceback the last call was in pynbody/sph/kdtree.pyc, but I can't find any reference to the value error there or anywhere else.

I have tried increasing the 'width' argument, and the halo particles themselves don't seem out of the ordinary, but nothing has resolved the issue so far. This is the first time I have generated this error despite having used the same function on other simulations.

Update: 
I seem to have bypassed the error by centring the entire pynbody load rather than the individual pynbody halo. By shifting only the pynbody halo I must have been putting particles outside of the predefined simulation box. Since this would depend on the individual halo location, it makes sense that I might not have encountered it before.

**Comment by biernackip** [comment]
I think what was helping this kind of error was to set `boxsize` manually via `ds.properties['boxsize']`

**Comment by Morkney** [comment]
Update 2:
I have found some halos where I encounter the error despite centring the entire pynbody load. Curiously this error only occurs on some halos.

**Comment by LizardM4** [comment]
I believe that this issue is in fact the same as #714; for which this workaround should apply: https://github.com/pynbody/pynbody/issues/714#issuecomment-1686024959.

**Comment by apontzen** [comment]
This is now addressed in #798
