### ISSUE TITLE
Units when writing tipsy files

### ISSUE THREAD

**Issue by tigikay** [pynbody/pynbody#443]
I'm getting this error when trying to save an updated snapshot. One of my key issues is that there is easy way to search through pynbody for a manual on saving/creating new snapshots.

My current task is loading a tipsy snapshot, editing it according to the starlog, calculating some values and then putting them into the original snapshot. I do that like so

f.s['value1']=value1
f.s['value2']=value2
f.s['value3']=value3

After that I check if it's correct and f.s['value1'] is a SimArray with the right units, but as soon as I try

run.write(fmt=pynbody.tipsy.TipsySnap, filename='run752.updoot')

I get this error

```
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pynbody-0.43-py3.4-macosx-10.6-intel.egg/pynbody/simdict.py:92: RuntimeWarning: Assuming default value for property 'a'=1.00e+00
  name, value), RuntimeWarning)
```

Is there any easy way to save a snapshot? Do I need to create an empty snapshot and fill it with the needed values? I did that as well and got the same errors.

If I could export the edited snapshot without creating a new one it would be ideal as I don't want to waste time filling a new snapshot with all the values.

**Comment by apontzen** [comment]
Hi @tigikay, I'm not quite following the problem. The thing that you quote is not an error, it is a warning saying that it is assuming a default value for the cosmological scalefactor. This may or may not be a problem depending on the context.

On the other question you ask: if you are using tipsy files, as you appear to be doing, you can should be able to save individual arrays using `f['value1'].write()`.

**Comment by tigikay** [comment]
Hello @apontzen thank you for the quick response!

I thought that 'a'=1.00e+00 name, value was a generalisation of any value in my snapshot, not a specific value, i.e. cosm. scale factor? 

I'm sorry for not also including this error, but my post here was influenced by this error:

I have a black hole in my simulation and it usually messes with my statistics, so as to remove it (it's the first value in my snapshot) I just reassign the values like so:

`run.s=run.s[1:]`

The problem is that when I save everything and load the new snapshot - the run.s['mass'] is all wrong with gigantic masses, the masses are all 2.36e4 times larger than the originals. The only warning I've received thus far is the "RuntimeWarning: Assuming default value for property 'a'=1.00e+00 name, value) " I referenced in the title of this post, so I had assumed it was the culprit.

Could my method of removing the black hole (on average 57225 times more massive than the star particles in the sim) be causing this error?

**Comment by apontzen** [comment]
Are you perhaps saving in physical_units but then reloading and re-converting to physical_units?

Tipsy files do not contain unit information so pynbody has to guess, and it can't be 100% accurate. If you are saving stuff out it can help to either keep things in the original units or cast back to the original units using `original_units` before saving.

**Comment by tigikay** [comment]
Hmm, I didn't know that tipsy doesn't contain unit information, that might be the issue: when I first load the snapshot before editing it I preform `run.physical_units();`

What is the best course of action? Not loading or saving in physical units?

**Comment by tigikay** [comment]
Also, what are the meta files being created along side the snapshot? Do they contain anything?

**Comment by apontzen** [comment]
The meta files contain auxiliary information, but only for the individual custom arrays you create, not for the main tipsy file.  

The solution is to not call `physical_units` if you know you will be saving the file. Or, alternatively, call `original_units` right before you save.

**Comment by tigikay** [comment]
Calling `original_units`, but not still not calling `physical_units` after first loading?

I might be slow in responding as I'm currently testing it out.

**Comment by apontzen** [comment]
Your workflow can look like this:

```
f = pynbody.load(...)
f.physical_units()

... do stuff in physical units ...

f.original_units()
f.write()
```

or like this:

```
f = pynbody.load(...)

... do stuff in file units ...

f.write()
```

Either should work.

**Comment by tigikay** [comment]
Okay, thank you, will test it out.

Also, is my method removing star particles okay, or could it cause problems in pynbody?

**Comment by apontzen** [comment]
Should be fine as far as I can tell!

**Comment by tigikay** [comment]
x
