### ISSUE TITLE
Gass temperatures are 0.0 k

### ISSUE THREAD

**Issue by Morkney** [pynbody/pynbody#452]
Hello,

I was trying to look at the gas temperatures for a simulation when I discovered that the entire array was listed as zeroes. I assume this is an issue within Pynbody because otherwise an error should have occurred before now:

```
In [1]: s = pynbody.load('/path/to/simulation/output_00101')
In [2]: s.g['temp']
Out[3]: SimArray([0., 0., 0., ..., 0., 0., 0.], 'K')
```

Is there anything I can do about this?

Thanks and all the best, -Matt

**Comment by Morkney** [comment]
'rho' looks fine, however 'u', 'p' and 'cs' are all zero arrays too. It seems as though any derived quantity which involves 'temp' is zero.

The following code concerns me:

```
@SimSnap.derived_quantity
def u(self):
    """Gas internal energy derived from temperature"""
    gamma = 5. / 3
    return self['temp'] * units.k / (self['mu'] * units.m_p * (gamma - 1))


@SimSnap.derived_quantity
def temp(self):
    """Gas temperature derived from internal energy"""
    gamma = 5. / 3
    mu_est = np.ones(len(self))
    for i in range(5):
        temp = (self['u'] * units.m_p / units.k) * (mu_est * (gamma - 1))
        temp.convert_units("K")
        mu_est = mu(self, temp)
    return temp
```

How is it that the definition of 'temp' relies on 'u', and the definition of 'u' relies on 'temp'?

**Comment by apontzen** [comment]
That code is only called if an array is missing so the assumption is that only one of temp and u is missing. If this were not true you’d get a circular dependency exception so this is not related to the zeros you are seeing.

**Comment by Martin-Rey** [comment]
The 'p' array being zero is unusual. It should be one of the array that is read from disk. Is it possible that your ramses <--> pynbody configuration is inconsistent ? 

I am thinking that maybe you have more hydro blocks (or they have different bit lengths) than pynbody expects. In this case you need to edit the hydro blocks line of your config file:
https://github.com/pynbody/pynbody/blob/aa925aa25989d74c2a3c512f1fe2858a6798f080/pynbody/default_config.ini#L167-L193

You can check this by seeing if the velocities and metal are also zeroes.

**Comment by Morkney** [comment]
It looks like the RAMSES outputs have been swapped around due to a RT-solver, but the correct data should still be retrievable. Since this problem is no fault of Pynbody I will close this issue.
