### ISSUE TITLE
physical_units issue

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#465]
I'm using 0.45 and I'm having a problem with physical_units with ramses data.

When I load a snap, I get reasonable positions of the gas cells:

> s['pos'] -= 0.5
> s.g['pos']
> SimArray([[-4.18952330e-05, -4.45321624e-05, -4.28767818e-05],
>           [-4.17918056e-05, -4.45402793e-05, -4.28309930e-05],
>           [-4.18312073e-05, -4.45206413e-05, -4.28440085e-05],
>           ...,
>           [-1.14249478e+02, -1.54999770e+02, -1.50452527e+02],
>           [-1.14424372e+02, -1.54999770e+02, -1.50802315e+02],
>           [-1.14074584e+02, -1.54999770e+02, -1.50802315e+02]], '1.38e+23 cm')

But after doing a

>  s.physical_units()

 things go wonky. The snap is 300 kpc/h comoving... and once I do the conversion s.g['pos'] looks like:

> SimArray([[-3.37484041e+05, -3.58725636e+05, -3.45390836e+05],
>           [-3.36650889e+05, -3.58791021e+05, -3.45021988e+05],
>           [-3.36968286e+05, -3.58632829e+05, -3.45126834e+05],
>           ...,
>           [-1.84489816e+15, -2.50293302e+15, -2.42950424e+15],
>           [-1.84772235e+15, -2.50293302e+15, -2.43515261e+15],
>           [-1.84207398e+15, -2.50293302e+15, -2.43515261e+15]], 'kpc')

Note that I have added extra scalars to ramses, and they are modeled in the pynbodyrc file:

> particle-blocks=x,y,z,vx,vy,vz,mass,iord,level,age,metal,rpart,mtime,ppf,pzf
> particle-format=f8,f8,f8,f8,f8,f8,f8,i4,i4,f8,f8,f8,f8,f8,f8
> 
> particle-distinguisher=9,f8 
> 
> hydro-blocks=rho,vx,vy,vz,p,metal,pgf,tv,pzf,rpgas,trknsbs
> hydro-format=f8,f8,f8,f8,f8,f8,f8,f8,f8,f8,f8
> gravity-blocks=phi,accg_x,accg_y,accg_z
> 

However, once converting to physical units I cannot plot anything ... I get the 'no particles in view' error.

Any ideas? I can upload the ramses snap if you like...

**Comment by earnric** [comment]
So this seems to be some kind of configuration issue. I'm running into this problem on a mac pro desktop, using gcc 5.5 and not at my 'home' mac pro (same era machine) running gcc 5.5 -- both homebrew.

It's weird that I'm not getting an error or a crash -- but just an incorrect conversion in the physical_units() routine. The dimensions seem ok before the conversion, but after (as noted above) the call they go wonky.

Has anyone else seen this? I'm checking all my libraries now... but I don't see anything out of the ordinary so far.

**Comment by apontzen** [comment]
Are you by any chance using anaconda python? Recently there seem to have
been pretty disasterous bugs in their numpy/mkl routines.

**Comment by earnric** [comment]
I am using anaconda python ... on both machines tho. 

I'll try reverting numpy and mkl to previous versions... maybe that'll help. 

Weird that it works fine on one, but not the other.

**Comment by earnric** [comment]
So I reinstalled anaconda python (yea, I know, but wanted to see why it works on one and not the other machine) on my work Mac ... cleaned everything, then reinstalled the same versions I have on my home machine (that is working fine)... still results in 'bogus math' when I do the 

s.g['pos'] -= 0.5 

which points to numpy. I will try with another install this weekend. Crazy type of issue!!

**Comment by apontzen** [comment]
Yes I have not been able to pinpoint what triggers these weird bugs either, so haven't made a report to anaconda as of yet. It does sound like this could be the issue you are running into. Try downgrading numpy + mkl conda packages?

**Comment by earnric** [comment]
Reverting to numpy v 1.12 via conda fixes the issue... Lesson learned: don't use numpy 1.14 with conda and pynbody. At least not on a mac running El Cap 10.11.6
