### ISSUE TITLE
python 3 compatibility?

### ISSUE THREAD

**Issue by rokroskar** [pynbody/pynbody#468]
Is pynbody python3 compatible? I've just spent a not insignificant amount of time trying to use pynbody with python 3.6 and still not quite there yet... before I invest any more time, should I be looking somewhere else for a python3 version?

**Comment by apontzen** [comment]
It should be - what is the problem you are encountering?

**Comment by rokroskar** [comment]
There were a lot of syntax errors on import with things like

```
raise ValueError, "bad value"
```

etc. Seems like those don't get hit by any tests and for whatever reason the interpreter I'm using was checking the syntax on import. 

I can import now but there are other issues like:

```
In [4]: pynbody.tipsy.TipsySnap('/Users/rok/Projects/isolated-disks/data/12M_hr/12M_hr.01000')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-5539447fa93c> in <module>()
----> 1 pynbody.tipsy.TipsySnap('/Users/rok/Projects/isolated-disks/data/12M_hr/12M_hr.01000')

~/Projects/pynbody/pynbody/snapshot/tipsy.py in __init__(self, filename, **kwargs)
     93                                   family.star: slice(nd + ng, ng + nd + ns)})
     94
---> 95         self._load_control = chunk.LoadControl(disk_family_slice, 10240, take)
     96
     97         self._family_slice = self._load_control.mem_family_slice

~/Projects/pynbody/pynbody/chunk/__init__.py in __init__(self, family_slice, max_chunk, clauses)
    160
    161         self._disk_family_slice = family_slice
--> 162         self._generate_family_order()
    163
    164         # generate simulation-level ID list

~/Projects/pynbody/pynbody/chunk/__init__.py in _generate_family_order(self)
    198     def _generate_family_order(self):
    199         famlist = []
--> 200         for fam, sl in self._disk_family_slice.iteritems():
    201             famlist.append((fam, sl.start, sl.stop))
    202

AttributeError: 'dict' object has no attribute 'iteritems'
```

I thought the tests are running with python 3.6 on travis so I'm really confused how they can pass. Loading a tipsy file is a part of the tests afaik.

**Comment by apontzen** [comment]
Something is going wrong with your installation - 2to3 should be run automatically when installing on python 3.

The path to deprecating python 2 would be to make the code base cross-compatible with six, negating the need for 2to3, as we did for [tangos](http://github.com/pynbody/tangos) - but this is a big undertaking.

**Comment by rokroskar** [comment]
What's making 2to3 run automatically when installing with python3?

**Comment by apontzen** [comment]
Line 159 of `setup.py`

**Comment by rokroskar** [comment]
I see, well that would explain it -- clearly this won't work if you try to install in editable mode!
