### ISSUE TITLE
AHF not invoked 

### ISSUE THREAD

**Issue by ChJazhiel** [pynbody/pynbody#470]
Hi, I'm having this issue addressed by previous post, like:

RuntimeError: No halo catalogue found for '<SimSnap "/home/ahf-v1.0-094/bin/Cluster_Ga1/Ga1_008" len=512000>'

I tried renaming the halo catalogue list but I get the exact same error and when invoking

h = pynbody.halo.AHFCatalogue(s)

I get

Path to AHF (None) is invalid

sorry if I'm missing something here I just want to learn how to use pynbody.

Thanks

**Comment by apontzen** [comment]
Pynbody can’t find your AHF output. What files are actually in that folder?

**Comment by ChJazhiel** [comment]
Hi, files are .AHF_halos, .AHF_particles .AHF_profiles, .AHF_substructure.

Maybe there's something I'm missing?

Thanks

**Comment by apontzen** [comment]
Please list all files in the folder with their exact filenames - I can't tell just from the extensions whether pynbody should be picking it up or not

**Comment by ChJazhiel** [comment]
Cluster_Ga1_008.z0.000.AHF_halos

Cluster_Ga1_008.z0.000.AHF_particles

Cluster_Ga1_008.z0.000.AHF_profiles

Cluster_Ga1_008.z0.000.AHF_substructure

Cluster_Ga1_008.log

Cluster_Ga1_008.parameter

**Comment by apontzen** [comment]
Is the simulation output not in the folder? I am trying to understand the full directory structure and naming conventions here.

**Comment by ChJazhiel** [comment]
Yes, output is actually in the folder

**Comment by apontzen** [comment]
OK, and called Cluster_Ga1_008?

Can you confirm it really is a z=0.000 output too?

**Comment by ChJazhiel** [comment]
I can't post pictures but I'm using gadgetviewer and Redshift reads 0.000

Yes, output is called Cluster_Ga1_008, I'm using gadget simulations

**Comment by apontzen** [comment]
Hmm, very puzzling. Are you able to upload your files somewhere so I can
reproduce the problem?

**Comment by ChJazhiel** [comment]
Thank you that'd be great, I can't upload right now due to the fact I don't have Internet (using my phone to answer) 

As soon as I Can use my laptop I'll upload the folder to my gdrive and post a link here

**Comment by ChJazhiel** [comment]
sorry for the long wait, just arrived home, here's the link to gdrive folder

https://drive.google.com/open?id=1rjrfIE3RRytfbr6P_GqjBHWJflMPLSJW


Any comment would be helpful.

**Comment by apontzen** [comment]
The problem is the inconsistency in your naming. The output is called Ga1_008, so if I rename it to Cluster_Ga1_008 (as you said it was called) everything works fine. Alternatively you could rename the AHF files to Ga1_008.z0.000.AHF_halos etc.

**Comment by ChJazhiel** [comment]
thank you, that  worked.... i'm running into another issue here, when I want to center on the most massive halo i get 
Insufficient particles around center to get velocity
AHF says that this halo has 38542 particles. Do I need to use more particles or is there another way to do this? 
Sorry if I bother you.
