### ISSUE TITLE
the derived calculation for "mu" is inconsistent

### ISSUE THREAD

**Issue by mtremmel** [pynbody/pynbody#477]
The current calculation for "mu" in derived.py states in the documentation (correctly) that the result is the number of particles per hydrogen mass. However, in the case when it cannot find information on H/He ionization states it defaults to default values of 0.59 (for temp > 1e4 K) or 1.3 (for temp < 1.4 K), with the idea that these values are approximately valid for fully ionized and neutral H/He gas respectively. This is true, but these default values are for the inverse of the value that is normally calculated by this function (i.e. the average mass per particle in units of the hydrogen mass).

**Comment by apontzen** [comment]
Whoops, please send a patch :-)

**Comment by apontzen** [comment]
I think this is now fixed - please reopen if not!
