### ISSUE TITLE
change config.ini file for gadget output

### ISSUE THREAD

**Issue by isantossantos** [pynbody/pynbody#479]
Hello,
I am trying to change the config.ini file so that I can read a gadget3 output. The order of the blocks in the simulation I am trying to read is:
HEAD,POS, VEL, ID, MASS, U   , AGE , Z   , RHO, NE, NH, HSML, SFR 
Therefore I have changed the following fields:

[gadget-name-mapping]
HSML: smooth
ID: iord
Z: metals
(here I have just added metals to what was already in the default_config.ini)

[gadget-1-blocks]
blocks=HEAD,POS,VEL,ID,MASS,U,AGE,Z,RHO,NE,NH,HSML,SFR

[gadget-default-output]
all= pos, vel, mass, age, metals
gas= u, rho, ne, nh, smooth, sfr
field-ordering = pos, vel, iord, mass, u , age, metals, rho, ne, nh, smooth, sfr
(I am not sure of what should go in the 'all' or only in the 'gas' sections)

With these changes I am able to get the metals of gas, but not of stars. Also, I am not able to get the tform (or age) of stars. I cannot therefore calculate the magnitude of the halo in any band because it cannot access 'tform'. Do I have to do some conversion between AGE provided by the sim and tform, which is what pynbody wants ?
The rest of stuff I think I can load correctly, so the problem is basically with AGE and Z.

If someone can help with this it would be great. thank you

**Comment by isantossantos** [comment]
I have added a line here:
[gadget-name-mapping]
HSML: smooth
ID: iord
Z: metals
**AGE: aform**

because AGE is the expansion factor at the time the star forms. However, writing: 
sim.s['aform']
gives KeyError: 'No array tform for family star'
because it is trying to calculate 'aform' from tform instead of reading it. I think there is no place where pynbody derives tform from aform, which would be needed in the case of gadget outputs.

**Comment by isantossantos** [comment]
Hi Andrew, thanks. I actually should be using the latest version, since i updated it from the master branch yesterday. I couldn't find any aform->tform transformation. did you add it yesterday?

And yes, I can see the masses and positions correctly. this is what it is reading:
In [12]: sim._block_list
Out[12]: 
{'age': [],
'iord': [<Family gas>, <Family dm>, <Family star>],
'mass': [<Family gas>, <Family dm>, <Family star>],
'metals': [<Family gas>],
'ne': [<Family gas>],
'nh': [<Family gas>],
'pos': [<Family gas>, <Family dm>, <Family star>],
'rho': [<Family gas>],
'sfr': [<Family gas>],
'smooth': [<Family gas>],
'u': [<Family gas>],
'vel': [<Family gas>, <Family dm>, <Family star>]}

I think that the field AGE should be only for stars. I have tried with the following:

[gadget-default-output]
all= pos, vel, mass, metals
**stars= age**
gas= u, rho, ne, nh, smooth, sfr
field-ordering = pos, vel, iord, mass, u , age, metals, rho, ne, nh, smooth, sfr

but nothing changes...

**Comment by isantossantos** [comment]
By the way... a different but related problem:
I also have hdf5 outputs for the same simulation. After changing the config.ini file (this was easier) I was able to load the snapshot and read correctly all the fields ,( except for StellarFormationTime, which is 'aform' and pynbody doesn't like).However, when I do 
h=sim.halos()
 it  loads the AHF_halos file, but not the AHF_particles file. So if I do
h[3].s['x']
it says it's a DummyHalo etc. This problem **does not** happen when the simulation I am loading is the one in the normal gadget output (the one I'm talking about above). This does not make sense to me... why should there be any difference? AHF was run over the normal gadget snapshots, but if the particle IDs are the same in both types of snapshot outputs (same simulation) it should work with both,no?

**Comment by isantossantos** [comment]
Ok, I have updated pynbody again and now I have the aform->tform transformation but there is still a problem when I do:
sim.s['tform'] (or sim.s['age'])
**ValueError: A value in x_new is below the interpolation range.**
In this simulation, stars (PartType4) can have a negative 'aform' value which means they are actually wind particles (Auriga), so I tried with: 
sim.s[np.where (sim.s['aform']>0)  ]['tform']
but the same error appears.

I will email you directly with instructions to access the files
thank you

**Comment by apontzen** [comment]
Oh no! Why doesn't it store them as a different particle type?

But yes, an automatically derived array always applies to the whole array. You could try manually setting the `tform` for the particles you want, i.e. something like

```python
sim.s['tform'] = 0
mask = sim.s['aform']>0
sim.s['tform'][mask] = pynbody.derived.tform(sim.s['aform'][mask])
```

**Comment by isantossantos** [comment]
Hi,
I've been able to load the AHF_particles correctly now! by doing:
h= pynbody.halo.ahf.AHFCatalogue(sim,  **use_iord=True**)
But still the problem with tform remains. If I apply the mask you suggested above, I get the following error with the last line:
sim.s['tform'][mask] = pynbody.derived.tform(sim.s['aform'][mask])
**IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices**

I did another test defining:
h[3].s['tform'] = 10.
and tried:
h[3].s['age']
but it says **UnitsException: Unknown units**
I think that the transformation aform->tform in derived.py is also missing adding units to the created tform simarray (?)

**Comment by isantossantos** [comment]
Some other issues:
Since there is this incompatibility with the dtypes float32 and float64 to make kdtree images,  I followed what was suggested here https://github.com/pynbody/pynbody/issues/301  to put pos, mass in dtype= float32. Putting it in this way , pynbody can return the sim.g['smooth'] array, but when I do:
**pynbody.plot.sph.image(h1.g, qty="rho",width='30 kpc', threaded=False)**
I get the following error:

TypeError                                 Traceback (most recent call last)
<ipython-input-13-de9b95e0aef9> in <module>()
----> 1 figure(); pynbody.plot.sph.image(hm31.g,qty='rho',width='30 kpc', threaded=False)

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/plot/sph.pyc in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    421     else:
    422         im = sph.render_image(sim, qty, width / 2, resolution, out_units=units,
--> 423                               kernel=kernel,  z_camera=z_camera, **kwargs)
    424 
    425     if fill_nan:

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, approximate_fast, threaded, denoise)
    534         im = base_renderer(snap, qty, x2, nx, y2, ny, x1, y1, z_plane,
    535                            out_units, xy_units, kernel, z_camera, smooth,
--> 536                            smooth_in_pixels, False)
    537 
    538     if denoise:

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in render_fn(*args, **kwargs)
    419         kwargs['res_downgrade'] = 1
    420         sub = 1
--> 421         base = fn(*args, **kwargs)
    422         kwargs['smooth_range'] = (1, 2)
    423         for i in xrange(1, levels):

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in _render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, smooth_range, res_downgrade, snap_slice, __threaded)
    661 
    662     result = _render.render_image(nx, ny, x, y, z, sm, x1, x2, y1, y2, z_camera, 0.0, qty, mass, rho,
--> 663                                   smooth_lo, smooth_hi, kernel, repeat_array, repeat_array)
    664 
    665     result = result.view(array.SimArray)

pynbody/sph/_render.pyx in pynbody.sph._render.__pyx_fused_cpdef (pynbody/sph/_render.c:35185)()

**TypeError: No matching signature found**

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
If instead I pass mass and pos to float64, calling to sim.g['smooth'] gives the following error:
ValueError                                Traceback (most recent call last)
<ipython-input-20-dc8e7ef11643> in <module>()
----> 1 sim.g['smooth']

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in __getitem__(self, i)
    261 
    262         if isinstance(i, str):
--> 263             return self._get_array_with_lazy_actions(i)
    264         elif isinstance(i, slice):
    265             return SubSnap(self, i)

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in _get_array_with_lazy_actions(self, name)
    354                     self.__load_if_required(name)
    355                 if not self.lazy_derive_off:
--> 356                     self.__derive_if_required(name)
    357 
    358             return self._get_array(name)

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in __derive_if_required(self, name)
    369     def __derive_if_required(self, name):
    370         if name not in self.keys():
--> 371             self._derive_array(name)
    372 
    373     def __resolve_obscuring_family_array(self, name):

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in _derive_array(self, array_name, fam)
   1970     def _derive_array(self, array_name, fam=None):
   1971         if fam is self._unifamily or fam is None:
-> 1972             self.base._derive_array(array_name, self._unifamily)
   1973 
   1974 

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in _derive_array(self, name, fam)
   1499                         name, always_writable=True)
   1500                 else:
-> 1501                     result = fn(self[fam])
   1502                     ndim = result.shape[-1] if len(
   1503                         result.shape) > 1 else 1

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in smooth(self)
    134     start = time.time()
    135     self.kdtree.set_array_ref('smooth',sm)
--> 136     self.kdtree.populate('hsm', config['sph']['smooth-particles'])
    137     end = time.time()
    138 

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/kdtree.pyc in populate(self, mode, nn)
    116             nn = 64
    117 
--> 118         smx = kdmain.nn_start(self.kdtree, int(nn), self.boxsize)
    119 
    120         propid = self.smooth_operation_to_id(mode)

**ValueError: The particles span a region larger than the specified boxsize**

(where 
In [22]: sim.properties['boxsize']
Out[22]: Unit("1.48e+05 kpc")
)
:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
And trying to make the sph image gives something very similar (or the same):
`
ValueError                                Traceback (most recent call last)
<ipython-input-18-d4915ad5b3fe> in <module>()
----> 1 figure(); pynbody.plot.sph.image(h1.g,qty="rho",width='30 kpc', threaded=False)

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/plot/sph.pyc in image(sim, qty, width, resolution, units, log, vmin, vmax, av_z, filename, z_camera, clear, cmap, title, qtytitle, show_cbar, subplot, noplot, ret_im, fill_nan, fill_val, linthresh, **kwargs)
    421     else:
    422         im = sph.render_image(sim, qty, width / 2, resolution, out_units=units,
--> 423                               kernel=kernel,  z_camera=z_camera, **kwargs)
    424 
    425     if fill_nan:

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, approximate_fast, threaded, denoise)
    534         im = base_renderer(snap, qty, x2, nx, y2, ny, x1, y1, z_plane,
    535                            out_units, xy_units, kernel, z_camera, smooth,
--> 536                            smooth_in_pixels, False)
    537 
    538     if denoise:

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in render_fn(*args, **kwargs)
    419         kwargs['res_downgrade'] = 1
    420         sub = 1
--> 421         base = fn(*args, **kwargs)
    422         kwargs['smooth_range'] = (1, 2)
    423         for i in xrange(1, levels):

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in _render_image(snap, qty, x2, nx, y2, ny, x1, y1, z_plane, out_units, xy_units, kernel, z_camera, smooth, smooth_in_pixels, force_quiet, smooth_range, res_downgrade, snap_slice, __threaded)
    569     # cache the arrays and take a slice of them if we've been asked to
    570     for arname in 'x', 'y', 'z', 'pos', smooth, qty, 'rho', 'mass':
--> 571         snap_proxy[arname] = snap[arname]
    572         if snap_slice is not None:
    573             snap_proxy[arname] = snap_proxy[arname][snap_slice]

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in __getitem__(self, i)
    261 
    262         if isinstance(i, str):
--> 263             return self._get_array_with_lazy_actions(i)
    264         elif isinstance(i, slice):
    265             return SubSnap(self, i)

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in _get_array_with_lazy_actions(self, name)
    354                     self.__load_if_required(name)
    355                 if not self.lazy_derive_off:
--> 356                     self.__derive_if_required(name)
    357 
    358             return self._get_array(name)

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in __derive_if_required(self, name)
    369     def __derive_if_required(self, name):
    370         if name not in self.keys():
--> 371             self._derive_array(name)
    372 
    373     def __resolve_obscuring_family_array(self, name):

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in _derive_array(self, array_name, fam)
   1970     def _derive_array(self, array_name, fam=None):
   1971         if fam is self._unifamily or fam is None:
-> 1972             self.base._derive_array(array_name, self._unifamily)
   1973 
   1974 

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in _derive_array(self, array_name, fam)
   1802 
   1803     def _derive_array(self, array_name, fam=None):
-> 1804         self.base._derive_array(array_name, fam)
   1805 
   1806     def family_keys(self, fam=None):

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc in _derive_array(self, name, fam)
   1499                         name, always_writable=True)
   1500                 else:
-> 1501                     result = fn(self[fam])
   1502                     ndim = result.shape[-1] if len(
   1503                         result.shape) > 1 else 1

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/__init__.pyc in smooth(self)
    134     start = time.time()
    135     self.kdtree.set_array_ref('smooth',sm)
--> 136     self.kdtree.populate('hsm', config['sph']['smooth-particles'])
    137     end = time.time()
    138 

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/sph/kdtree.pyc in populate(self, mode, nn)
    116             nn = 64
    117 
--> 118         smx = kdmain.nn_start(self.kdtree, int(nn), self.boxsize)
    119 
    120         propid = self.smooth_operation_to_id(mode)

**ValueError: The particles span a region larger than the specified boxsize**

**Comment by apontzen** [comment]
@isantossantos please post separate problems in a new issue

Re your issue with the slice, what is `type(mask)`, and/or `mask.dtype`? I am unclear what can be going wrong here, but as you can see it is complaining that the mask is not of the right type to index an array.

**Comment by isantossantos** [comment]
Hi , sorry, the mask works correctly,
In [303]: sim.s['aform'][mask]
Out[303]: 
SimArray([ 0.24213843,  0.31842414,  0.19580525, ...,  0.81822419,
        0.85303968,  0.93284714], dtype=float32)

 the error is in the tform function:
In [306]: pynbody.derived.tform(  sim.s['aform'][mask])
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-306-24d59f02b578> in <module>()
----> 1 pynbody.derived.tform(  sim.s['aform'][mask])

/z/isantossantos/anaconda2/lib/python2.7/site-packages/pynbody/derived.pyc in tform(self)
    307     """The time of the specified expansion factor in the aform"""
    308     from . import analysis
--> 309     t = analysis.cosmology.age(self, 1./self['aform'] - 1.)
    310     return t

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices


In [302]: mask.dtype
Out[302]: dtype('bool')

**Comment by apontzen** [comment]
Oops, sorry, that is my typo in the suggestion above! What you want is `pynbody.derived.tform(sim.s[mask])` (it takes the whole simulation, not the `aform` array)

**Comment by apontzen** [comment]
Try branch issue-479 (PR #482) - this should fix the problem without needing to apply a mask directly. It will fill in NaNs in tform when aform is unphysical.

**Comment by isantossantos** [comment]
Hi, this works, thanks!
i have to use a mask however to calculate the magnitudes. but thats perfectly ok

**Comment by apontzen** [comment]
Great. In principle it would be possible to scan for negative aform and use it to separate out the sink particles explicitly, meaning you wouldn't need to use the mask. Or just change the code to save them out as a different particle type! Can this issue now be closed? 

Did you ever open an issue on the image rendering problem? I can't see it...

**Comment by isantossantos** [comment]
yes this issue can be closed, thank you. 
i didn't open yet a new issue with the rendering problem, i was still checking some things, and I manage to make the sph.images but not the stars.render ones. I have similar errors to this issue by Tobias https://github.com/pynbody/pynbody/issues/464
should I reply there?

**Comment by apontzen** [comment]
Sounds good!
