### ISSUE TITLE
`IndexedSimArray` problem

### ISSUE THREAD

**Issue by elehcim** [pynbody/pynbody#485]
I tried to run the script [examples/vdisp.py](../tree/master/examples/vdisp.py) with pynbody 0.46 and python 3.6. I think it should work even if it's an old one. I tried with many Gadget2 datasets including `testdata/test_g2_snap.1`, the error persists.
I have the following problem in accessing an `IndexedSimArray`.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-23f851898348> in <module>()
     13     bininds = np.where(rxyinds == ind)
---> 14     sigvz[i] = np.std(stars[bininds]['vz'].in_units('km s^-1'))
     15 
     16     try:

~/Software/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in std(a, axis, dtype, out, ddof, keepdims)
   3022             pass
   3023         else:
-> 3024             return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)
   3025 
   3026     return _methods._std(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

~/Software/miniconda3/lib/python3.6/site-packages/pynbody-0.46-py3.6-linux-x86_64.egg/pynbody/array.py in q(s, *y, **kw)
    945         # but it seems required on McMaster setup (Py 2.6.5, NP 1.4.1)
    946         if kw != {}:
--> 947             return w(SimArray(s), *y, **kw)
    948         else:
    949             return w(SimArray(s), *y)

~/Software/miniconda3/lib/python3.6/site-packages/pynbody-0.46-py3.6-linux-x86_64.egg/pynbody/array.py in __new__(subtype, data, units, sim, **kwargs)
    194     def __new__(subtype, data, units=None, sim=None, **kwargs):
    195         new = np.array(data, **kwargs).view(subtype)
--> 196         if hasattr(data, 'units') and hasattr(data, 'sim') and units is None and sim is None:
    197             units = data.units
    198             sim = data.sim

~/Software/miniconda3/lib/python3.6/site-packages/pynbody-0.46-py3.6-linux-x86_64.egg/pynbody/array.py in sim(self)
    906     @property
    907     def sim(self):
--> 908         return self.base.sim[self._ptr]
    909 
    910     @sim.setter

TypeError: 'NoneType' object is not subscriptable
```

If I run the failing line `np.std(stars[bininds]['vz'].in_units('km s^-1'))` twice in a notebook cell the first time it raises the `TypeError` while the second time it works.

**Comment by elehcim** [comment]
To reproduce the error I run the following script with `testdata/gadget1.snap` as input. It is not the same as the original `vdisp.py` (I commented out the halo catalogue requirement, the filter on the `rxy` of the stars and the `pynbody.analysis.angmom.faceon(s)` line). I'm sorry if I kind of moved the problem. 
I can reproduce the problem with my dataset with the rotation `angmom.faceon` and the filter on the stars turned on. If you really think those are important I can send you my snapshot and my `.pynbodyrc` file. Thanks.

```
import pynbody, sys
import matplotlib.pyplot as plt
import numpy as np

tfile = sys.argv[1]
s = pynbody.load(tfile)
# pynbody.analysis.angmom.faceon(s)
stars = s.s # [pynbody.filt.LowPass('rxy','2 kpc')]
rxyhist, rxybins = np.histogram(stars['rxy'],bins=20)
rxyinds = np.digitize(stars['rxy'], rxybins)
nrbins = len(np.unique(rxyinds))
sigvz = np.zeros(nrbins)
sigvr = np.zeros(nrbins)
sigvt = np.zeros(nrbins)
rxy = np.zeros(nrbins)

print(rxyinds)
for i, ind in enumerate(np.unique(rxyinds)):
    bininds = np.where(rxyinds == ind)
    sigvz[i] = np.std(stars[bininds]['vz'].in_units('km s^-1'))
    sigvr[i] = np.std(stars[bininds]['vr'].in_units('km s^-1'))
    sigvt[i] = np.std(stars[bininds]['vt'].in_units('km s^-1'))
    rxy[i] = np.mean(stars[bininds]['rxy'].in_units('kpc'))

plt.plot(rxy,sigvz,'o',label='$\sigma_{vz}$')
plt.plot(rxy,sigvr,'o',label='$\sigma_{vr}$')
plt.plot(rxy,sigvt,'o',label=r'$\sigma_{v \theta}$')
plt.xlabel('R$_{xy}$ [kpc]')
plt.ylabel('$\sigma$ [km s$^{-1}$]')

plt.legend(loc=0)

plt.savefig(tfile+'.vdisp.png')
```

**Comment by apontzen** [comment]
Sadly, I still can’t reproduce any error! Perhaps it relies on a certain configuration?

**Comment by elehcim** [comment]
With the default configuration and a fresh installation of pynbody 0.46 through pip, I found that with python2 the script works whereas it fails with the above error in python3.

**Comment by elehcim** [comment]
I boiled down the problem to this:

```
import pynbody
s = pynbody.load("testdata/test_g2_snap.1")
stars = s.s
print(stars[1]['vz'])
print(stars[1]['vz'].in_units('km s^-1'))
```

running the above in python2 it works with output:
```
[1.9441841]
[1.0246749]
```

in python3 it crashes:
```
[1.9441841]
[1.0246749]
Exception ignored in: <bound method _wrap_fn.<locals>.q of SimArray([1.0246749], dtype=float32, 'km s**-1')>
Traceback (most recent call last):
  File "~/PYNBODY3/lib/python3.6/site-packages/pynbody/array.py", line 950, in q
    return w(SimArray(s), *y)
  File "~/PYNBODY3/lib/python3.6/site-packages/pynbody/array.py", line 196, in __new__
    if hasattr(data, 'units') and hasattr(data, 'sim') and units is None and sim is None:
  File "~/PYNBODY3/lib/python3.6/site-packages/pynbody/array.py", line 909, in sim
    return self.base.sim[self._ptr]
TypeError: 'NoneType' object is not subscriptable

```

So, unless I perform the unit conversion on the derived array of the `SimSnap "testdata/test_g2_snap.1::star:indexed"` python3 behaves like python2.

Please tell me if you manage to reproduce this. Thanks

**Comment by elehcim** [comment]
The error message [of the previous comment](https://github.com/pynbody/pynbody/issues/485#issuecomment-425024349) is actually an `Exception ignored`, which happened in the `__del__` method.
When instead any other method is called on a unit-converted `IndexedSimArray` (like `np.std`), a real `TypeError` Exception is thrown but only in python 3 (as in the first message).

This is due to the fact that in a converted `IndexedSimArray` the `IndexedSimArray.base.sim` attribute is None as can be seen below:

```python
import pynbody
s = pynbody.load("testdata/test_g2_snap.1")
stars = s.s
indexed_arr = stars[1,2]['vz']
print("indexed_arr.base.sim:",indexed_arr.base.sim)  # <SimSnap "testdata/test_g2_snap.1::star" len=18>
print("converted indexed_arr.base.sim:",indexed_arr.in_units('km s^-1').base.sim)  # None
```

Due to how the `IndexedSimArray` is wrapped around `SimArray`, whenever a `SimArray` method was called the `SimArray.__new__` method was called too. There, the `hasattr(data, 'sim')` [line](https://github.com/pynbody/pynbody/blob/3fac16d1a2fe8170e73828613378021c4726a7ea/pynbody/array.py#L195) (where `data` is the [newly created](https://github.com/pynbody/pynbody/blob/3fac16d1a2fe8170e73828613378021c4726a7ea/pynbody/array.py#L924) unit-converted `IndexedSimArray`) is the guilty piece of code.

In fact `hasattr` has different behaviours in python2 vs python3. While checking an attribute which could be a property, in python2 `hasattr` actually swallows any exception and returns False, whereas in python3 it throws the exception. See more [here](https://hynek.me/articles/hasattr/), a good read.

To solve the issue I just removed the exception in `IndexedSimArray.sim` property in commit: https://github.com/elehcim/pynbody/commit/510bc03fe21cdf05cef3731946b1694f87e0f864.

Maybe a better fix would be to relink the correct `base.sim` for a unit-converted `IndexedSimArray`, which now is lost. But for now I don't know how to do it.

**Comment by apontzen** [comment]
Thanks for tracking this down! I seem to recall this is the correct behaviour, as in some places there is an assumption that `ar.sim[ar.name] is ar`, if it exists. Which is not true for the converted array. Your fix seems very sensible.
