### ISSUE TITLE
Rockstar not making halo catalogue 

### ISSUE THREAD

**Issue by SaraZahoor** [pynbody/pynbody#497]
pynbody is reading the snapshot for Gadget2 as

```
s = pynbody.load('/export/home3/rcms/sara.zahoor/sim128/halo8/snapshot_005')
```

but when I try make it reading the halos using

```
h = s.halos()
```

it gives me the following error,

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-0032989a1cfd> in <module>()
----> 1 h = s.halos()

~/soft/yt/yt-conda/lib/python3.6/site-packages/pynbody/snapshot/__init__.py in halos(self, *args, **kwargs)
    855                 pass
    856 
--> 857         raise RuntimeError("No halo catalogue found for %r" % str(self))
    858 
    859     def bridge(self, other):

RuntimeError: No halo catalogue found for '<SimSnap "/export/home3/rcms/sara.zahoor/sim128/halo8/snapshot_005" len=2097152>'
```

Does that mean that pynbody is not properly configured with the rockstar?

**Comment by SaraZahoor** [comment]
I was using pynbody on yt-conda. I changed it and now using on anaconda 3. 
In .pynbodyrc I am giving the path to rockstar as,
Path: /export/home3/rcms/sara.zahoor/soft/Rockstar-0.99.9-RC3

but leaving the the "config:" part, may be that`s why it was giving me error...

Now, I want to ask you two things,
1) I am using input of gadget2 snapshots and so when I load single snapshot it reads it, but does not read all of the snaps. I tried putting it in a zip folder and simple directory. But both times, it tells me that that this format is not readable or recognized. 

2) For gadget snaps, how to mention it in the config part in .pynbodyrc ?

   Config:   FILE_FORMAT = %(GADGET)s
          PARTICLE_MASS = %(1.36297e+08)d
          SCALE_NOW = %(1)f
          h0 = %(0.7)f
          Om = %(0.27)f
          Ol = %(0.73)f
          TIPSY_LENGTH_CONVERSION = %(boxsize)e
          TIPSY_VELOCITY_CONVERSION = %(vunit)e
          TIPSY_MASS_CONVERSION = %(munit)e
          FORCE_RES = %(0.05)e
          OUTPUT_FORMAT = BINARY
I am using GADGET, not TIPSY. Should I leave it to that or edit it to GADGET_LENGTH_CONVERSION and GADGET_MASS_CONVERSION ?

P.S: I am new to these things so that is why confused.

**Comment by apontzen** [comment]
I have never used the facility to auto-run rockstar - I think it may have been implemented by @rokroskar? 

My personal bias would be to run rockstar externally first, rather than get pynbody to run it for you which does add a layer of complication.

For your gadget files, assuming they are `snapshot_xxx.0`, `snapshot_xxx.1`, ..., you just ask pynbody to load `snapshot_xxx` and it will load the files together (see https://pynbody.github.io/pynbody/tutorials/data_access.html)

**Comment by SaraZahoor** [comment]
For gadget files, I have them as snapshot_000, snapshot_001, snapshot_002
and so on...
Am I suppose to just put snapshot_000 and it will read the rest by itself
or there is some specific command? because I tired it as snapshot_00. ,
snapshot_00 , snapshot_ , snapshot and etc, it is giving me the same error,

"File %r: format not understood or does not exist" % filename

**Comment by apontzen** [comment]
That sounds like a time sequence of snapshots - pynbody deals with each snapshot as a separate object, so you just want to load them in turn.

**Comment by SaraZahoor** [comment]
1) If I have to use rockstar, then do I need to find halos for each snap
(within pynbody)?

2) I have externally produced halo catalog  and have files
as,  halos_5.0.bin, halos_5.1.bin etc.
But when I try to make pynbody read it as,
 h =
pynbody.load("/export/home3/rcms/sara.zahoor/sim128/rs_1/halos_5.0.bin")

it gives me error,

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-43-51f6cf302063> in <module>()
----> 1 h =
pynbody.load("/export/home3/rcms/sara.zahoor/sim128/rs_1/halos_5.0.bin")

/export/home3/rcms/sara.zahoor/.conda/envs/py2.7/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc
in load(filename, *args, **kwargs)
   1984
   1985     raise IOError(
-> 1986         "File %r: format not understood or does not exist" %
filename)
   1987
   1988 def new(n_particles=0, order=None, **families):

IOError: File '/export/home3/rcms/sara.zahoor/sim128/rs_1/halos_5.0.bin':
format not understood or does not exist

3) And also, the this halo catalog was made for all the snapshots,
collectively. So, it is going to work for individual snapshot?

**Comment by apontzen** [comment]
I’m afraid I don’t fully get what you are attempting to do, in that case. Is it some sort of lightcone catalogue? If so, I don’t believe pynbody can read it unfortunately.

**Comment by apontzen** [comment]
Probably the best thing is if you state exactly what you are trying to do, and give a full listing of all files you have so far.

**Comment by SaraZahoor** [comment]
Well, I have Gadget output with just dark matter particles, i.e.
snapshot_001 - snapshot_005, each at different redshift.

Using rockstar, I want to identify, where halos are located. For which I`ll
be needing halo catalog. I want to show the projections or the circles
around the dark matter halos in my snapshots. So can I create a projection
plot with pynbody here?
Also, need to plot the halo mass function.

I hope it helps to understand...

**Comment by apontzen** [comment]
OK, so you should just be able to follow the tutorial, i.e. start with

```
f = pynbody.load("snapshot_005")
h = f.halos()
```

If that doesn’t work, please post a link to all files so that we can reproduce whatever problem you are running into.

**Comment by SaraZahoor** [comment]
I tried following the tutorial, but it`s not working, again getting
the same error


---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-375f4b3982ec> in <module>()
----> 1 h = f.halos()

/export/home3/rcms/sara.zahoor/.conda/envs/py2.7/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc
in halos(self, *args, **kwargs)
    854                 pass
    855
--> 856         raise RuntimeError("No halo catalogue found for %r" %
str(self))
    857
    858     def bridge(self, other):

RuntimeError: No halo catalogue found for '<SimSnap
"/export/home3/rcms/sara.zahoor/sim128/halo8/snapshot_005" len=2097152>'


and when I just try to upload the halo bin made from rockstar, as

h = pynbody.load
("/export/home3/rcms/sara.zahoor/sim128/rs_1/halos_5.0.bin")

I get this error message

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-9-92551204d00c> in <module>()
----> 1 h = pynbody.load
("/export/home3/rcms/sara.zahoor/sim128/rs_1/halos_5.0.bin")

/export/home3/rcms/sara.zahoor/.conda/envs/py2.7/lib/python2.7/site-packages/pynbody/snapshot/__init__.pyc
in load(filename, *args, **kwargs)
   1984
   1985     raise IOError(
-> 1986         "File %r: format not understood or does not exist" %
filename)
   1987
   1988 def new(n_particles=0, order=None, **families):

IOError: File '/export/home3/rcms/sara.zahoor/sim128/rs_1/halos_5.0.bin':
format not understood or does not exist

**Comment by SaraZahoor** [comment]
snapshot_005
<https://drive.google.com/file/d/1cY0PCcKlGJHodqvIxgTHVbjp6C0_ypxk/view?usp=drive_web>

**Comment by apontzen** [comment]
I need _all_ files, including the rockstar catalogues, otherwise I cannot reproduce the problem.

**Comment by SaraZahoor** [comment]
Can you give me some time? Because I am not able to create a link for all
of these files on the cluster that I am using.
Can I send it to you through Dropbox?

**Comment by SaraZahoor** [comment]
I have uploaded the gadget`s snapshots and rockstar output in this dropbox folder.
I hope you are able to access the files here...

https://www.dropbox.com/sh/h2ev7kld5zrwa8h/AACMWb7M3yKqTP-Aw5f43LRoa?dl=0

**Comment by apontzen** [comment]
It all works well for me. I put your `halos_5...` files and snapshots in the same folder (this is essential) and then tested as follows:

```python
In [1]: import pynbody

In [2]: f = pynbody.load("snapshot_005")

In [3]: h = f.halos()

In [4]: h[1]
Out[4]: <SimSnap "snapshot_005:halo_1" len=85>

In [5]: h[1].properties
Out[5]: 
{'omegaM0': 0.308,
 'omegaL0': 0.692,
 'boxsize': Unit("1.00e+02 Mpc a h**-1"),
 'a': 0.9999999999999996,
 'h': 0.678,
 'time': Unit("9.57e-03 Mpc s a**1/2 h**-1 km**-1"),
 'halo_id': 1,
 'id': 1,
 'pos': array([0.07847197, 0.04969056, 0.07229796], dtype=float32),
 'vel': array([ -747.4232 ,   -88.34059, -1099.8649 ], dtype=float32),
 'corevel': array([ -747.4232 ,   -88.34059, -1099.8649 ], dtype=float32),
 'bulkvel': array([ -747.4232 ,   -88.34059, -1099.8649 ], dtype=float32),
 ...
}
```
It looks to me like you only have halo catalogues for snapshot 5. Loading the halos for other snapshots fails because they have not yet been computed - you'll need to rerun Rockstar for those snapshots. 

Note also that your snapshot 4 is at the same redshift as snapshot 5 which suggests a minor configuration error (mainly harmless) in your gadget setup.

**Comment by SaraZahoor** [comment]
It worked!!!
Thank you so much. I should have just put all the data in one directory.  :)

**Comment by apontzen** [comment]
Glad to be able to help!
