### ISSUE TITLE
Is there any code about velocity field?

### ISSUE THREAD

**Issue by erokumasama** [pynbody/pynbody#509]
I knew there is "sph.velocity_image" in Pynbody that can do the velocity vector image,
but is there any code that can do the velocity field image, just like the first moment image of radio astronomy?

Is this correct that I just set the " qty='vr' " in image function?

**Comment by apontzen** [comment]
Yes, or more precisely you should set `qty='vx'` and `av_z='rho'` to e.g. average the x component of the velocity along the line of sight, weighted by density. You can weight by any other property too. Does this help?

**Comment by 8la888** [comment]
Yes, your advise really help me to understand how do this code work.
I will try to change more parameters, also.
Thank you a lot.

**Comment by apontzen** [comment]
Very welcome!
