### ISSUE TITLE
Fields 'rho' and 'smooth' for DM particles

### ISSUE THREAD

**Issue by chaoticinflaton** [pynbody/pynbody#514]
I recently got some data from another group which includes the particles of one halo. 

When I access the loadable keys for the snapshot, I get:

`In[5]: s.dm.loadable_keys()`
`Out[5]: ['iord', 'mass', 'pos', 'vel']`

However, when I say:

`s.dm['smooth']`, 

It takes a little while and gives me what I presume is anarray of smoothing lengths. 

It does the same when I call `s.dm['rho']` , now giving me an array of densities. 

My question is, what are these two quantities "rho" and "smooth" exactly? Is the rho a computed smoothed density around each particle? If it is, can I control the smoothing lengths / kernels?

-----------------------------------------------------------------------

On a related note, is there a way to do a cloud-in-cell density assignment internally?

Thanks a ton,
Himanish

**Comment by apontzen** [comment]
They are calculated using the SPH module, which defaults to a 32 nearest-neighbour algorithm but can be customised from the configuration file.

I'm afraid there isn't any cloud-in-cell algorithm within pynbody.
