### ISSUE TITLE
use_iord must be set to true when using GadgetHDFSnap

### ISSUE THREAD

**Issue by rennehan** [pynbody/pynbody#515]
Hello, 

I'm using pynbody-0.46 with GIZMO and have been using the GadgetHDFSnap as an interface, since they are effectively the same.

I realized after a few hours of reading through the code that there should be the following at the beginning of pynbody/halo/ahf.py:

```python
if use_iord is None:
    use_iord = isinstance(sim.ancestor, snapshot.gadgethdf.GadgetHDFSnap)
```

It should be beneath the following:

```python
if use_iord is None:
    use_iord = isinstance(sim.ancestor, snapshot.gadget.GadgetSnap)
```

Thanks for the code!

EDIT: I just made it cleaner, doh.

**Comment by apontzen** [comment]
Thanks for the report. I have tried making a fix for this in branch `issue-515` (PR #516) - could you confirm whether it works for you?

**Comment by rennehan** [comment]
Yes, that works, thank you.

**Comment by apontzen** [comment]
Merged
