### ISSUE TITLE
Possible bug in fast_kde

### ISSUE THREAD

**Issue by ttepperg** [pynbody/pynbody#519]
Hi,

There appears to be a bug in pynbody.plot.util.fast_kde at line:

kernel = kernel.reshape((kern_ny, kern_nx))

Both kern_nx/ny are defined as floats, but reshape expects int's.

A call to fast_kde() indeed fails with the following error message:

kernel = kernel.reshape((kern_ny, kern_nx))
TypeError: 'numpy.float64' object cannot be interpreted as an index

I have verified that the error disappears if casting kern_nx/ny into int's
at the aforementioned call, e.g.:

kernel = kernel.reshape((int(kern_ny), int(kern_nx)))

I've tested this only on an iMac running python2.7 installed via MacPorts.

Hope this helps!

Thor.

**Comment by apontzen** [comment]
Thanks, I have made this change in #522 - could you confirm this is what you had in mind and it fixes your problem?

**Comment by apontzen** [comment]
@ttepperg Quick check-in about whether PR #522 fixes your problem? This will enable me to merge and close this issue.

**Comment by ttepperg** [comment]
yes, it appears to fix it, thanks a lot!

--------------------------------------------
Dr. Thor Tepper-Garcia
Postdoctoral Research Associate
ASTRO-3D | GASKAP | GALAH Member
Sydney Institute for Astronomy
School of Physics (A28.328)
The University of Sydney
NSW 2006 Australia
www.thorsten.mx<http://www.thorsten.mx/>


On 31 Aug 2019, at 5:41 pm, Andrew Pontzen <notifications@github.com<mailto:notifications@github.com>> wrote:


@ttepperg<https://protect-au.mimecast.com/s/AhiQCgZowLH3Yo6VTohEKC?domain=github.com> Quick check-in about whether PR #522<https://protect-au.mimecast.com/s/gWG1CjZrzqHryBEph5VjNG?domain=github.com> fixes your problem? This will enable me to merge and close this issue.

**Comment by apontzen** [comment]
No problem, thanks for the report. Merged to master.
