### ISSUE TITLE
time value when writing tipsy file

### ISSUE THREAD

**Issue by dumasj** [pynbody/pynbody#523]
When I use f.write(fmt=pynbody.tipsy.TipsySnap, filename='name') to write a tipsy file for a non-cosmological simulation, the time value in f.properties is overwritten to {'time': Unit("1.00e+00 s kpc km**-1")}. I will need the time value to be unchanged. Any assistance is appreciated.

**Comment by apontzen** [comment]
Thanks for the report. In branch `issue-523` (PR #524) I tried adding an option `f.write(fmt=pynbody.tipsy.TipsySnap, filename='name', cosmological=False)` -- could you try it out and confirm if this fixes it for you?

**Comment by dumasj** [comment]
Yes it works now, the time value remains unchanged. Thanks

**Comment by apontzen** [comment]
Great, merged into master
