### ISSUE TITLE
Total energy (te) calculation fails

### ISSUE THREAD

**Issue by ttepperg** [pynbody/pynbody#529]
Hi,

The calculation of the specific total energy (derived 'te') fails
because the calculation of the specific potential energy 'phi' is not available.
I'm guessing this was accidentally removed after a code update?
Could it be added in the next version and / or a code snippet provided
on how to efficiently calculate 'phi'?

Thanks!

Thor.

**Comment by apontzen** [comment]
Phi has to be provided in the simulation snapshot, unfortunately, so this is a format-dependent function. Pynbody doesn’t currently have a fast way to calculate potential of all particles. I agree this could/should be made clearer in the code so that it is not so much of a surprise when it fails.

**Comment by Astrokiwi** [comment]
There's a nice python library called pykdgrav (not to be confused with the
n body code with the same name) that can calculate potentials for you. It's
on pip (pip import pykdgrav). It doesn't always play nicely with the
pynbody wrapped arrays though so you sometimes have to convert to vanilla
numpy arrays.

-David Williamson
University of Southampton

**Comment by Astrokiwi** [comment]
btw would you ever consider incorporating pykdgrav into pynbody? I'm not sure how the gitiquette of combining repos like that works, but I think it'd be a useful addition if we could get them to talk to each other.

**Comment by ttepperg** [comment]
Thank you both for your reply, both very, very helpful!

Cheers,

Thor.

--------------------------------------------
Dr. Thor Tepper-Garcia
Postdoctoral Research Associate
ASTRO-3D | GASKAP | GALAH Member
Sydney Institute for Astronomy
School of Physics (A28.328)
The University of Sydney
NSW 2006 Australia
www.thorsten.mx<http://www.thorsten.mx/>


On 5 Jun 2019, at 4:02 am, Astrokiwi <notifications@github.com<mailto:notifications@github.com>> wrote:

There's a nice python library called pykdgrav (not to be confused with the
n body code with the same name) that can calculate potentials for you. It's
on pip (pip import pykdgrav). It doesn't always play nicely with the
pynbody wrapped arrays though so you sometimes have to convert to vanilla
numpy arrays.

-David Williamson
University of Southampton

**Comment by apontzen** [comment]
@Astrokiwi I agree something like this functionality would be useful but pynbody already calculates a kdtree for sph, so it would be annoying to have to calculate a separate kdtree to do gravity. In an ideal world we would merge the functionality so that a single kdtree can serve both purposes. I don't have a timescale for any work like that, unless there are volunteers!
