### ISSUE TITLE
HII calculation should include H2 (if available)

### ISSUE THREAD

**Issue by emapple** [pynbody/pynbody#533]
If H2 is tracked in the simulation, this will give the incorrect HII (it will assume the hydrogen in molecular phase is ionized).

https://github.com/pynbody/pynbody/blob/b37d0dba99d7b64ab2fc51355d8068afb609d7ab/pynbody/snapshot/tipsy.py#L986-L990

Should be solved (if H2 is present) by subtracting out 2 * sim['H2'], I believe.

**Comment by apontzen** [comment]
I agree, could you make a pull request?

**Comment by emapple** [comment]
Merged.
