### ISSUE TITLE
GadgetHDF5 and AHF halo catalogue gives Dummyhalo

### ISSUE THREAD

**Issue by TobiBu** [pynbody/pynbody#537]
Hi,

I try to use GADGETHDF5 snapshots together with an AHF catalogue.

When trying to load the halo catalogue I solely get DummyHalos.

`import pynbody`
`f = pynbody.load('./snapshot_127')`
`h = pynbody.halo.AHFCatalogue(f)`

similar behaviour happens also with
`h = f.halos()`

I put up some GADGETHDF5 files and the corresponding AHF files [here](https://datashare.mpcdf.mpg.de/s/78Z1H8EQZnsMwyc).

**Comment by apontzen** [comment]
The problem seems to be with the AHF particle files. Pynbody is expecting two columns but these files have 8, so it doesn't know what to do with them. Is this a new version of AHF, or a hacked private version?

**Comment by TobiBu** [comment]
I see, 
I think it is kind of a hacked version for the HESTIA project.

I will contact Alexander Knebe and ask him if its a hack or new version.

Meanwhile I will take a look at the nailing of the particles file and see if I can get around it.

**Comment by apontzen** [comment]
It shouldn't be too hard to get around, for sure. You just need to know how to detect whether the file will have this new format.

**Comment by TobiBu** [comment]
great,
do you have any more details what goes wrong?
Pynbody simply can't handle the file?

**Comment by apontzen** [comment]
Yes, you can see the underlying error by calling `_load_ahf_particle_block` manually -- the error is at line 307

**Comment by TobiBu** [comment]
thanks. I guess from there I can take it.

If it turns out, that's a new version of AHF, I gonna get back to you and make a pull request.

**Comment by apontzen** [comment]
Sounds good! Might as well do that anyway if it is a version that a reasonable number of people might encounter.
