### ISSUE TITLE
Broken Ramses birth times for isolated simulations

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/pynbody#554]
Hi,

A master student in Lund, Oscar Andersson, made me aware that the current handling of 'ages' and 'tform' arrays for RAMSES isolated, non-cosmological, simulations is broken, most likely due to PR #521 . 

By default, pynbody now tries to load the birth files to convert the birth times of stellar particles in a physically-meaningful unit, but this operation (and the associated birth files) are unnecessary in the context of isolated simulations.

I will submit a fix refining the behaviour here:
https://github.com/pynbody/pynbody/blob/e0ade3bf17eaa2d9d3eb2aa63853ed6c48452c6e/pynbody/snapshot/ramses.py#L971-L977

Is there an isolated snapshot in old-RAMSES format in the current test data to design a test?

Martin

**Comment by apontzen** [comment]
Thanks Martin. I don't think there is such a snapshot in the test data but I'd be happy to add one if you have access to a small one.

**Comment by Martin-Rey** [comment]
Should be fixed by #602
