### ISSUE TITLE
ramses star ages broken

### ISSUE THREAD

**Issue by mkrets** [pynbody/pynbody#559]
Hi,

in my cosmological ramses runs I use `use_proper_time=.true.` .

I noticed that I had to put back `birth_time: tform` in `.pynbodyrc`.

`data.s["age"].in_units("Gyr")`
gives: UnitsException: Unknown units

but 
`data.s["tform_raw"].in_units("Gyr")`
yields some negative values.

It seems that 
`data.properties["time"].in_units("Gyr") + data.s["tform_raw"].in_units("Gyr")`
gives the correct birth times.

You can find an example output here:
https://www.dropbox.com/s/tb85zmril8p60tx/output_00030.tar.gz

It would be great if `use_proper_time=.true.` would be supported either through `.pynbodyrc` or automatically by reading the namelist (I had something in mind with #534).

I hope that describes the problem well enough.
Thank you for your help.

**Comment by mkrets** [comment]
A quick fix is to modify `_convert_tform`:

```python
def _convert_tform(self):
    # Copy the existing array in weird Ramses format into a hidden raw array
    self.star['tform_raw'] = self.star['tform']
    self.star['tform_raw'].units = self._file_units_system[1]
    if config_parser.getboolean("ramses", "proper_time", fallback=False):
        t0 = analysis.cosmology.age(self, z=0.0, unit="Gyr")
        birth_time = t0 + self.s["tform_raw"].in_units("Gyr")/self.properties["a"]**2
        birth_time[birth_time > t0] = t0 - 1e-7
        self.star['tform'] = birth_time
    else:
        from ..analysis import ramses_util
        # Replace the tform array by its usual meaning using the birth files
        ramses_util.get_tform(self)

```

and then add in the config `.pynbodyrc`:

```
[ramses]
proper_time: True
...
```
If its not present the code above will fall back to False and execute the ramses_util part.

I still need to add `birth_time: tform` as well.
```
[ramses-name-mapping]
# For RAMSES format post November 2017: map the names in the part_file_descriptor.txt to pynbody names
position_x: x
position_y: y
position_z: z
velocity_x: vx
velocity_y: vy
velocity_z: vz
identity: iord
levelp: level
birth_time: tform

...
```

Hope that helps.

**Comment by YuankangLiu** [comment]
> A quick fix is to modify `_convert_tform`:
> 
> ```python
> def _convert_tform(self):
>     # Copy the existing array in weird Ramses format into a hidden raw array
>     self.star['tform_raw'] = self.star['tform']
>     self.star['tform_raw'].units = self._file_units_system[1]
>     if config_parser.getboolean("ramses", "proper_time", fallback=False):
>         t0 = analysis.cosmology.age(self, z=0.0, unit="Gyr")
>         birth_time = t0 + self.s["tform_raw"].in_units("Gyr")/self.properties["a"]**2
>         birth_time[birth_time > t0] = t0 - 1e-7
>         self.star['tform'] = birth_time
>     else:
>         from ..analysis import ramses_util
>         # Replace the tform array by its usual meaning using the birth files
>         ramses_util.get_tform(self)
> ```
> 
> To explain, if ramses was run with `use_proper_time=.true.` the ages written to the files are in lookback time (and codeunits). By converting them with `unit_t` we multiply with `aexp**2 / (h0*1d5/Mpc2cm)` since the ages are already in "proper time" we don't need that factor `aexp**2` thats why it is divided out again in the snippet above. `t0` is just to transform from lookback time to "normal" time and the last check is to prevent ages later then `t0` which may occure because the cosmological calculations in pynbody and ramses are slightly different.
> 
> Additionally I add in the config `.pynbodyrc`:
> 
> ```
> [ramses]
> proper_time: True
> ...
> ```
> 
> If its not present the code above will fall back to False and execute the ramses_util part.
> 
> I still need to add `birth_time: tform` as well.
> 
> ```
> [ramses-name-mapping]
> # For RAMSES format post November 2017: map the names in the part_file_descriptor.txt to pynbody names
> position_x: x
> position_y: y
> position_z: z
> velocity_x: vx
> velocity_y: vy
> velocity_z: vz
> identity: iord
> levelp: level
> birth_time: tform
> 
> ...
> ```
> 
> Hope that helps.

This method works nicely.

**Comment by Martin-Rey** [comment]
Hi both, 

Thanks a lot for the report and code suggestion, this is definitely worth implementing into the master branch!

The proper time problem is something I have been aware for awhile, mostly because it is turned on  either explicitly through the `use_proper_time=.true.` namelist parameter, or implicitly if running with radiative transfer.  I was thinking of detecting automatically from the namelist whether the flag (or RT) were on, but asking the user to be explicit in its config file is simpler and requires less machinery. Have you tried whether your snippet of code passes the nosetests -- would you be happy to submit it as a pull request with a test catching this behaviour?

Another potential side effect is that `tform` for isolated, non-cosmological runs are actually in yet another unit (physical time, #554, which I need to fix myself but haven't had the time to look into). I think these two issues are orthogonal, but they both introduce a new edge case that needs to be dealt in the same place of the code.

Martin
