### ISSUE TITLE
bug(s) in zeldovich_offset?

### ISSUE THREAD

**Issue by marmusso** [pynbody/pynbody#567]
Hi, I am not an expert of analyzing simulations, so bear with me if this is not true... 

I believe that Zeldovich displacements are not implemented correctly. By reading the source code, I understand that velocities are divided by a*Ddot/D in order to get the displacement. This would be correct for physical velocities, v = a* dx/dt, but not for comoving velocities, dx/dt.
I understand that whether velocities are physical or not depends on which Nbody code one is using.
For instance, according to the manual Gadget outputs sqrt(a)*dx/dt (so neither physical nor comoving), in which case the calculation of Zeldovich displacement should divide by sqrt(a). 

On top of this, the code divides by a, whereas the corresponding units are divided by a^-1, ending up multiplying by a instead.

Are these bugs or am I missing something?

Another note. From the Gadget snapshot I am using, positions are imported in units of a*Mpc/h, whereas they should be in Mpc/h. Not sure if this is a separate issue, or still me missing something...

Any help with this? Thanks.

Marcello

**Comment by apontzen** [comment]
Thanks for the report. 

I don't believe there is an error here, and suspect you may be confused about the way the units system incorporates comoving units. By setting the units e.g. to `a Mpc`, it is indicating positions are comoving. The multiplication is taken literally, e.g. `3 a Mpc` means the physical length is 3 times the scalefactor times one megaparsec. When the Zel'dovich displacement is calculated, the formula as expressed needs to be correct for physical units. Any unit conversions, which are format-dependent (as you mention specifically for the gadget case), are then taken into account automatically. 

The easiest way to verify whether this works correctly is to try the `zeldovich_offset` with and without converting the file to `physical_units()` first. As far as I can tell everything seems consistent, and physically correct. However if you continue to disagree please post a reproducible example where you have a known correct solution and a corresponding incorrect result from pynbody.

Thanks again!

**Comment by apontzen** [comment]
I am closing the issue but please feel free to reopen it if you do have an example where the results are demonstrably wrong.
