### ISSUE TITLE
Installation of pynbody not possible (MacOs 11.0.1)

### ISSUE THREAD

**Issue by jackjack14** [pynbody/pynbody#590]
I run `pip3 install pynbody`. This results in an error. pip3 can install other packages (e.g. numpy).
I have the Xcode tools installed.

```
17 warnings and 4 errors generated.
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/private/var/folders/5q/xc22bbms0qjdgmpsv2188ydh0000gn/T/pip-build-env-3cjk1pyq/overlay/lib/python3.9/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c pynbody/gravity/_gravity.c -o build/temp.macosx-10.9-x86_64-3.9/pynbody/gravity/_gravity.o " failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pynbody
Failed to build pynbody
ERROR: Could not build wheels for pynbody which use PEP 517 and cannot be installed directly
```

I also tried to build manually (`python3 setup.py install`).

If I then try to use it in python (`import pynbody`), then I get the error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/Desktop/pynbody/pynbody/__init__.py", line 33, in <module>
    from . import util, filt, array, family, snapshot
  File "/Users/username/Desktop/pynbody/pynbody/util.py", line 30, in <module>
    from ._util import *
ModuleNotFoundError: No module named 'pynbody._util'`

During the installation (`python3 setup.py install`)
I get the error:

`zip_safe flag not set; analyzing archive contents...
pynbody.__pycache__._util.cpython-39: module references __file__
pynbody.__pycache__.configuration.cpython-39: module references __file__
pynbody.__pycache__.openmp.cpython-39: module references __file__
pynbody.analysis.__pycache__._com.cpython-39: module references __file__
pynbody.analysis.__pycache__._interpolate3d.cpython-39: module references __file__
pynbody.analysis.__pycache__.hifrac.cpython-39: module references __file__
pynbody.analysis.__pycache__.hmf.cpython-39: module references __file__
pynbody.analysis.__pycache__.ionfrac.cpython-39: module references __file__
pynbody.analysis.__pycache__.luminosity.cpython-39: module references __file__
pynbody.bridge.__pycache__._bridge.cpython-39: module references __file__
pynbody.chunk.__pycache__.scan.cpython-39: module references __file__
pynbody.extern.__pycache__._cython_fortran_utils.cpython-39: module references __file__
pynbody.gravity.__pycache__._gravity.cpython-39: module references __file__
pynbody.plot.__pycache__.stars.cpython-39: module references __file__
pynbody.sph.__pycache__.__init__.cpython-39: module references __file__
pynbody.sph.__pycache__._render.cpython-39: module references __file__
pynbody.sph.__pycache__.kdmain.cpython-39: module references __file__`

**Setup:**
 - MacOS 11.0.1
 - Python version 3.9.0
 - Numpy version 1.19.4
 - Pynbody version 1.0.2

**Comment by apontzen** [comment]
I believe the issue is with python 3.9.0 and the pre-compiled cython files in the pip archive.

Try installing direct from the git repository (`pip install git+https://github.com/pynbody/pynbody.git`) and provided you have a recent version of cython installed I think you will find it works OK.

I'll update the pip archive when there is a moment to do so.

**Comment by jackjack14** [comment]
Thank you for the reply. It works now, however I had to build manually `git clone https://github.com/pynbody/pynbody.git` 
and then `python3 setup.py install`. 
Installing directly with pip did not work, it gave another error: 

```
 RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
  RankWarning: Polyfit may be poorly conditioned
  
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/5q/xc22bbms0qjdgmpsv2188ydh0000gn/T/tmpod_d7jd8 Check the logs for full command output.

```

**Comment by apontzen** [comment]
That’s an error from numpy, probably due to the staging behaviour of pip
combined with numpy + python 3.9 compatibility behaviour.
