### ISSUE TITLE
Issue loading gz files

### ISSUE THREAD

**Issue by yuhao** [pynbody/pynbody#619]
Hi, I am very new to this, but got an error when doing `pynbody.load(g15784.lr.01024.HeI.gz)`:

```
File "venv/lib64/python3.6/site-packages/pynbody/snapshot/__init__.py", line 2031, in load
    "File %r: format not understood or does not exist" % filename)
OSError: File 'g15784.lr.01024.HeI.gz': format not understood or does not exist
```

This works fine for `g15784.lr.01024.gz`.

**Comment by yuhao** [comment]
Thank you. A related question, is there a short description of the simulation data in the testdata?

**Comment by apontzen** [comment]
No, sadly not. It's a very dated set of simulations intended as data for use with the tests - was never really meant for anything much beyond that. But the particular file you are looking at is from the "MUGS" suite (Stinson et al 2010, https://ui.adsabs.harvard.edu/abs/2010MNRAS.408..812S/abstract)

There are some more useful sets of test data available from the tangos tutorials here https://pynbody.github.io/tangos/first_steps.html -- although the page describes using them with tangos, there is no reason you can't just follow the download links then use them with plain-old-pynbody instead.

**Comment by yuhao** [comment]
Thank you.
