### ISSUE TITLE
Using a bridge with a halo catalog object

### ISSUE THREAD

**Issue by chaoticinflaton** [pynbody/pynbody#620]
I want to create a subsnap from a snapshot including only those particles that are present within the halos found in another snapshot. 

Is there an easy way to do this using the halos object?

For instance, I load the "reference" snapshot, sn_r. I also have the halo and halo particle catalog. Now, I want to find the particles that are in halos in sn_r in another snapshot, called sn_n. 

How can this be accomplished?

**Comment by apontzen** [comment]
There isn't a built-in way to do this, but you can do it fairly efficiently as follows:

```
f = pynbody.load(filename_1)
f2 = pynbody.load(filename_2)

h = f.halos()
h.make_grp()

b = f.bridge(f2)
b(b(f2))['grp'] = b(b(f))['grp']
f2_in_f1_halos = f2[f2['grp']!=0]
```

Does this help?

**Comment by chaoticinflaton** [comment]
Yes, this works! Thanks so much!
