### ISSUE TITLE
Changing properties for new tipsy snapshots

### ISSUE THREAD

**Issue by tigikay** [pynbody/pynbody#625]
I've been trying to create a script that loads snapshots, removes the dark matter particles, and the saves as a new snapshot.

I could not find any function that would permit the removal of a particle family, so I moved onto creating a new tipsy snapshot

`f=pb.new(gas=len(sim.g),star=len(sim.s))`

and then assigning all the values from the original simulation into the new snapshot

```
for i in sim.s.keys():
    f.s[i]=sim.s[i]
for i in sim.g.keys():
    f.g[i]=sim.g[i]
```

This has worked to some degree, however, a common issue I've found is that when using pynbody.new and pynbody.write it is not possible to set sim.properties['time'] without it being set to a default value like 1 Gyr after writing.

Overall my question is twofold:

- Is there a simpler way of loading a simulation, stripping a family of particles, then writing it while preserving the 'time' parameter?
- If not and I'm on the right track with my method, is there a more efficient way of doing this while also preserving/carrying over the 'time' parameter?

**Comment by apontzen** [comment]
* Removing dark matter particles: no, there is no built-in way to do this, and you are probably using the best work-around I could think of
* Time parameter: try passing `cosmological=False` to `write()` -- does this help?

**Comment by tigikay** [comment]
Yes the `cosmological=False` worked, thank you.

Only issues is that there is always a small time difference between the resulting and initial snapshots.

Is there a more proper way of transferring properties than

`new_sim.properties={'time':old_sim.properties['time']}`

**Comment by tigikay** [comment]
Very minor, but I want to make sure that there is no underlying issue.

old_sim, `Unit("5.46e+00 s kpc km**-1")`
new_sim, `Unit("5.45e+00 s kpc km**-1")`

which results in 
`5.337 Gyr` and `5.331 Gyr` difference

I guess when I use write() it still assigns it's own units?

**Comment by apontzen** [comment]
I am closing this issue for now but feel free to reopen if problem re-emerges.
