### ISSUE TITLE
Issues in the calculation of the spherical polar coordinates

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/pynbody#636]
Hi,

I think I have found two issues with the derived computations transforming into spherical polar coordinates:

1) The computation of the theta-component of the velocity in spherical polar coordinates is currently bugged: 
https://github.com/pynbody/pynbody/blob/5e97777552161c29eaed37f20252c5b815041e49/pynbody/derived.py#L108-L113

where the last velocity component should be `vz` rather than `vy`

Here are some minimal tests demonstrating the issue:
```
# Should find that x = r cos(azimuth) cos(polar declination)
#                  y = r sin(azimuth) cos(polar declination)
#                  z = r cos(polar declination)

np.testing.assert_allclose(sphere.st['x'], sphere.st['r'] * np.cos(sphere.st['az']) * np.sin(sphere.st['theta']))
np.testing.assert_allclose(sphere.st['y'], sphere.st['r'] * np.sin(sphere.st['az']) * np.sin(sphere.st['theta']))
np.testing.assert_allclose(sphere.st['z'], sphere.st['r'] * np.cos(sphere.st['theta']))

# Should find vr = vx * cos(azimuth) sin(polar declination) + vy sin(azimuth) sin(polar declination) + vz cos (polar declination)
vr = np.sin(sphere.st['theta']) * np.cos(sphere.st['az']) * sphere.st['vx'] + np.sin(sphere.st['theta']) * np.sin(sphere.st['az']) * sphere.st['vy'] + np.cos(sphere.st['theta']) * sphere.st['vz']
np.testing.assert_allclose(vr, sphere.st['vr'])

# Should find vphi = - vx * sin(azimuth) + vy cos(azimuth) + 0
vphi = - np.sin(sphere.st['az']) * sphere.st['vx'] + np.cos(sphere.st['az']) * sphere.st['vy']
np.testing.assert_allclose(vphi, sphere.st['vphi'])

# Should find vtheta = vx * cos(azimuth) cos(polar declination) + vy sin(azimuth) cos(polar declination) - vz sin (polar declination)
vtheta = np.cos(sphere.st['theta']) * np.cos(sphere.st['az']) * sphere.st['vx'] + np.cos(sphere.st['theta']) * np.sin(sphere.st['az']) * sphere.st['vy'] - np.sin(sphere.st['theta']) * sphere.st['vz']
np.testing.assert_allclose(vtheta, sphere.st['vtheta'])

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/var/folders/p9/_7j4sr91773fnjnfplf1ydmm0000gn/T/ipykernel_23816/3096593999.py in <module>
      3 
      4 np.testing.assert_allclose(vtheta_bugged, sphere.st['vtheta'])
----> 5 np.testing.assert_allclose(vtheta, sphere.st['vtheta'])

    [... skipping hidden 1 frame]

/opt/local/anaconda3/lib/python3.9/site-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    840                                 verbose=verbose, header=header,
    841                                 names=('x', 'y'), precision=precision)
--> 842             raise AssertionError(msg)
    843     except ValueError:
    844         import traceback

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 3317919 / 3317919 (100%)
Max absolute difference: 948.45969908
Max relative difference: 21739494.6855386
 x: array([ -0.867811,   5.407057,  11.310157, ..., -29.631147,  18.757444,
        -8.00515 ])
 y: SimArray([ -89.231716,  106.499345, -185.879866, ...,  -25.760905,
             2.417598,   11.836589])
```

2) When changing orientations, centering or any snapshot transformations, the `x, y, z, vx, vy, vz` arrays are updated following the change of frame of reference. But the derived arrays are derived once and for all and are never updated, leading  to very confusing behaviour.

For example, the same tests as above suddenly don't work because `x, y, z` have been rotated but the `phi, theta` angles have stayed the same
```

pynbody.analysis.angmom.faceon(sphere.st)

np.testing.assert_allclose(sphere.st['x'], sphere.st['r'] * np.cos(sphere.st['az']) * np.sin(sphere.st['theta']))
np.testing.assert_allclose(sphere.st['y'], sphere.st['r'] * np.sin(sphere.st['az']) * np.sin(sphere.st['theta']))
np.testing.assert_allclose(sphere.st['z'], sphere.st['r'] * np.cos(sphere.st['theta']))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/var/folders/p9/_7j4sr91773fnjnfplf1ydmm0000gn/T/ipykernel_23816/680787550.py in <module>
      1 pynbody.analysis.angmom.faceon(sphere.st)
----> 2 np.testing.assert_allclose(sphere.st['x'], sphere.st['r'] * np.cos(sphere.st['az']) * np.sin(sphere.st['theta']))
      3 np.testing.assert_allclose(sphere.st['y'], sphere.st['r'] * np.sin(sphere.st['az']) * np.sin(sphere.st['theta']))
      4 np.testing.assert_allclose(sphere.st['z'], sphere.st['r'] * np.cos(sphere.st['theta']))

    [... skipping hidden 1 frame]

/opt/local/anaconda3/lib/python3.9/site-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    840                                 verbose=verbose, header=header,
    841                                 names=('x', 'y'), precision=precision)
--> 842             raise AssertionError(msg)
    843     except ValueError:
    844         import traceback

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 3317919 / 3317919 (100%)
Max absolute difference: 387.41509053
Max relative difference: 5525157.11470859
 x: SimArray([ 11.915663,  61.871565, 102.835762, ...,  58.749114,  58.844956,
           58.747145])
 y: SimArray([ 60.492471, -18.270879, -39.392864, ...,  90.469473,  90.496467,
           90.568392])

```

Bug 1 is trivial to fix, and has been in the code since ce14c55ad4e9b12c2613703bcd5c4c5df41c5609 as far as I can tell. I will submit a one-line fix and tests asap.

How to treat issue 2 is a less clear to me, as I am unsure whether there are mechanisms to force derived arrays to be recomputed following updates in their native arrays. The same behaviour likely also affects the spherical polar derived quantities `rxy, vrxy, vcxy` which seem to behave in a similar way.  

Let me know what you think,
Martin

**Comment by Martin-Rey** [comment]
I have made progress understanding the second part of my issues, and I think it arises from a generic behaviour of pynbody which could affect any derived arrays.

Derived arrays from `x, y, z` or `vx, vy, vz` get correctly flagged has being dependent on the 1D position and velocity arrays. For example the azimuth angle is in the dependencies of `x, y` when derived through a minimal example:
```
s['az']

s._dependency_tracker.get_dependents('x')
{'az'}

s._dependency_tracker.get_dependents('y')
{'az'}
``` 

However, when the 1D position arrays are processed through the dependency tracker, they get mapped to their 3D counterparts through 
https://github.com/pynbody/pynbody/blob/6ff3514afbca7bdf174efce625848678c578b3e8/pynbody/snapshot/__init__.py#L1464-L1468

The dependency tree that is actually checked is that of `pos` and `vel`, rather than that of `x, y, z`. In the minimal example deriving the azimuth, the `pos` array has no dependency and does not track any underlying dependency on 1D arrays:
```
s._dependency_tracker.get_dependents('pos')
set() # Empty set
```

This means that the azimuth is never updated when doing a coordinate transform, because it never depends on `pos`. The problem "magically" doesn't appear for other derived arrays such as the polar angle `theta` or `vr, vtheta, vphi`  because they end up recursively depending on `pos` and `vel` through the radius `r` and `vr` which are themselves derived from `pos` and `vel` rather than their 1D components:
https://github.com/pynbody/pynbody/blob/6ff3514afbca7bdf174efce625848678c578b3e8/pynbody/derived.py#L26-L29


I think there are two ways to solve this 
1) Accept this as a behaviour and make derived arrays always use a version of `pos` and `vel`for calculations while raising a big documentation warning about this necessity.

2) Fix the mapping from 1D to 3D to ensure that any 1D dependencies are also added to 3D. I think this would be much cleaner but I might need advice on how to best do this because I am quite unfamiliar with the code, and feel like the mapping from 1D to 3D might be necessary for some other parts of the code.

**Comment by apontzen** [comment]
I agree the second solution is better. I suspect the thing to do may be to look at line 349 of snapshot's `__init__.py` where the dependency is actually recorded. Could it always map this to the 3D name? Since on line 1468 the 1D name is always translated into a 3D name, this would seem to match across the two points where the names are referenced.

It's a long time since I touched any of this code, so I may be wrong, but this is worth a go to see if it works without breaking anything else.

**Comment by Martin-Rey** [comment]
Thanks, I think PR #637 now addresses this issue cleanly, by adding all 1D dependencies to their parent 3D. This seems to go through all previous tests, plus the ones I added to check for this behaviour in the context of the polar coordinates.

Let me know what you think
