### ISSUE TITLE
[Feature Request] Add Colab button to example notebook

### ISSUE THREAD

**Issue by SauravMaheshkar** [pynbody/pynbody#638]
I noticed that the [**`pynbody_demo`**](https://github.com/pynbody/pynbody/blob/master/examples/pynbody_demo.ipynb) notebook doesn't have a "Open in Colab" button and has a ValueError. Having the button would make experimentation extremely easy.

More than happy to take this up.

**Comment by apontzen** [comment]
Very happy for you to go ahead with this suggestion and open a pull request! Thanks

**Comment by SauravMaheshkar** [comment]
Request for Review @apontzen

**Comment by apontzen** [comment]
Thanks! Would it be worth adding a cell that does `!pip install pynbody`? I am not much used to colab so I am not familiar with the norms.

**Comment by SauravMaheshkar** [comment]
Oh yes, sorry forgot to add that.
