### ISSUE TITLE
pynbody not centering halos

### ISSUE THREAD

**Issue by milanq14** [pynbody/pynbody#685]
Hey!

so im working with some simulation data which I have no problem loading. I also have no problem when loading the halos, but when I try to center them with:
pynbody.analysis.halo.center(h[1])
I always get the error:
Insufficient particles around center to get velocity

no matter the mode i choose ('hyb','pot,...)

**Comment by milanq14** [comment]
In fact, get the values for density, velocity etc for each halo. For instance, 
In [7]: len(h[1])
Out[7]: 8022957

In [11]: h[1].gas['rho']
Out[11]: 
SimArray([3.7844345e+06, 1.0513699e+07, 7.7620280e+06, ..., 3.3675325e+03,
          2.1280855e+02, 1.5987448e+04], dtype=float32, 'Msol kpc**-3')

In [12]: h[1].gas['vel']
Out[12]: 
SimArray([[-253.6705 ,  363.24857, -291.52673],
          [-252.76956,  355.28528, -200.86699],
          [-241.95026,  336.48352, -236.81317],
          ...,
          [-364.043  ,  438.04584, -492.67557],
          [-405.88638,  539.47284,  -76.88934],
          [-367.68112,  409.06116, -497.98166]], dtype=float32, 'km s**-1')

**Comment by milanq14** [comment]
Hey. So I fixed the issue uncommenting some of the first lines in the .pynbodyrc file, namely:
[gadget-units]
vel: km s^-1 a^1/2
mass: 1E10 Msol h^-1
pos: kpc a h^-1

I was giving it some wrong units (the boxsize was 3 orders of magnitudes bigger than it shoud) which wass messing up pynbody. That solved all the problems.

Thanks for your answer!!

**Comment by Martin-Rey** [comment]
Great to hear you solved it -- feel free to close this issue if it is resolved!
