### ISSUE TITLE
wrong kernel gradient in smooth.cpp

### ISSUE THREAD

**Issue by TobiBu** [pynbody/pynbody#693]
Hi Andrew,

while working on PR #692 I realised that the kernel gradient of the cubic spline kernel in e.g. smooth.cpp in line 763 following is wrong.

This is what's in the code:
`r2 = fList[j];
q2 = r2*ih2;
r = sqrt(r2);
q = sqrt(q2);
// Kernel gradient
if (q < 1.0) rs = -3.0*ih + 2.25*r*ih2;
else rs = -0.75*(2-q)*(2-q)/r;
rs *= fNorm;`

While this is what I derive and what's also coded in e.g. [pySPH](https://pysph.readthedocs.io/en/latest/_modules/pysph/base/kernels.html#CubicSpline)

Can you confirm that 

1. one line needs to read: `if (q < 1.0) rs = -3.0*q + 2.25*q2;`
2. the other line simply needs to be: `else rs = -0.75*(2-q)*(2-q);`

If this is correct I'll go about and fix it in PR #692

**Comment by apontzen** [comment]
Oh dear! I don't think I've ever used this, so if you could correct it and add a suitable test that would be much appreciated.

**Comment by TobiBu** [comment]
sure, I can do that.
What exactly do you mean by suitable test. Simply a unit test of this part of the code or a test for the correctness of the gradient, e.g. calculating the kernel gradient with an independent code like [pySPH](https://pysph.readthedocs.io/en/latest/_modules/pysph/base/kernels.html#CubicSpline)?

**Comment by apontzen** [comment]
Just something that tests the result, similar to this: https://github.com/pynbody/pynbody/blob/aa4bd2a0e9fb411d68c246daac7a2752e0020d2f/tests/sph_image_test.py#L53 

Obviously if you are confident about the reference answer being tested that makes the test better :-)

**Comment by TobiBu** [comment]
great, I'll see how easy it is to use pySPH to get some reference for the kernel gradient. 
Do keep things clean, I'll do a new pull request to first fix the kernel gradient of the cubic spline kernel and then add the appropriate WendlandC2 kernel support in Eva's pull request PR #692 separately.

**Comment by TobiBu** [comment]
wait, I might have confused myself here. Let me double check.

**Comment by TobiBu** [comment]
yes, I completely confused myself by the variable transformation inside the kernel gradient. Sorry. I'm closing this and PR#694 is obsolete.
