### ISSUE TITLE
`xdrlib` 

### ISSUE THREAD

**Issue by jobovy** [pynbody/pynbody#700]
**Describe the bug**

`xdrlib` is deprecated and slated for removal in Python 3.13 (see [PEP 594](https://peps.python.org/pep-0594/#xdrlib); less than two years from now). Used in
https://github.com/pynbody/pynbody/blob/2f6647b93384583c7275ef190d814a8d3ec7826d/pynbody/snapshot/nchilada.py#L14

**To Reproduce**

```
from pynbody.snapshort import nchilada
```
raises a DeprecationWarning.

**Expected behaviour or result**

No DeprecationWarning

**Setup (please complete the following information):**
 - Python 3.11
 - pynbody: 1.3.0

**Additional context**

Issue popped up in `galpy`'s CI (see, e.g., [here](https://github.com/jobovy/galpy/actions/runs/3987639158/jobs/6837735334#step:20:65)), where I now turn all DeprecationWarnings into errors to guard against future issues. I'm sure I can work around this....

**Comment by apontzen** [comment]
Thanks Jo. I guess quick-fix will be to import this module 'on demand' when someone tries to load an nchilada file rather than when pynbody is imported, so that at least it doesn't break the whole of pynbody.

**Comment by jobovy** [comment]
Not an ideal option, but a very quick fix would just be to move the import to just before this line:
https://github.com/pynbody/pynbody/blob/2f6647b93384583c7275ef190d814a8d3ec7826d/pynbody/snapshot/nchilada.py#L36
because I think that's the only line where it's used. Of course, eventually, you'll have to find an alternative library. It doesn't seem like the standard library is having a replacement in mind.

Presumably, not many people are running `pynbody` with deprecation warnings turned into errors, so this really only needs to be fixed when you want to support Python 3.13. I just thought I should flag it because I've recently been bitten by a `numpy` deprecation warning that I ignored for too long and that is now breaking a lot of code.

**Comment by apontzen** [comment]
Given how it is only used in that one place, it will hopefully be easy to replace even if nobody develops an external package. But I agree for the moment that moving the `import` to that location would be fine.
