### ISSUE TITLE
I can't install pynbody

### ISSUE THREAD

**Issue by hhatam** [pynbody/pynbody#716]
Hi.
I tried `pip install pynbody` and get this error :

```
 
File "<string>", line 68, in <module>
        File "<string>", line 29, in check_for_pthread
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1

```

Tried installing using git and the result was the same. I even tried installing different version of pynbody and wheel as well and even reinstalled my Anaconda and still encounter the same error.

I tried importing pynbody as a module by inserting pynbody folder next to my code and this is what I get:

cannot import name '_util' from partially initialized module 'pynbody' (most likely due to a circular import) (C:\Users\pynbody\__init__.py)

Can you help me install this package I really need this. 
Thanks.

**Comment by apontzen** [comment]
It looks like you're trying to use pynbody on windows, which unfortunately isn't supported except under WSL installations (https://learn.microsoft.com/en-us/windows/wsl/install). We ought to improve the error message though!

**Comment by hhatam** [comment]
> It looks like you're trying to use pynbody on windows, which unfortunately isn't supported except under WSL installations (https://learn.microsoft.com/en-us/windows/wsl/install). We ought to improve the error message though!

Thank you for your response.
I installed WSL 2 but it didn't resolved my issue.

**Comment by apontzen** [comment]
If you're getting the same error message, sounds like you're still running python inside windows rather than WSL. It's not enough just to install WSL, unfortunately; you need to install a Linux distro inside WSL, and run python within that. There's lots of tutorials on the web about doing this. Once everything is working, you can pip install from within the linux shell.
