### ISSUE TITLE
Calculate derived arrays only for particles of family type

### ISSUE THREAD

**Issue by isaacgcarbajal** [pynbody/pynbody#720]
Hi!

I was reading the documentation and I saw that there are the functionality called "derived_arrays" that uses other arrays to calculate new quantities and the best of all is that there are only calculated "on demand".

I want to create derived_arrays but only for a kind of particle. In particular I want to add a quantity called "mag" to the stellar particles, which are the magnitudes in 5 bands of all the stellar particles but only load them into memory when I need them.

Following the documentation I made the next minimal code that explains what I'm trying to do

```
import pynbody
import numpy as np

# Expected only for stellar particles
@pynbody.derived_array
def mag(sim):
    return np.random.random((10, 5))

# Generate a new simulation
sim = pynbody.new(dm=30, star=10, gas=20)

# try to calculate derived array
sim.s['mag']
```

where the random array represents the 5 stellar magnitudes of the 10 particles in this case.

This works but if by "mistake" I try to calculate the "mag" quantity for all the simulation it tries to calculate it giving me the next error

```
In [6]: sim['mag']
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 1
----> 1 sim['mag']

File ~/anaconda3/envs/pgsf++-dev/lib/python3.9/site-packages/pynbody/snapshot/__init__.py:258, in SimSnap.__getitem__(self, i)
    254 """Return either a specific array or a subview of this simulation. See
    255 the class documentation (:class:`SimSnap`) for more information."""
    257 if isinstance(i, str):
--> 258     return self._get_array_with_lazy_actions(i)
    259 elif isinstance(i, slice):
    260     return SubSnap(self, i)

File ~/anaconda3/envs/pgsf++-dev/lib/python3.9/site-packages/pynbody/snapshot/__init__.py:358, in SimSnap._get_array_with_lazy_actions(self, name)
    356         self.__load_if_required(name)
    357     if not self.lazy_derive_off:
--> 358         self.__derive_if_required(name)
    360 return self._get_array(name)

File ~/anaconda3/envs/pgsf++-dev/lib/python3.9/site-packages/pynbody/snapshot/__init__.py:373, in SimSnap.__derive_if_required(self, name)
    371 def __derive_if_required(self, name):
    372     if name not in list(self.keys()):
--> 373         self._derive_array(name)

File ~/anaconda3/envs/pgsf++-dev/lib/python3.9/site-packages/pynbody/snapshot/__init__.py:1455, in SimSnap._derive_array(self, name, fam)
   1450     write_array = self[fam]._get_array(
   1451         name, always_writable=True)
   1453 self.ancestor._autoconvert_array_unit(result)
-> 1455 write_array[:] = result
   1456 if units.has_units(result):
   1457     write_array.units = result.units

File ~/anaconda3/envs/pgsf++-dev/lib/python3.9/site-packages/pynbody/array.py:711, in _dirty_fn.<locals>.q(a, *y, **kw)
    709     return w(a, *y, **kw)
    710 else:
--> 711     return w(a, *y)

File ~/anaconda3/envs/pgsf++-dev/lib/python3.9/site-packages/pynbody/array.py:499, in SimArray.__setitem__(self, item, to)
    497     np.ndarray.__setitem__(self, item, to.in_units(self.units))
    498 else:
--> 499     np.ndarray.__setitem__(self, item, to)

ValueError: could not broadcast input array from shape (10,5) into shape (60,5)

``` 

what I expected because the length of the stars is different than the length of all the simulation particles. 

Is there any way to add this type of quantities only to a specific type of particle?

Thanks for your time!

**Comment by apontzen** [comment]
This isn't currently a feature, with the presumption being that people will access properties relevant to the particular family (which seems to be working according to your report).

One reason for this is that it would seem unnecessarily restrictive -- if something _can_ be calculated, the framework shouldn't really stand in the way.

You should find that if you replace your hard-coded array shape with an actual calculation that it "just works" when accessed correctly, and raises a reasonably meaningful message when not. However if there is a vital reason why you need to explicitly restrict things to a particular family, do post back...

**Comment by isaacgcarbajal** [comment]
Actually there is no reason to "force" the restriction to a specific family other than that the dark matter particles cannot have stellar magnitudes. But being careful to calculate only for the stars it's enough.

Thank you, and congrats for this code!
