### ISSUE TITLE
Typing incompatible with Python 3.8

### ISSUE THREAD

**Issue by jobovy** [pynbody/pynbody#753]
The type hints here:
https://github.com/pynbody/pynbody/blob/f2635598c52b22f92851a492ff53faaafd0a5449/pynbody/array/shared.py#L18-L20
introduced in #752 are incompatible with Python 3.8 (they were introduced in this form in [Python 3.9](https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections), see also [this StackOverflow answer](https://stackoverflow.com/a/75202688)). This leads to errors in Python 3.8, because the minimum version in ``setup.py`` is set to 3.8:
https://github.com/pynbody/pynbody/blob/f2635598c52b22f92851a492ff53faaafd0a5449/setup.py#L219

One way to fix this would be to:
- Bump the minimum Python version to 3.9 in ``setup.py``:
- Yank the current release from PyPI and upload a new version (this such that Python 3.8 installs will correctly install the last compatible version)

Alternatively, you could make the code Python 3.8 compatible by importing ``List`` from ``typing`` as per the StackOverflow answer above and then release a new version that fixes the issue for Python 3.8. Given that ``numpy`` has a minimum Python version of 3.9, just making the minimum 3.9 would be very reasonable.

**Comment by jobovy** [comment]
Update: These lines
https://github.com/pynbody/pynbody/blob/f2635598c52b22f92851a492ff53faaafd0a5449/pynbody/snapshot/tipsy.py#L300-L304
from #749 are also incompatible with Python 3.8. There might be more, this is just the first error I run into with ``pynbody`` v1.5.0 with Python 3.8, so perhaps again arguing for simply increasing the Python version requirement (of course, this also means that v1.5.0 is broken for Python 3.8).

**Comment by apontzen** [comment]
Sorry about that jo and thanks for highlighting! The mistake is in the minimum python version, since 3.8 is now deprecated. I'll fix this and yank the version so that python3.8 should (theoretically) pick up an older, compatible version.

**Comment by jobovy** [comment]
No worries, I know how hard it is to get the minimum Python version right! I only hit this issue in ``galpy``'s CI and will just pin ``pynbody`` to 1.4.2 until I also drop Python 3.8, but if you yank, I think you need to yank both 1.5.0 and 1.5.1. As you probably know, if you wanted to keep those versions, you could just do ``1.5.0.post0`` and ``1.5.1.post0`` release that just change the minimum Python version, but it might not be worth the hassle.

**Comment by jobovy** [comment]
> Thanks. I've uploaded 1.5.2 and will now yank 1.5.1 - are you sure yanking 1.5.0 is needed? I thought this was before the breaking change. Would be v helpful if you can check as I don't have a working py3.8 environment at present.

Yes, v1.5.0 also failed to import with Python 3.8 because of these lines introduced in #749:
https://github.com/pynbody/pynbody/blob/f2635598c52b22f92851a492ff53faaafd0a5449/pynbody/snapshot/tipsy.py#L300-L304
See this CI run: https://github.com/jobovy/galpy/actions/runs/7095380993/job/19312206131

**Comment by apontzen** [comment]
Thanks - I think this is now fixed. I'm closing the issue but feel free to reopen if there is still a problem.
