### ISSUE TITLE
AHF files throwing an error when reading in the substructure list

### ISSUE THREAD

**Issue by EthTay** [pynbody/pynbody#768]
Using the template below will help us reproduce your problem, which is an essential first step in helping or improving the code. Feel free to customise the template if you are used to raising bug reports, but be sure that you give us enough information to start investigating.

**Describe the bug**
A clear and concise description of what the bug or inaccuracy is.

**To Reproduce**
s=pynbody.load('path/to/snapshot/with/ahf/halofinder/files')
h=s.halos()
>pynbody.halo : An error occurred while reading substructure file. Falling back to using the halo info.

**Expected behaviour or result**
correctly reading the substructure file, this makes no difference to what data is presented as the substructure is still correctly presented but it then reads the halo file rather than the substructure file

**Setup (please complete the following information):**
 - OS = linux
 - Python version = 3.10
 - Numpy version = 1.22.2
 - Pynbody version = 1.5.2

**Additional context**
this is fixed in PR #767

**Comment by apontzen** [comment]
This issue is believed to be fixed (via a different mechanism than the proposed PR). Please re-open if not!
