### ISSUE TITLE
KeyError: 'mass'

### ISSUE THREAD

**Issue by ttepperg** [pynbody/pynbody#771]
On Pynbody 1.3.1 I'm experiencing a KeyError issue. Specifically, when loading a Ramses output and trying to retrieve the 'mass' array:

s = pynbody.load('output_00029') 
s['mass']

results in:

KeyError: "'mass' is a family-level array for [<Family dm>, <Family star>, <Family cloud>, <Family sink>]. To use it over the whole simulation you need either to delete it first, or create it separately for [<Family gas>]."

I can get around the issue by doing first:

s.g['mass']

Here is a link to a Dropbox folder containing:
= A script to reproduce the result
- The simulation output
- A Pynbody config file in case neeed

https://www.dropbox.com/scl/fo/uchb8v3tjpvsjj7rt2rtp/h?rlkey=emel04j866jom7negkxv0gv3g&e=1&dl=0

**Comment by ttepperg** [comment]
Hi Rick,

No, it does not make sense, at least to me.

The ‘mass’ array is a valid key for all families, and retrieving
it from the global snapshot object should work. This is different from,
say, ‘iord’, which not necessarily exists for all families and trying to
do s[‘iord’] without defining it for all families first raises an error.

Be that as it may, it normally works, in fact, it is the first time in 7+ years or
so of using Pynbody that I’ve had the issue. In the github issue I’ve uploaded two sim
outputs; for one it works, for the other it fails. Check for yourself.
No fundamental difference between the snapshots though, which makes
the issue a bit weird.

Cheers

Thor

_______________________________________________
Dr. Thor Tepper García | Astrophysicist
Sydney Institute for Astronomy (SIfA)
The University of Sydney
www.thorsten.mx<http://www.thorsten.mx>

The University of Sydney
A globally ranked university<https://www.sydney.edu.au/about-us/our-world-rankings.html>
Top 20 university in the world | 1st for sustainability in Australia
*QS World University Rankings 2024



From: Rick Sarmento ***@***.***>
Date: Friday, 23 February 2024 at 12:01
To: pynbody/pynbody ***@***.***>
Cc: Thorsten Tepper Garcia ***@***.***>, Author ***@***.***>
Subject: Re: [pynbody/pynbody] KeyError: 'mass' (Issue #771)

Doesn't that make sense? You have to ask for the mass either for the gas or dark matter family:

s.g['mass']
or
s.dm['mass']

to get a mass for a cell.

**Comment by apontzen** [comment]
Thanks Thor. Do I understand correctly that you see the issue on the provided sample snapshot but not on certain others? Would be helpful to know which snapshots the issue _doesn't_ arise on, to help refine where the problem may lie specifically.

**Comment by earnric** [comment]
I'll try on one of my snaps later today. I guess I've always just worked with gas or dm independently -- or summed them. I never remember doing it differently.

**Comment by ttepperg** [comment]
Hi Andrew,

As a matter of fact, I’ve never before experienced this issue; the only case / sim
is the one called hbd_10_gd111_s4_star (any snapshot, but I’ve uploaded one
representative). This simulation differ froms the other I’ve also uploaded in
that it contains sinks and ‘cloud’ particles. That said, I’ve had simulations like
that in the past but never encountered this issue.

Cheers

Thor

_______________________________________________
Dr. Thor Tepper García | Astrophysicist
Sydney Institute for Astronomy (SIfA)
The University of Sydney
www.thorsten.mx<http://www.thorsten.mx>

The University of Sydney
A globally ranked university<https://www.sydney.edu.au/about-us/our-world-rankings.html>
Top 20 university in the world | 1st for sustainability in Australia
*QS World University Rankings 2024



From: Andrew Pontzen ***@***.***>
Date: Friday, 23 February 2024 at 19:44
To: pynbody/pynbody ***@***.***>
Cc: Thorsten Tepper Garcia ***@***.***>, Author ***@***.***>
Subject: Re: [pynbody/pynbody] KeyError: 'mass' (Issue #771)

Thanks Thor. Do I understand correctly that you see the issue on the provided sample snapshot but not on certain others? Would be helpful to know which snapshots the issue doesn't arise on, to help refine where the problem may lie specifically.

**Comment by apontzen** [comment]
This should now be fixed in the latest master branch - please reopen if not!

**Comment by ttepperg** [comment]
Hi Andrew,

Thanks for the quick response!

I’ll try it out and let you know if I encounter any issue.

Cheers

Thor

_______________________________________________
Dr. Thor Tepper García | Astrophysicist
Sydney Institute for Astronomy (SIfA)
The University of Sydney
www.thorsten.mx<http://www.thorsten.mx>

The University of Sydney
A globally ranked university<https://www.sydney.edu.au/about-us/our-world-rankings.html>
Top 20 university in the world | 1st for sustainability in Australia
*QS World University Rankings 2024



From: Andrew Pontzen ***@***.***>
Date: Monday, 25 March 2024 at 01:09
To: pynbody/pynbody ***@***.***>
Cc: Thorsten Tepper Garcia ***@***.***>, Author ***@***.***>
Subject: Re: [pynbody/pynbody] KeyError: 'mass' (Issue #771)

This should now be fixed in the latest master branch - please reopen if not!
