### ISSUE TITLE
[Question]: Minimal test data set to cover most of the functionality

### ISSUE THREAD

**Issue by Hellseher** [pynbody/pynbody#778]
Hi,

I try to stabilize tests while preparing version 1.6.0 for Guix and I've faced
with the issue where `pynbody` requires nearly 1.0GiB+ test data to satisfy test
suit. Due to that fact I had to disable most of the tests which require the
data.

A list of disabled tests.
```
--ignore=tests/copy_on_access_test.py
--ignore=tests/gravity_test.py
--ignore=tests/adaptahop_test.py
--ignore=tests/ahf_halos_test.py
--ignore=tests/array_test.py
--ignore=tests/bridge_test.py
--ignore=tests/family_test.py
--ignore=tests/partial_tipsy_test.py
--ignore=tests/snapshot_test.py
--ignore=tests/test_profile.py
--ignore=tests/gadget_test.py
--ignore=tests/gadgethdf_test.py
--ignore=tests/grafic_test.py
--ignore=tests/halotools_test.py
--ignore=tests/nchilada_test.py
--ignore=tests/ramses_new_ptcl_format_test.py
--ignore=tests/ramses_test.py
--ignore=tests/rockstar_test.py
--ignore=tests/sph_image_test.py
--ignore=tests/sph_smooth_test.py
--ignore=tests/subfind_test.py
--ignore=tests/subfindhdf_gadget4_test.py
--ignore=tests/tipsy_test.py
-k
not test_div_curl_smoothing
 and not test_float_kd
 and not test_kd_delete
 and not test_kd_issue_88
 and not test_kdtree_from_existing_kdtree
 and not test_kdtree_shared_mem
 and not test_neighbour_list
 and not test_particles_in_sphere
 and not test_periodic_smoothing
 and not test_smooth
 and not test_smooth_WendlandC2
```

Report: 53 passed, 100 deselected in 4.46s

Is there any bare minimal requirement for test data set to cover the most of the
functionality?

Thanks,
Oleg

**Comment by apontzen** [comment]
Unfortunately as an IO library it's very hard to test with only small files. It would be great to create a cutdown set of test files that still gain good coverage, but there's not enough human effort available. To add complication, the test data archive is now updated for v2 beta so won't work with 1.6.0. Sorry about that!
