### ISSUE TITLE
AHF substructure error

### ISSUE THREAD

**Issue by vepe99** [pynbody/pynbody#797]
Hi everyone,

when reading an AHF catalogue with pynbody version 1.6.0, I get the following error/warning for the substructure file:

`pynbody.halo : An error occurred while reading substructure file. Falling back to using the halo info.`

This error does not happen with pynbody version 1.3.1.

What does this tell me?
Shall I be concerned about this or can I kepp working with pynbody. All neccesary halo info seems to be there.

thanks in advance
Giuseppe and Tobias

**Comment by apontzen** [comment]
This is nothing to worry about if the information you need is present. The only difference in v1.6.0 is that it actually notifies you of the problem. V2.0 beta reimplements AHF reading, so you could also try that.

**Comment by vepe99** [comment]
Thank you!
