### ISSUE TITLE
Add help for `write_fpos` parameter in `AHFCatalogue`

### ISSUE THREAD

**Issue by manodeep** [pynbody/pynbody#819]
I noticed the `init` method of the `AHFCatalogue` class has a `write_fpos` parameter but no associated help. Would be good to add that. Looks like this writes out a text file containing the starting file offsets for particle ids for each halo (in sequential order). 

https://github.com/pynbody/pynbody/blob/8ebcd67c8e4019537bc5d852e6c0e1d579f2f545/pynbody/halo/ahf.py#L29

**Comment by apontzen** [comment]
Thanks, fixed!
