### ISSUE TITLE
Circular import error at import 

### ISSUE THREAD

**Issue by G-Francio** [pynbody/pynbody#865]
Using the template below will help us reproduce your problem, which is an essential first step in helping or improving the code. Feel free to customise the template if you are used to raising bug reports, but be sure that you give us enough information to start investigating.

**Describe the bug**
After installing by cloning the repo, I tried to run `import pynbody`. The import fails, and I receive the following error:

`cannot import name 'geometry_selection' from partially initialized module 'pynbody.filt' (most likely due to a circular import) ([...]/pynbody/filt/__init__.py)`

Full stacktrace is available at the bottom of this report.

**To Reproduce**
Open a Python interpreter and run `import pynbody`

Preferably reproduce the bug using pynbody's own test data (as used by the tutorials, and downloadable from
[zenodo](https://zenodo.org/doi/10.5281/zenodo.12552027). If this impossible, provide us a pointer to another file
that we can use to reproduce the problem. This file should be as small as possible to illustrate the problem, as it
may be incorporated into future versions of the test data.

**Expected behaviour or result**
The import is successful

**Setup (please complete the following information):**
 - OS: 
 ```
> lsb_release -a
Scientific Linux release 7.9 (Nitrogen)
``` 
It's a server I need to work on.

- Python version: 
```
Python 3.10.13
```
- Numpy version
```
1.26.3
```

- Pynbody version
```
2.0.0b14
```
(I presume, based on `pip list`)

**Additional context**
Full stacktrace

```
In [1]: import pynbody
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pynbody

File [...]/pynbody/pynbody/__init__.py:20
     18 from .configuration import config, logger, config_parser
     19 # isort: on
---> 20 from . import (
     21     analysis,
     22     array,
     23     bridge,
     24     configuration,
     25     derived,
     26     family,
     27     filt,
     28     gravity,
     29     halo,
     30     snapshot,
     31     sph,
     32     transformation,
     33     util,
     34 )
     37 # The PlotModuleProxy serves to delay import of pynbody.plot until it's accessed.
     38 # Importing pynbody.plot imports pylab which in turn is quite slow and cause problem
     39 # for terminal-only applications. However, since pynbody always auto-imported
     40 # pynbody.plot, it would seem to be too destructive to stop this behaviour.
     41 # So this hack is the compromise and should be completely transparent to most
     42 # users.
     43 class PlotModuleProxy:

File [...]/pynbody/pynbody/analysis/__init__.py:10
      1 """Tools for scientific analysis with pynbody
      2 
      3 This sub-package contains a number of modules that enable scientific analysis beyond the basic capabilities of pynbody.
   (...)
      7 
      8 """
---> 10 from . import (
     11     cosmology,
     12     halo,
     13     hifrac,
     14     hmf,
     15     ionfrac,
     16     luminosity,
     17     profile,
     18     ramses_util,
     19     theoretical_profiles,
     20 )
     21 from .angmom import faceon, sideon
     22 from .halo import center

File [...]/pynbody/pynbody/analysis/halo.py:17
     13 import warnings
     15 import numpy as np
---> 17 from .. import array, config, filt, transformation, units, util
     18 from . import _com, cosmology, profile
     20 logger = logging.getLogger('pynbody.analysis.halo')

File [...]/pynbody/pynbody/filt/__init__.py:24
     21 from numpy.typing import ArrayLike
     23 from .. import family, units
---> 24 from . import geometry_selection
     26 if TYPE_CHECKING:
     27     from .. import snapshot
```

**Comment by apontzen** [comment]
Are you by any chance trying to import it from within the source folder? Try changing directory before executing python and see if that helps

**Comment by G-Francio** [comment]
Reason #1 to not submit bug reports on Friday evening, you make idiot mistakes! Thanks, closing this, your suggestion solved it!

**Comment by G-Francio** [comment]
Given I opened a bug report, might as well ask a second thing @apontzen. In order to install the package with Numpy < 2.00 I had to add 

```
#if NPY_ABI_VERSION < 0x02000000
  #define PyDataType_ELSIZE(descr) ((descr)->elsize)
#endif
```

Otherwise I would get an error during at compile time while installing the package.

 To `pynbody/kdtree/kdmain.cpp`. Is this the expected behaviour, or was I missing once again something obvious?

Thanks a lot for the super quick answer in any case, and apologies for bothering given it was my fault...

**Comment by apontzen** [comment]
Hmm, no I wasn't aware that this would be required. If you are willing to open a PR that fixes it, that'd be handy.

(That said, if you install with `pip` then the build isolation should result in numpy 2 being used anyway. It's a bad idea to build a binary with numpy 1 because then you will have to rebuild everything once you upgrade to numpy 2, whereas numpy 2-built binaries are backwards compatible. As far as I understand, anyway.)

**Comment by G-Francio** [comment]
For some reason just using `pip install -e .[all]` did not work, but we had been fiddlling with the install process for a bit so we might also had broken something in doing that.

I'll still open the pull request, also for reference, I am not sure if adding those few lines will break compatibility with Numpy 2.0 though.

Thanks a lot for the support, closing this.
