### ISSUE TITLE
can't convert Ramses-3 snapshot to Tipsy

### ISSUE THREAD

**Issue by Rory-dot** [pynbody/pynbody#875]
Hi,

I am trying to use pynbody to convert a Ramses output directory to a Tipsy file (to then be passed to AHF). But it seems like pynbody doesn't recognise that it is a Ramses output. e.g.

>>> pynbody.analysis.ramses_util.convert_to_tipsy_fullbox('output_00024')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rsmith/.local/lib/python3.10/site-packages/pynbody/analysis/ramses_util.py", line 176, in convert_to_tipsy_fullbox
    raise ValueError("This routine can only be used for Ramses snapshots but you are calling with " + str(type(s)))
ValueError: This routine can only be used for Ramses snapshots but you are calling with <class 'str'>

If I simply load in the snapshot it works:
>>> import pynbody
>>> f = pynbody.load("output_00011")

And if I run the converter command, without specifying the Ramses output name, it seems to work:
 >>> pynbody.analysis.ramses_util.convert_to_tipsy_fullbox
<function convert_to_tipsy_fullbox at 0x7fd329d85090>

I am worried this is something to do with a change in the format of Ramses version 3 output files. I heard there are new families of particles now. But, honestly, I am not sure what the problem is. 

Any help would be really appreciated! Thanks!

**Comment by apontzen** [comment]
It looks like the routine expects a loaded SimSnap rather than a filename. The documentation is confusing on this issue but that’s what the code’s looking for. Let me know if this helps.

**Comment by apontzen** [comment]
Actually looking at it again the docs are also pretty unambiguous https://pynbody.readthedocs.io/latest/reference/_autosummary/pynbody.analysis.ramses_util.convert_to_tipsy_fullbox.html#pynbody.analysis.ramses_util.convert_to_tipsy_fullbox

**Comment by Rory-dot** [comment]
Thanks a lot for your quick response. That did help. I was thrown by one of the comments in ramses_util.py:

 For running AHF or pkdgrav, you can convert ramses files to tipsy format using
 >>> pynbody.analysis.ramses_util.convert_to_tipsy_fullbox('output_00101') # will convert the whole output
 
The 'output_00101' looks like one of the Ramses output directories. But indeed if I first load the output directory to a SimSnap, the convert command seems to run. Although, it throws a warning about there being no ionisation fractions, and fully breaks because there are no metals. I am not tracking metals in this simulation. Would I need to to be able to use pynbody to do the conversion? Or there is a way to modify the SimSnap to get around this?

Thanks again for your help!

>>> pynbody.analysis.ramses_util.convert_to_tipsy_fullbox(s)
/home/rsmith/.local/lib/python3.10/site-packages/pynbody/analysis/ramses_util.py:178: UserWarning: This routine currently makes the assumption that the ramses snapshot is cosmological
when converting units. Beware if converting isolated runs.
  warnings.warn("This routine currently makes the assumption that the ramses snapshot is cosmological\n"

/home/rsmith/.local/lib/python3.10/site-packages/pynbody/derived.py:229: UserWarning: No ionization fractions found, assuming fully ionised gas above 10^4 and neutral below 10^4K. This is a very crude approximation.
  warnings.warn("No ionization fractions found, assuming fully ionised gas above 10^4 and neutral below 10^4K. "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rsmith/.local/lib/python3.10/site-packages/pynbody/analysis/ramses_util.py", line 198, in convert_to_tipsy_fullbox
    s.g['metals'] = s.g['metal']
  File "/home/rsmith/.local/lib/python3.10/site-packages/pynbody/snapshot/simsnap.py", line 252, in __getitem__
    return self._get_array_with_lazy_actions(i)
  File "/home/rsmith/.local/lib/python3.10/site-packages/pynbody/snapshot/simsnap.py", line 370, in _get_array_with_lazy_actions
    return self._get_array(name)
  File "/home/rsmith/.local/lib/python3.10/site-packages/pynbody/snapshot/subsnap.py", line 352, in _get_array
    return self._subsnap_base._get_family_array(name, self._unifamily, index, always_writable)
  File "/home/rsmith/.local/lib/python3.10/site-packages/pynbody/snapshot/simsnap.py", line 1287, in _get_family_array
    raise KeyError("No array " + name + " for family " + fam.name) from None
KeyError: 'No array metal for family gas'

**Comment by apontzen** [comment]
Yes that bit of the docs is indeed wrong, I'll fix it.

You could either edit the code so that it doesn't demand the `metal` array to be present, or more simply, create it for yourself -- something like

```python
f = pynbody.load(...)
f.gas['metal'] = 0
pynbody.analysis.ramses_util.convert_to_tipsy_fullbox(f)
```

**Comment by Rory-dot** [comment]
Ah no, I spoke too soon. AHF is not happy when trying to read this tipsy file. I produced an AHF parameters input file with the following:

import pynbody
f = pynbody.load('output_00011')
f.gas['metal'] = 0
pynbody.analysis.ramses_util.convert_to_tipsy_fullbox(f)
pynbody.analysis.ramses_util.write_ahf_input(f,'output_00011_fullbox.tipsy')

Then I ran AHF and got this output from AHF:

./AHF-v1.0-115 AHF.input-example 
================================================================
	             A        H       H   FFFFFFFF    
	           A A       H       H   F           
	         A   A      H       H   F           
	       AAAAAAA     HHHHHHHHH   FFFFFF      
	     A       A    H       H   F           
	   A         A   H       H   F           
	 A           A  H       H   F       (v1.0/115)
================================================================


These are the input parameters you provided, please check them carefully again:
===============================================================================
ic_filename       = ../output_00011_fullbox.tipsy
ic_filetype       = 90
outfile_prefix    = hydrocosmosim3
time    = -115829609203737102730631664301010303066819845834391198228386910475912832369130358611950339103990974349957270478461390722939852377903967967970529057925091949073917979125560979336553275624259584.000000
nbodies = 682174469
ndim    = 50331648
nsph    = 2895266052
ndark   = 1922224128
nstar   = 176428544
Numerical Recipes run-time error...
Error in routine polint
...now exiting to system...


As you can see, the time looks messed up in the screen output from AHF. So, I tried adding the following step before running AHF: 

>>> pynbody.analysis.ramses_util.get_tform(f,times_are_proper = False)

/home/rsmith/.local/lib/python3.10/site-packages/pynbody/snapshot/ramses.py:1089: UserWarning: Assumed times to be in conformal units because no RT file was found. If this is incorrect, pass the `times_are_proper` keyword argument when loading the dataset, or set the option `proper_time` in your .pynbodyrc.
  warnings.warn(
SharedMemorySimArray([0.12239253, 0.13653941, 0.14272501, ..., 5.96289317,
                      5.96289317, 5.96289317], 'Gyr')

The numbers at the end (5.96 Gyr) seem about right for this snapshot. But when I reran AHF, the screen output still shows the strange value for time. 

Finally, I checked the AHF log file, and it seems something else is strange with the units or the number format/precision. In the part about reading the file, there are infinity velocities, and the positions seem to be nonsense numbers: Extreme positions: xmin = -3.40278e+38  xmax = 3.40273e+38.

I cut and paste the AHF output that looks strange below. So sorry for all these messages, but I am just hoping you have seen this before and there is some simple fix for the format of the numbers.  Thanks so much once again.

-------------------------------------------------------------------------------
  A-2.2  Reading
-------------------------------------------------------------------------------

Obviously the file uses float for floating point values (4 bytes).
A total of 682174469 particle masses with 4 bytes per float (2602.289062 MB total) a
re stored.
Asked to read 682174469 and to skip 0 particles. Checking those numbers.
WARNING: x-Separation of particles exceeds boxsize (6.80552e+38 > 50). Setting scale
_pos accordingly!
WARNING: y-Separation of particles exceeds boxsize (6.80541e+38 > 50). Setting scale
_pos accordingly!
WARNING: z-Separation of particles exceeds boxsize (6.80541e+38 > 50). Setting scale
_pos accordingly!
Extreme positions: xmin = -3.40278e+38  xmax = 3.40273e+38
                   ymin = -3.40273e+38  ymax = 3.40268e+38
                   zmin = -3.40263e+38  zmax = 3.40278e+38
Applying shift: (3.40278e+38, 3.40273e+38, 3.40263e+38)
Scaling by:  positions:  1.4694e-39
             velocities: inf
             weights:    1e-40
             energies:   0

-------------------------------------------------------------------------------
  A-2.3  Short sanity check
-------------------------------------------------------------------------------

First particle:
    positions (x,y,z):      0.500004  0.499996  0.499981
    velocities (vx,vy,vz):  -inf  -inf  inf
    weight:                 -6.51884e-42
    ID:                     2098652672
    energy:                 0
Last particle:
    positions (x,y,z):      0.500004  0.499996  0.499981
    velocities (vx,vy,vz):  -nan  -nan  -nan
    weight:                 0
    ID:                     2780827140
    energy:                 0

**Comment by apontzen** [comment]
Looks to me like your problem is with the endianness of your platform. Are you converting the file on a different platform from where you are running AHF? Either way, check whether AHF has an option to switch the endianness convention. Pynbody transparently figures out the right endianness when loading a file, but AHF may not.

**Comment by Rory-dot** [comment]
Yes, in case anyone runs into the same problem, there is indeed a flag when you compile AHF that allows you to switch the endianness. It is called 'Byteswap' (you can find the exact name in the AHF userguide). 

That fixed it, and I now have sensible times, positions, velocities and everything. The AHF halo catalogues look great.

Thanks so much for all the support with this. It was incredibly helpful. This time the issue will stay closed!
